ODPOWIEDNIKI=
  <
    ODPOWIEDNIK=< LISTA=[

                        ]>
    ODPOWIEDNIK=< LISTA=[

                        ]>
    ODPOWIEDNIK=< LISTA=[

                        ]>
    ODPOWIEDNIK=< LISTA=[

                        ]>
    ODPOWIEDNIK=< LISTA=[

                        ]>
						
//Створки оконные
    ODPOWIEDNIK=< LISTA=[ //Створка оконная малая

                        ]>
											
    ODPOWIEDNIK=< LISTA=[ //Створка оконная большая

                        ]>
						
    ODPOWIEDNIK=< LISTA=[ //Створка оконная малая ПВХ

                        ]>	

    ODPOWIEDNIK=< LISTA=[ //Створка оконная больщая ПВХ

                        ]>							

    ODPOWIEDNIK=< LISTA=[ //Створка с усилителем

                        ]>
//Рама оконная
    ODPOWIEDNIK=< LISTA=[ //Рама оконная малая

                        ]>
    ODPOWIEDNIK=< LISTA=[ //Рама оконная большая

                        ]>						

    ODPOWIEDNIK=< LISTA=[ //Рама ленточная

                        ]>	
						
    ODPOWIEDNIK=< LISTA=[ //Рама 

                        ]>							
    ODPOWIEDNIK=< LISTA=[ //Рама 
						 
                        ]>	
    ODPOWIEDNIK=< LISTA=[ //Рама 

                        ]>		
    ODPOWIEDNIK=< LISTA=[ //Рама 
   
                        ]>								
//Рама/Створка дверная
    ODPOWIEDNIK=< LISTA=[ //Рама 
								 
                        ]>		
    ODPOWIEDNIK=< LISTA=[ //Рама 

                        ]>		
    ODPOWIEDNIK=< LISTA=[ //Рама 

                        ]>		
    ODPOWIEDNIK=< LISTA=[ //Рама 
  						 
                        ]>			
    ODPOWIEDNIK=< LISTA=[ //Рама 
    						 
                        ]>		
    ODPOWIEDNIK=< LISTA=[ //Рама 
    						 
                        ]>		
    ODPOWIEDNIK=< LISTA=[ //Импост
   						 
                        ]>							
//Порог
    ODPOWIEDNIK=< LISTA=[ 

                        ]>		
    ODPOWIEDNIK=< LISTA=[ 
   						 
                        ]>		
//skrzydіo R
    ODPOWIEDNIK=< LISTA=[
						 
                        ]>
    ODPOWIEDNIK=< LISTA=[
						 
                        ]>
    ODPOWIEDNIK=< LISTA=[
						 
                        ]>		
						
    ODPOWIEDNIK=< LISTA=[
						 
                        ]>
    ODPOWIEDNIK=< LISTA=[
					 
                        ]>
    ODPOWIEDNIK=< LISTA=[
						 
                        ]>		

    ODPOWIEDNIK=< LISTA=[
							 
                        ]>
    ODPOWIEDNIK=< LISTA=[
						 
                        ]>
    ODPOWIEDNIK=< LISTA=[
						 
                        ]>	

    ODPOWIEDNIK=< LISTA=[
						 
                        ]>
    ODPOWIEDNIK=< LISTA=[
						 
                        ]>
    ODPOWIEDNIK=< LISTA=[
						 
                        ]>							
//skrzydіo UR
    ODPOWIEDNIK=< LISTA=[
					 
                        ]>
    ODPOWIEDNIK=< LISTA=[
						 
                        ]>
    ODPOWIEDNIK=< LISTA=[
						 
                        ]>
    ODPOWIEDNIK=< LISTA=[
						 
                        ]>		

    ODPOWIEDNIK=< LISTA=[
						 
                        ]>
    ODPOWIEDNIK=< LISTA=[
						 
                        ]>		

    ODPOWIEDNIK=< LISTA=[
						 
                        ]>
    ODPOWIEDNIK=< LISTA=[
							 
                        ]>							
						
//skrzydіo U
    ODPOWIEDNIK=< LISTA=[
						 
                        ]>
    ODPOWIEDNIK=< LISTA=[
						 
                        ]>
//skrzydіo UP
    ODPOWIEDNIK=< LISTA=[
						 
                        ]>
    ODPOWIEDNIK=< LISTA=[
					 
                        ]>
    ODPOWIEDNIK=< LISTA=[
					 
                        ]>
    ODPOWIEDNIK=< LISTA=[
						 
                        ]>		
						
//Рама оконная
    ODPOWIEDNIK=< LISTA=[
					 
                        ]>
    ODPOWIEDNIK=< LISTA=[
					 
                        ]>			
//Рама дверная
    ODPOWIEDNIK=< LISTA=[
						 
                        ]>
    ODPOWIEDNIK=< LISTA=[
							 
                        ]>		
//Створка дверная
    ODPOWIEDNIK=< LISTA=[
					 
                        ]>
			
    ODPOWIEDNIK=< LISTA=[
						 
                        ]>		
    ODPOWIEDNIK=< LISTA=[
						 
                        ]>					
    ODPOWIEDNIK=< LISTA=[
						 
                        ]>		
						
    ODPOWIEDNIK=< LISTA=[
						 
                        ]>                     
    ODPOWIEDNIK=< LISTA=[                      
						 
                        ]>		               
    ODPOWIEDNIK=< LISTA=[                      
						 
                        ]>					   
    ODPOWIEDNIK=< LISTA=[                      
						 
                        ]>	

    ODPOWIEDNIK=< LISTA=[
					 
                        ]>
    ODPOWIEDNIK=< LISTA=[
					 
                        ]>		
    ODPOWIEDNIK=< LISTA=[
						 
                        ]>					
    ODPOWIEDNIK=< LISTA=[
						 
                        ]>		
						
    ODPOWIEDNIK=< LISTA=[
						 
                        ]>                     
    ODPOWIEDNIK=< LISTA=[                      
					 
                        ]>		               
    ODPOWIEDNIK=< LISTA=[                      
						 
                        ]>					   
    ODPOWIEDNIK=< LISTA=[                      
						 
                        ]>		

  //Typy skrzydeі (TS_*)
  ODPOWIEDNIK_TYPU_SKRZYDLA=< LISTA=[] >//_RamaDZ   
  ODPOWIEDNIK_TYPU_SKRZYDLA=< LISTA=[] >//_RamaDZ
  >
