GRUPY_ELEMENTOW=
  <
//*******************************************************************
//Опора
//*******************************************************************

    GRUPA[1001]=
      <
      NAZWA=     'Кронштейн рухомий F50.604.03 (h=60мм)'
      OPIS_HTML= 'Кронштейн рухомий F50.604.03. <b><font face="verdana" color="clred">Виліт кронштейна 130мм</font></b'
      ZESTAW=    'Кронштейни (рухомі)'
      RYSUNEK=   'KR_F50_604_03.png'

      RODZAJ=1 // 1- кронштейны, 0 - дополнительные элементы
	  CZY_RUCHOMA_PODPORA=TAK	  

      DLA_PROFILI=[
                   PRF_F50_SLP_F50_102  ,
                   PRF_F50_SLP_F50_103  ,
                   PRF_F50_SLP_F50_104  ,
                   PRF_F50_SLP_F50_105  ,
                   PRF_F50_SLP_F50_106  ,
                   PRF_F50_SLP_F50_107  ,	 
                   
                   PRF_F50_WSLP_F50_102 ,
                   PRF_F50_WSLP_F50_103 ,
                   PRF_F50_WSLP_F50_104 ,
                   PRF_F50_WSLP_F50_105 ,
                   PRF_F50_WSLP_F50_106 ,
                   PRF_F50_WSLP_F50_107 					   
                  ]
      SYSTEMY= [DEF_SYS_F50]

      ELEMENT[N]=< KOD=E_F50_604_03           ILOSC='1' STRONA=KOLOR_WEWN NR_PRZEKROJU=517	> 
      ELEMENT[N]=< KOD=E_F50_603_01           ILOSC='2' STRONA=KOLOR_WEWN NR_PRZEKROJU=517	>
      ELEMENT[N]=< KOD=E_F50_603_02           ILOSC='2' STRONA=KOLOR_WEWN NR_PRZEKROJU=517	>			   
      ELEMENT[N]=< KOD=E_ALP_F50_612_02       ILOSC='1' STRONA=KOLOR_WEWN NR_PRZEKROJU=517	>
      ELEMENT[N]=< KOD=E_Podkladka_M10_DIN125 ILOSC='2' STRONA=KOLOR_WEWN NR_PRZEKROJU=517	>
      ELEMENT[N]=< KOD=E_Nakretka_M10_DIN985  ILOSC='1' STRONA=KOLOR_WEWN NR_PRZEKROJU=517	>
      ELEMENT[N]=< KOD=E_M10x90_DIN931        ILOSC='1' STRONA=KOLOR_WEWN NR_PRZEKROJU=517	>			   
      >	
	  
    GRUPA[1002]=
      <
      NAZWA=     'Кронштейн рухомий F50.604.05 (h=90мм)'
      OPIS_HTML= 'Кронштейн рухомий F50.604.05. <b><font face="verdana" color="clred">Виліт кронштейна 130мм</font></b'
      ZESTAW=    'Кронштейни (рухомі)'
      RYSUNEK=   'KR_F50_604_05.png'
	  //WLASNY_RYSUNEK=TAK // собственный рисунок для кронштейна на чертеже

      RODZAJ=1 // 1- кронштейны, 0 - дополнительные элементы

      DLA_PROFILI=[
        PRF_F50_SLP_F50_102  ,
        PRF_F50_SLP_F50_103  ,
        PRF_F50_SLP_F50_104  ,
        PRF_F50_SLP_F50_105  ,
        PRF_F50_SLP_F50_106  ,
        PRF_F50_SLP_F50_107  ,	 
        
        PRF_F50_WSLP_F50_102 ,
        PRF_F50_WSLP_F50_103 ,
        PRF_F50_WSLP_F50_104 ,
        PRF_F50_WSLP_F50_105 ,
        PRF_F50_WSLP_F50_106 ,
        PRF_F50_WSLP_F50_107 								 
                  ]
     SYSTEMY= [DEF_SYS_F50]

      ELEMENT[N]=< KOD=E_F50_604_05           ILOSC='1' STRONA=KOLOR_WEWN NR_PRZEKROJU=517	> 
      ELEMENT[N]=< KOD=E_F50_603_01           ILOSC='2' STRONA=KOLOR_WEWN NR_PRZEKROJU=517	>
      ELEMENT[N]=< KOD=E_F50_603_02           ILOSC='2' STRONA=KOLOR_WEWN NR_PRZEKROJU=517	>			   
      ELEMENT[N]=< KOD=E_ALP_F50_612_02       ILOSC='1' STRONA=KOLOR_WEWN NR_PRZEKROJU=517	>
      ELEMENT[N]=< KOD=E_Podkladka_M10_DIN125 ILOSC='2' STRONA=KOLOR_WEWN NR_PRZEKROJU=517	>
      ELEMENT[N]=< KOD=E_Nakretka_M10_DIN985  ILOSC='1' STRONA=KOLOR_WEWN NR_PRZEKROJU=517	>
      ELEMENT[N]=< KOD=E_M10x90_DIN931        ILOSC='1' STRONA=KOLOR_WEWN NR_PRZEKROJU=517	>		
      >	 

    GRUPA[1003]=
      <
      NAZWA=     'Кронштейн нерухомий F50.604.06 (h=60мм)'
      OPIS_HTML= 'Кронштейн нерухомий F50.604.06. <b><font face="verdana" color="clred">Виліт кронштейна 130мм</font></b'
      ZESTAW=    'Кронштейни (нерухомі)'
      RYSUNEK=   'KR_F50_604_06.png'

      RODZAJ=1 // 1- кронштейны, 0 - дополнительные элементы
	  CZY_RUCHOMA_PODPORA=TAK	  

      DLA_PROFILI=[
        PRF_F50_SLP_F50_102  ,
        PRF_F50_SLP_F50_103  ,
        PRF_F50_SLP_F50_104  ,
        PRF_F50_SLP_F50_105  ,
        PRF_F50_SLP_F50_106  ,
        PRF_F50_SLP_F50_107  ,	 
        
        PRF_F50_WSLP_F50_102 ,
        PRF_F50_WSLP_F50_103 ,
        PRF_F50_WSLP_F50_104 ,
        PRF_F50_WSLP_F50_105 ,
        PRF_F50_WSLP_F50_106 ,
        PRF_F50_WSLP_F50_107 			
                  ]
     SYSTEMY= [DEF_SYS_F50]

      ELEMENT[N]=< KOD=E_F50_604_06           ILOSC='1' STRONA=KOLOR_WEWN NR_PRZEKROJU=517	> 
      ELEMENT[N]=< KOD=E_F50_603_01           ILOSC='2' STRONA=KOLOR_WEWN NR_PRZEKROJU=517	>
      ELEMENT[N]=< KOD=E_F50_603_01           ILOSC='2' STRONA=KOLOR_WEWN NR_PRZEKROJU=517	>			   
      ELEMENT[N]=< KOD=E_ALP_F50_612_01       ILOSC='1' STRONA=KOLOR_WEWN NR_PRZEKROJU=517	>
      ELEMENT[N]=< KOD=E_Podkladka_M10_DIN125 ILOSC='2' STRONA=KOLOR_WEWN NR_PRZEKROJU=517	>
      ELEMENT[N]=< KOD=E_Nakretka_M10_DIN985  ILOSC='1' STRONA=KOLOR_WEWN NR_PRZEKROJU=517	>
      ELEMENT[N]=< KOD=E_M10x90_DIN931        ILOSC='1' STRONA=KOLOR_WEWN NR_PRZEKROJU=517	>			 
      >	  	 
	  

    GRUPA[1004]=
      <
      NAZWA=     'Кронштейн нерухомий F50.604.07 (h=120мм)'
      OPIS_HTML= 'Кронштейн нерухомий F50.604.07. <b><font face="verdana" color="clred">Виліт кронштейна 130мм</font></b'
      ZESTAW=    'Кронштейни (нерухомі)'
      RYSUNEK=   'KR_F50_604_07.png'
	  //WLASNY_RYSUNEK=TAK // собственный рисунок для кронштейна на чертеже

      RODZAJ=1 // 1- кронштейны, 0 - дополнительные элементы
	  CZY_RUCHOMA_PODPORA=TAK	 

      DLA_PROFILI=[
        PRF_F50_SLP_F50_102  ,
        PRF_F50_SLP_F50_103  ,
        PRF_F50_SLP_F50_104  ,
        PRF_F50_SLP_F50_105  ,
        PRF_F50_SLP_F50_106  ,
        PRF_F50_SLP_F50_107  ,	 
        
        PRF_F50_WSLP_F50_102 ,
        PRF_F50_WSLP_F50_103 ,
        PRF_F50_WSLP_F50_104 ,
        PRF_F50_WSLP_F50_105 ,
        PRF_F50_WSLP_F50_106 ,
        PRF_F50_WSLP_F50_107 			
                  ]
     SYSTEMY= [DEF_SYS_F50]

      ELEMENT[N]=< KOD=E_F50_604_07           ILOSC='1' STRONA=KOLOR_WEWN NR_PRZEKROJU=517	> 
      ELEMENT[N]=< KOD=E_F50_603_01           ILOSC='6' STRONA=KOLOR_WEWN NR_PRZEKROJU=517	>
      ELEMENT[N]=< KOD=E_ALP_F50_612_01       ILOSC='2' STRONA=KOLOR_WEWN NR_PRZEKROJU=517	>
      ELEMENT[N]=< KOD=E_Podkladka_M10_DIN125 ILOSC='4' STRONA=KOLOR_WEWN NR_PRZEKROJU=517	>
      ELEMENT[N]=< KOD=E_Nakretka_M10_DIN985  ILOSC='2' STRONA=KOLOR_WEWN NR_PRZEKROJU=517	>
      ELEMENT[N]=< KOD=E_M10x90_DIN931        ILOSC='2' STRONA=KOLOR_WEWN NR_PRZEKROJU=517	>	
      >	  

	GRUPA[1005]=
      <
      NAZWA=     'Опора нижня F50.A0.. (авто)'
      OPIS=      'Опора нижня F50.A0.. (авто)'
      ZESTAW=    'Опора на алюмінієвій основі'
      RYSUNEK=   'OPORA_F50_BOTTOM.vct'
	  
      RODZAJ=1

      SYSTEMY= [DEF_SYS_F50]
	  
      PARAMETRY=
	    <				 		 
		>	  
	  
      DLA_PROFILI=[
                   PRF_F50_SLP_F50_102  ,
                   PRF_F50_SLP_F50_103  ,
                   PRF_F50_SLP_F50_104  ,
                   PRF_F50_SLP_F50_105  ,
                   PRF_F50_SLP_F50_106  ,
                   PRF_F50_SLP_F50_107  ,	 
                   
                   PRF_F50_WSLP_F50_102 ,
                   PRF_F50_WSLP_F50_103 ,
                   PRF_F50_WSLP_F50_104 ,
                   PRF_F50_WSLP_F50_105 ,
                   PRF_F50_WSLP_F50_106 ,
                   PRF_F50_WSLP_F50_107 				   
			      ]
	//Авто подбор 	
	  //****************  	
      ELEMENT[N]=< KOD=E_F50_A011           ILOSC='1'    STRONA=KOLOR_WEWN   DLA_PROFILI=[PRF_F50_SLP_F50_102, PRF_F50_WSLP_F50_102]  NR_PRZEKROJU=517> 	
	  //****************                           
      ELEMENT[N]=< KOD=E_F50_A013           ILOSC='1'    STRONA=KOLOR_WEWN   DLA_PROFILI=[PRF_F50_SLP_F50_103, PRF_F50_WSLP_F50_103]  NR_PRZEKROJU=517> 	
	  //****************                           
      ELEMENT[N]=< KOD=E_F50_A015           ILOSC='1'    STRONA=KOLOR_WEWN   DLA_PROFILI=[PRF_F50_SLP_F50_104, PRF_F50_WSLP_F50_104]  NR_PRZEKROJU=517> 	
	  //****************                           
      ELEMENT[N]=< KOD=E_F50_A017           ILOSC='1'    STRONA=KOLOR_WEWN   DLA_PROFILI=[PRF_F50_SLP_F50_105, PRF_F50_WSLP_F50_105]  NR_PRZEKROJU=517> 	
	  //****************                           
      ELEMENT[N]=< KOD=E_F50_A019           ILOSC='1'    STRONA=KOLOR_WEWN   DLA_PROFILI=[PRF_F50_SLP_F50_106, PRF_F50_WSLP_F50_106]  NR_PRZEKROJU=517> 
	  //****************
      ELEMENT[N]=< KOD=E_F50_A021           ILOSC='1'    STRONA=KOLOR_WEWN   DLA_PROFILI=[PRF_F50_SLP_F50_107, PRF_F50_WSLP_F50_107]  NR_PRZEKROJU=517> 
	  //****************
	  
      ELEMENT[N]=< KOD=E_ALP_F50_612_03       ILOSC='1'  STRONA=KOLOR_WEWN   DLA_PROFILI=[PRF_F50_SLP_F50_102, PRF_F50_SLP_F50_103, PRF_F50_SLP_F50_104, PRF_F50_WSLP_F50_102, PRF_F50_WSLP_F50_103, PRF_F50_WSLP_F50_104]  NR_PRZEKROJU=517> 
      ELEMENT[N]=< KOD=E_Podkladka_M10_DIN125 ILOSC='2'  STRONA=KOLOR_WEWN   DLA_PROFILI=[PRF_F50_SLP_F50_102, PRF_F50_SLP_F50_103, PRF_F50_SLP_F50_104, PRF_F50_WSLP_F50_102, PRF_F50_WSLP_F50_103, PRF_F50_WSLP_F50_104]  NR_PRZEKROJU=517	>
      ELEMENT[N]=< KOD=E_Nakretka_M10_DIN934  ILOSC='1'  STRONA=KOLOR_WEWN   DLA_PROFILI=[PRF_F50_SLP_F50_102, PRF_F50_SLP_F50_103, PRF_F50_SLP_F50_104, PRF_F50_WSLP_F50_102, PRF_F50_WSLP_F50_103, PRF_F50_WSLP_F50_104]  NR_PRZEKROJU=517	>
      ELEMENT[N]=< KOD=E_Podkladka_M10_DIN127 ILOSC='1'  STRONA=KOLOR_WEWN   DLA_PROFILI=[PRF_F50_SLP_F50_102, PRF_F50_SLP_F50_103, PRF_F50_SLP_F50_104, PRF_F50_WSLP_F50_102, PRF_F50_WSLP_F50_103, PRF_F50_WSLP_F50_104]  NR_PRZEKROJU=517	>
      ELEMENT[N]=< KOD=E_M10x70_DIN931        ILOSC='1'  STRONA=KOLOR_WEWN   DLA_PROFILI=[PRF_F50_SLP_F50_102, PRF_F50_SLP_F50_103, PRF_F50_SLP_F50_104, PRF_F50_WSLP_F50_102, PRF_F50_WSLP_F50_103, PRF_F50_WSLP_F50_104]  NR_PRZEKROJU=517	>		  
	  
      ELEMENT[N]=< KOD=E_ALP_F50_612_03       ILOSC='2'  STRONA=KOLOR_WEWN   DLA_PROFILI=[PRF_F50_SLP_F50_105, PRF_F50_WSLP_F50_105, PRF_F50_SLP_F50_106, PRF_F50_WSLP_F50_106, PRF_F50_SLP_F50_107, PRF_F50_WSLP_F50_107]  NR_PRZEKROJU=517> 
      ELEMENT[N]=< KOD=E_Podkladka_M10_DIN125 ILOSC='4'  STRONA=KOLOR_WEWN   DLA_PROFILI=[PRF_F50_SLP_F50_105, PRF_F50_WSLP_F50_105, PRF_F50_SLP_F50_106, PRF_F50_WSLP_F50_106, PRF_F50_SLP_F50_107, PRF_F50_WSLP_F50_107]  NR_PRZEKROJU=517	>
      ELEMENT[N]=< KOD=E_Nakretka_M10_DIN934  ILOSC='2'  STRONA=KOLOR_WEWN   DLA_PROFILI=[PRF_F50_SLP_F50_105, PRF_F50_WSLP_F50_105, PRF_F50_SLP_F50_106, PRF_F50_WSLP_F50_106, PRF_F50_SLP_F50_107, PRF_F50_WSLP_F50_107]  NR_PRZEKROJU=517	>
      ELEMENT[N]=< KOD=E_Podkladka_M10_DIN127 ILOSC='2'  STRONA=KOLOR_WEWN   DLA_PROFILI=[PRF_F50_SLP_F50_105, PRF_F50_WSLP_F50_105, PRF_F50_SLP_F50_106, PRF_F50_WSLP_F50_106, PRF_F50_SLP_F50_107, PRF_F50_WSLP_F50_107]  NR_PRZEKROJU=517	>
      ELEMENT[N]=< KOD=E_M10x70_DIN931        ILOSC='2'  STRONA=KOLOR_WEWN   DLA_PROFILI=[PRF_F50_SLP_F50_105, PRF_F50_WSLP_F50_105, PRF_F50_SLP_F50_106, PRF_F50_WSLP_F50_106, PRF_F50_SLP_F50_107, PRF_F50_WSLP_F50_107]  NR_PRZEKROJU=517	>		  
	  >			
	  
	  

	GRUPA[1006]=
      <
      NAZWA=     'Опора верхня F50.A0.. (авто)'
      OPIS=      'Опора верхня F50.A0.. (авто)'
      ZESTAW=    'Опора на алюмінієвій основі'
      RYSUNEK=   'OPORA_F50_TOP.vct'
	  
      RODZAJ=1

      SYSTEMY= [DEF_SYS_F50]
	  
      PARAMETRY=
	    <				 		 
		>	  
	  
      DLA_PROFILI=[
                   PRF_F50_SLP_F50_102  ,
                   PRF_F50_SLP_F50_103  ,
                   PRF_F50_SLP_F50_104  ,
                   PRF_F50_SLP_F50_105  ,
                   PRF_F50_SLP_F50_106  ,
                   PRF_F50_SLP_F50_107  ,	 
                   
                   PRF_F50_WSLP_F50_102 ,
                   PRF_F50_WSLP_F50_103 ,
                   PRF_F50_WSLP_F50_104 ,
                   PRF_F50_WSLP_F50_105 ,
                   PRF_F50_WSLP_F50_106 ,
                   PRF_F50_WSLP_F50_107 				   
			      ]
	//Авто подбор 	
	  //****************  	
      ELEMENT[N]=< KOD=E_F50_A012           ILOSC='1'    STRONA=KOLOR_WEWN                                   DLA_PROFILI=[PRF_F50_SLP_F50_102, PRF_F50_WSLP_F50_102]  NR_PRZEKROJU=517> 	
	  //****************                           
      ELEMENT[N]=< KOD=E_F50_A014           ILOSC='1'    STRONA=KOLOR_WEWN                                   DLA_PROFILI=[PRF_F50_SLP_F50_103, PRF_F50_WSLP_F50_103]  NR_PRZEKROJU=517> 	
	  //****************                           
      ELEMENT[N]=< KOD=E_F50_A016           ILOSC='1'    STRONA=KOLOR_WEWN                                   DLA_PROFILI=[PRF_F50_SLP_F50_104, PRF_F50_WSLP_F50_104]  NR_PRZEKROJU=517> 	
	  //****************                           
      ELEMENT[N]=< KOD=E_F50_A018           ILOSC='1'    STRONA=KOLOR_WEWN                                   DLA_PROFILI=[PRF_F50_SLP_F50_105, PRF_F50_WSLP_F50_105]  NR_PRZEKROJU=517> 	
	  //****************                           
      ELEMENT[N]=< KOD=E_F50_A020           ILOSC='1'    STRONA=KOLOR_WEWN                                   DLA_PROFILI=[PRF_F50_SLP_F50_106, PRF_F50_WSLP_F50_106]  NR_PRZEKROJU=517> 
	  //****************                           
      ELEMENT[N]=< KOD=E_F50_A022           ILOSC='1'    STRONA=KOLOR_WEWN                                   DLA_PROFILI=[PRF_F50_SLP_F50_107, PRF_F50_WSLP_F50_107]  NR_PRZEKROJU=517> 
	  	  	  
	  //****************

      ELEMENT[N]=< KOD=E_ALP_F50_612_03       ILOSC='1'  STRONA=KOLOR_WEWN   DLA_PROFILI=[PRF_F50_SLP_F50_102, PRF_F50_SLP_F50_103, PRF_F50_SLP_F50_104, PRF_F50_WSLP_F50_102, PRF_F50_WSLP_F50_103, PRF_F50_WSLP_F50_104]  NR_PRZEKROJU=517> 
      ELEMENT[N]=< KOD=E_Podkladka_M10_DIN125 ILOSC='2'  STRONA=KOLOR_WEWN   DLA_PROFILI=[PRF_F50_SLP_F50_102, PRF_F50_SLP_F50_103, PRF_F50_SLP_F50_104, PRF_F50_WSLP_F50_102, PRF_F50_WSLP_F50_103, PRF_F50_WSLP_F50_104]  NR_PRZEKROJU=517	>
      ELEMENT[N]=< KOD=E_Nakretka_M10_DIN934  ILOSC='1'  STRONA=KOLOR_WEWN   DLA_PROFILI=[PRF_F50_SLP_F50_102, PRF_F50_SLP_F50_103, PRF_F50_SLP_F50_104, PRF_F50_WSLP_F50_102, PRF_F50_WSLP_F50_103, PRF_F50_WSLP_F50_104]  NR_PRZEKROJU=517	>
      ELEMENT[N]=< KOD=E_Podkladka_M10_DIN127 ILOSC='1'  STRONA=KOLOR_WEWN   DLA_PROFILI=[PRF_F50_SLP_F50_102, PRF_F50_SLP_F50_103, PRF_F50_SLP_F50_104, PRF_F50_WSLP_F50_102, PRF_F50_WSLP_F50_103, PRF_F50_WSLP_F50_104]  NR_PRZEKROJU=517	>
      ELEMENT[N]=< KOD=E_M10x70_DIN931        ILOSC='1'  STRONA=KOLOR_WEWN   DLA_PROFILI=[PRF_F50_SLP_F50_102, PRF_F50_SLP_F50_103, PRF_F50_SLP_F50_104, PRF_F50_WSLP_F50_102, PRF_F50_WSLP_F50_103, PRF_F50_WSLP_F50_104]  NR_PRZEKROJU=517	>		  
	  
      ELEMENT[N]=< KOD=E_ALP_F50_612_03       ILOSC='2'  STRONA=KOLOR_WEWN   DLA_PROFILI=[PRF_F50_SLP_F50_105, PRF_F50_WSLP_F50_105, PRF_F50_SLP_F50_106, PRF_F50_WSLP_F50_106, PRF_F50_SLP_F50_107, PRF_F50_WSLP_F50_107]  NR_PRZEKROJU=517> 
      ELEMENT[N]=< KOD=E_Podkladka_M10_DIN125 ILOSC='4'  STRONA=KOLOR_WEWN   DLA_PROFILI=[PRF_F50_SLP_F50_105, PRF_F50_WSLP_F50_105, PRF_F50_SLP_F50_106, PRF_F50_WSLP_F50_106, PRF_F50_SLP_F50_107, PRF_F50_WSLP_F50_107]  NR_PRZEKROJU=517	>
      ELEMENT[N]=< KOD=E_Nakretka_M10_DIN934  ILOSC='2'  STRONA=KOLOR_WEWN   DLA_PROFILI=[PRF_F50_SLP_F50_105, PRF_F50_WSLP_F50_105, PRF_F50_SLP_F50_106, PRF_F50_WSLP_F50_106, PRF_F50_SLP_F50_107, PRF_F50_WSLP_F50_107]  NR_PRZEKROJU=517	>
      ELEMENT[N]=< KOD=E_Podkladka_M10_DIN127 ILOSC='2'  STRONA=KOLOR_WEWN   DLA_PROFILI=[PRF_F50_SLP_F50_105, PRF_F50_WSLP_F50_105, PRF_F50_SLP_F50_106, PRF_F50_WSLP_F50_106, PRF_F50_SLP_F50_107, PRF_F50_WSLP_F50_107]  NR_PRZEKROJU=517	>
      ELEMENT[N]=< KOD=E_M10x70_DIN931        ILOSC='2'  STRONA=KOLOR_WEWN   DLA_PROFILI=[PRF_F50_SLP_F50_105, PRF_F50_WSLP_F50_105, PRF_F50_SLP_F50_106, PRF_F50_WSLP_F50_106, PRF_F50_SLP_F50_107, PRF_F50_WSLP_F50_107]  NR_PRZEKROJU=517	>		  
	  >		


	GRUPA[1007]=
      <
      NAZWA=     'Опора нижня F50.A0.. (авто)'
      OPIS=      'Опора нижня F50.A0.. (авто)'
      ZESTAW=    'Опора на стальній основі'
      RYSUNEK=   'OPORA_F50_BOTTOM.vct'
	  
      RODZAJ=1

      SYSTEMY= [DEF_SYS_F50]
	  
      PARAMETRY=
	    <				 		 
		>	  
	  
      DLA_PROFILI=[
                   PRF_F50_SLP_F50_102  ,
                   PRF_F50_SLP_F50_103  ,
                   PRF_F50_SLP_F50_104  ,
                   PRF_F50_SLP_F50_105  ,
                   PRF_F50_SLP_F50_106  ,
                   PRF_F50_SLP_F50_107  ,	 
                   
                   PRF_F50_WSLP_F50_102 ,
                   PRF_F50_WSLP_F50_103 ,
                   PRF_F50_WSLP_F50_104 ,
                   PRF_F50_WSLP_F50_105 ,
                   PRF_F50_WSLP_F50_106 ,
                   PRF_F50_WSLP_F50_107 				   
			      ]
	//Авто подбор 	
	  //****************  	
      ELEMENT[N]=< KOD=E_F50_A001           ILOSC='1'    STRONA=KOLOR_WEWN                                   DLA_PROFILI=[PRF_F50_SLP_F50_102, PRF_F50_WSLP_F50_102]  NR_PRZEKROJU=517> 	
	  //****************                           
      ELEMENT[N]=< KOD=E_F50_A003           ILOSC='1'    STRONA=KOLOR_WEWN                                   DLA_PROFILI=[PRF_F50_SLP_F50_103, PRF_F50_WSLP_F50_103]  NR_PRZEKROJU=517> 	
	  //****************                           
      ELEMENT[N]=< KOD=E_F50_A005           ILOSC='1'    STRONA=KOLOR_WEWN                                   DLA_PROFILI=[PRF_F50_SLP_F50_104, PRF_F50_WSLP_F50_104]  NR_PRZEKROJU=517> 	
	  //****************                           
      ELEMENT[N]=< KOD=E_F50_A007           ILOSC='1'    STRONA=KOLOR_WEWN                                   DLA_PROFILI=[PRF_F50_SLP_F50_105, PRF_F50_WSLP_F50_105]  NR_PRZEKROJU=517> 	
	  //****************                           
      ELEMENT[N]=< KOD=E_F50_A009           ILOSC='1'    STRONA=KOLOR_WEWN                                   DLA_PROFILI=[PRF_F50_SLP_F50_106, PRF_F50_WSLP_F50_106]  NR_PRZEKROJU=517> 
	  //****************
      ELEMENT[N]=< KOD=E_F50_A023           ILOSC='1'    STRONA=KOLOR_WEWN                                   DLA_PROFILI=[PRF_F50_SLP_F50_107, PRF_F50_WSLP_F50_107]  NR_PRZEKROJU=517> 
	  //****************

      ELEMENT[N]=< KOD=E_ALP_F50_612_03       ILOSC='1'  STRONA=KOLOR_WEWN   DLA_PROFILI=[PRF_F50_SLP_F50_102, PRF_F50_SLP_F50_103, PRF_F50_SLP_F50_104, PRF_F50_WSLP_F50_102, PRF_F50_WSLP_F50_103, PRF_F50_WSLP_F50_104]  NR_PRZEKROJU=517> 
      ELEMENT[N]=< KOD=E_Podkladka_M10_DIN125 ILOSC='2'  STRONA=KOLOR_WEWN   DLA_PROFILI=[PRF_F50_SLP_F50_102, PRF_F50_SLP_F50_103, PRF_F50_SLP_F50_104, PRF_F50_WSLP_F50_102, PRF_F50_WSLP_F50_103, PRF_F50_WSLP_F50_104]  NR_PRZEKROJU=517	>
      ELEMENT[N]=< KOD=E_Nakretka_M10_DIN934  ILOSC='1'  STRONA=KOLOR_WEWN   DLA_PROFILI=[PRF_F50_SLP_F50_102, PRF_F50_SLP_F50_103, PRF_F50_SLP_F50_104, PRF_F50_WSLP_F50_102, PRF_F50_WSLP_F50_103, PRF_F50_WSLP_F50_104]  NR_PRZEKROJU=517	>
      ELEMENT[N]=< KOD=E_Podkladka_M10_DIN127 ILOSC='1'  STRONA=KOLOR_WEWN   DLA_PROFILI=[PRF_F50_SLP_F50_102, PRF_F50_SLP_F50_103, PRF_F50_SLP_F50_104, PRF_F50_WSLP_F50_102, PRF_F50_WSLP_F50_103, PRF_F50_WSLP_F50_104]  NR_PRZEKROJU=517	>
      ELEMENT[N]=< KOD=E_M10x70_DIN931        ILOSC='1'  STRONA=KOLOR_WEWN   DLA_PROFILI=[PRF_F50_SLP_F50_102, PRF_F50_SLP_F50_103, PRF_F50_SLP_F50_104, PRF_F50_WSLP_F50_102, PRF_F50_WSLP_F50_103, PRF_F50_WSLP_F50_104]  NR_PRZEKROJU=517	>		  
	  
      ELEMENT[N]=< KOD=E_ALP_F50_612_03       ILOSC='2'  STRONA=KOLOR_WEWN   DLA_PROFILI=[PRF_F50_SLP_F50_105, PRF_F50_WSLP_F50_105, PRF_F50_SLP_F50_106, PRF_F50_WSLP_F50_106, PRF_F50_SLP_F50_107, PRF_F50_WSLP_F50_107]  NR_PRZEKROJU=517> 
      ELEMENT[N]=< KOD=E_Podkladka_M10_DIN125 ILOSC='4'  STRONA=KOLOR_WEWN   DLA_PROFILI=[PRF_F50_SLP_F50_105, PRF_F50_WSLP_F50_105, PRF_F50_SLP_F50_106, PRF_F50_WSLP_F50_106, PRF_F50_SLP_F50_107, PRF_F50_WSLP_F50_107]  NR_PRZEKROJU=517	>
      ELEMENT[N]=< KOD=E_Nakretka_M10_DIN934  ILOSC='2'  STRONA=KOLOR_WEWN   DLA_PROFILI=[PRF_F50_SLP_F50_105, PRF_F50_WSLP_F50_105, PRF_F50_SLP_F50_106, PRF_F50_WSLP_F50_106, PRF_F50_SLP_F50_107, PRF_F50_WSLP_F50_107]  NR_PRZEKROJU=517	>
      ELEMENT[N]=< KOD=E_Podkladka_M10_DIN127 ILOSC='2'  STRONA=KOLOR_WEWN   DLA_PROFILI=[PRF_F50_SLP_F50_105, PRF_F50_WSLP_F50_105, PRF_F50_SLP_F50_106, PRF_F50_WSLP_F50_106, PRF_F50_SLP_F50_107, PRF_F50_WSLP_F50_107]  NR_PRZEKROJU=517	>
      ELEMENT[N]=< KOD=E_M10x70_DIN931        ILOSC='2'  STRONA=KOLOR_WEWN   DLA_PROFILI=[PRF_F50_SLP_F50_105, PRF_F50_WSLP_F50_105, PRF_F50_SLP_F50_106, PRF_F50_WSLP_F50_106, PRF_F50_SLP_F50_107, PRF_F50_WSLP_F50_107]  NR_PRZEKROJU=517	>		  
	  >		
	  

	GRUPA[1008]=
      <
      NAZWA=     'Опора верхня F50.A0.. (авто)'
      OPIS=      'Опора верхня F50.A0.. (авто)'
      ZESTAW=    'Опора на стальній основі'
      RYSUNEK=   'OPORA_F50_TOP.vct'
	  
      RODZAJ=1

      SYSTEMY= [DEF_SYS_F50]
	  
      PARAMETRY=
	    <				 		 
		>	  
	  
      DLA_PROFILI=[
                   PRF_F50_SLP_F50_102  ,
                   PRF_F50_SLP_F50_103  ,
                   PRF_F50_SLP_F50_104  ,
                   PRF_F50_SLP_F50_105  ,
                   PRF_F50_SLP_F50_106  ,
                   PRF_F50_SLP_F50_107  ,	 
                   
                   PRF_F50_WSLP_F50_102 ,
                   PRF_F50_WSLP_F50_103 ,
                   PRF_F50_WSLP_F50_104 ,
                   PRF_F50_WSLP_F50_105 ,
                   PRF_F50_WSLP_F50_106 ,
                   PRF_F50_WSLP_F50_107 				   
			      ]
	//Авто подбор 	
	  //****************  	
      ELEMENT[N]=< KOD=E_F50_A002           ILOSC='1'    STRONA=KOLOR_WEWN                                   DLA_PROFILI=[PRF_F50_SLP_F50_102, PRF_F50_WSLP_F50_102]  NR_PRZEKROJU=517> 	
	  //****************                           
      ELEMENT[N]=< KOD=E_F50_A004           ILOSC='1'    STRONA=KOLOR_WEWN                                   DLA_PROFILI=[PRF_F50_SLP_F50_103, PRF_F50_WSLP_F50_103]  NR_PRZEKROJU=517> 	
	  //****************                           
      ELEMENT[N]=< KOD=E_F50_A006           ILOSC='1'    STRONA=KOLOR_WEWN                                   DLA_PROFILI=[PRF_F50_SLP_F50_104, PRF_F50_WSLP_F50_104]  NR_PRZEKROJU=517> 	
	  //****************                           
      ELEMENT[N]=< KOD=E_F50_A008           ILOSC='1'    STRONA=KOLOR_WEWN                                   DLA_PROFILI=[PRF_F50_SLP_F50_105, PRF_F50_WSLP_F50_105]  NR_PRZEKROJU=517> 	
	  //****************                           
      ELEMENT[N]=< KOD=E_F50_A010           ILOSC='1'    STRONA=KOLOR_WEWN                                   DLA_PROFILI=[PRF_F50_SLP_F50_106, PRF_F50_WSLP_F50_106]  NR_PRZEKROJU=517> 
	  //****************
      ELEMENT[N]=< KOD=E_F50_A024           ILOSC='1'    STRONA=KOLOR_WEWN                                   DLA_PROFILI=[PRF_F50_SLP_F50_107, PRF_F50_WSLP_F50_107]  NR_PRZEKROJU=517> 
	  //****************

      ELEMENT[N]=< KOD=E_ALP_F50_612_03       ILOSC='1'  STRONA=KOLOR_WEWN   DLA_PROFILI=[PRF_F50_SLP_F50_102, PRF_F50_SLP_F50_103, PRF_F50_SLP_F50_104, PRF_F50_WSLP_F50_102, PRF_F50_WSLP_F50_103, PRF_F50_WSLP_F50_104]  NR_PRZEKROJU=517> 
      ELEMENT[N]=< KOD=E_Podkladka_M10_DIN125 ILOSC='2'  STRONA=KOLOR_WEWN   DLA_PROFILI=[PRF_F50_SLP_F50_102, PRF_F50_SLP_F50_103, PRF_F50_SLP_F50_104, PRF_F50_WSLP_F50_102, PRF_F50_WSLP_F50_103, PRF_F50_WSLP_F50_104]  NR_PRZEKROJU=517	>
      ELEMENT[N]=< KOD=E_Nakretka_M10_DIN934  ILOSC='1'  STRONA=KOLOR_WEWN   DLA_PROFILI=[PRF_F50_SLP_F50_102, PRF_F50_SLP_F50_103, PRF_F50_SLP_F50_104, PRF_F50_WSLP_F50_102, PRF_F50_WSLP_F50_103, PRF_F50_WSLP_F50_104]  NR_PRZEKROJU=517	>
      ELEMENT[N]=< KOD=E_Podkladka_M10_DIN127 ILOSC='1'  STRONA=KOLOR_WEWN   DLA_PROFILI=[PRF_F50_SLP_F50_102, PRF_F50_SLP_F50_103, PRF_F50_SLP_F50_104, PRF_F50_WSLP_F50_102, PRF_F50_WSLP_F50_103, PRF_F50_WSLP_F50_104]  NR_PRZEKROJU=517	>
      ELEMENT[N]=< KOD=E_M10x70_DIN931        ILOSC='1'  STRONA=KOLOR_WEWN   DLA_PROFILI=[PRF_F50_SLP_F50_102, PRF_F50_SLP_F50_103, PRF_F50_SLP_F50_104, PRF_F50_WSLP_F50_102, PRF_F50_WSLP_F50_103, PRF_F50_WSLP_F50_104]  NR_PRZEKROJU=517	>		  
	  
      ELEMENT[N]=< KOD=E_ALP_F50_612_03       ILOSC='2'  STRONA=KOLOR_WEWN   DLA_PROFILI=[PRF_F50_SLP_F50_105, PRF_F50_WSLP_F50_105, PRF_F50_SLP_F50_106, PRF_F50_WSLP_F50_106, PRF_F50_SLP_F50_107, PRF_F50_WSLP_F50_107]  NR_PRZEKROJU=517> 
      ELEMENT[N]=< KOD=E_Podkladka_M10_DIN125 ILOSC='4'  STRONA=KOLOR_WEWN   DLA_PROFILI=[PRF_F50_SLP_F50_105, PRF_F50_WSLP_F50_105, PRF_F50_SLP_F50_106, PRF_F50_WSLP_F50_106, PRF_F50_SLP_F50_107, PRF_F50_WSLP_F50_107]  NR_PRZEKROJU=517	>
      ELEMENT[N]=< KOD=E_Nakretka_M10_DIN934  ILOSC='2'  STRONA=KOLOR_WEWN   DLA_PROFILI=[PRF_F50_SLP_F50_105, PRF_F50_WSLP_F50_105, PRF_F50_SLP_F50_106, PRF_F50_WSLP_F50_106, PRF_F50_SLP_F50_107, PRF_F50_WSLP_F50_107]  NR_PRZEKROJU=517	>
      ELEMENT[N]=< KOD=E_Podkladka_M10_DIN127 ILOSC='2'  STRONA=KOLOR_WEWN   DLA_PROFILI=[PRF_F50_SLP_F50_105, PRF_F50_WSLP_F50_105, PRF_F50_SLP_F50_106, PRF_F50_WSLP_F50_106, PRF_F50_SLP_F50_107, PRF_F50_WSLP_F50_107]  NR_PRZEKROJU=517	>
      ELEMENT[N]=< KOD=E_M10x70_DIN931        ILOSC='2'  STRONA=KOLOR_WEWN   DLA_PROFILI=[PRF_F50_SLP_F50_105, PRF_F50_WSLP_F50_105, PRF_F50_SLP_F50_106, PRF_F50_WSLP_F50_106, PRF_F50_SLP_F50_107, PRF_F50_WSLP_F50_107]  NR_PRZEKROJU=517	>		  
	  >			
	  
//***********************************************************************
//Вент фасад
//***********************************************************************
	  
    GRUPA[1101]=
      <
      NAZWA=     'Кронштейн ПАС-3602.01 100х45х60 / БП 0,06м [НВФ]'
      OPIS=      'Кронштейн ПАС-3602.01 100х45х60 / БП 0,06м [НВФ]'
      ZESTAW=    '{ 1. Кронштейн оновленний <b>60mm</b> <FONT COLOR="#0000FF"><FONT-SIZE="2"><b><big>(Рухомий)</b><FONT-SIZE="1">}'

      RODZAJ=1
	  
      PARAMETRY=
	    <
        Z_LISTY=
            < KLUCZ='NVF_PODOVGUVACH' 
			  PYTANIE='Використовувати подовжувача до кронштейна:' 
              ELEMENT     = 'Без подовжувача'   
              ELEMENT     = 'З використаням подовжувача 100х60 (ПАС-3835.01)'   			  
              STANDARDOWO = '0'			  
		  >	  	  
		>		 
	  
	  SYSTEMY= [DEF_SYS_NVF_KERAM_KLIAM, DEF_SYS_NVF_KERAM_GLUE,DEF_SYS_NVF_AKP,DEF_SYS_NVF_HPL_PANEL,DEF_SYS_NVF_FZP]
      RYSUNEK= 'PAS_3602_01_KR.png'
      WLASNY_RYSUNEK=TAK 
					ROZMIAR_X='100'
					ROZMIAR_Y='100'	
                    RYSUNEK=   'fix_podv1.vct'					
	  			    POLOZENIE_X='0'
					POLOZENIE_Y='0'
					WYMIARY_GRUPY
                    AKTYWNY=TAK 		  

      ELEMENT[N]=< KOD=E_ALP_NVF_PAS_3602_01        NR_PRZEKROJU=517 ILOSC='1'                 STRONA=KOLOR_WEWN  >
      ELEMENT[N]=< KOD=E_ALP_NVF_PAS_3835_01        NR_PRZEKROJU=517 ILOSC='1*NVF_PODOVGUVACH' STRONA=KOLOR_WEWN  >
      ELEMENT[N]=< KOD=E_ALP_NVF_Zakl_5_10_DIN7337  NR_PRZEKROJU=517 ILOSC='2'                 STRONA=KOLOR_WEWN  >
      ELEMENT[N]=< KOD=E_ALP_NVF_Zakl_5_10_DIN7337  NR_PRZEKROJU=517 ILOSC='2*NVF_PODOVGUVACH' STRONA=KOLOR_WEWN  >
	  
      ELEMENT[N]=< KOD=E_ALP_NVF_TERMO_70_50_5      NR_PRZEKROJU=517 ILOSC='1'                 STRONA=KOLOR_WEWN  >  
	  >	  
	  
    GRUPA[1102]=
      <
      NAZWA=     'Кронштейн ПАС-3603.01 130х45х60 / БП 0,06м [НВФ]'
      OPIS=      'Кронштейн ПАС-3603.01 130х45х60 / БП 0,06м [НВФ]'
      ZESTAW=    '{ 1. Кронштейн оновленний <b>60mm</b> <FONT COLOR="#0000FF"><FONT-SIZE="2"><b><big>(Рухомий)</b><FONT-SIZE="1">}'

      RODZAJ=1
	  
      PARAMETRY=
	    <
        Z_LISTY=
            < KLUCZ='NVF_PODOVGUVACH' 
			  PYTANIE='Використовувати подовжувача до кронштейна:' 
              ELEMENT     = 'Без подовжувача'   
              ELEMENT     = 'З використаням подовжувача 100х60 (ПАС-3835.01)'   			  
              STANDARDOWO = '0'			  
		  >	  	  
		>		 
	  
	  SYSTEMY= [DEF_SYS_NVF_KERAM_KLIAM, DEF_SYS_NVF_KERAM_GLUE,DEF_SYS_NVF_AKP,DEF_SYS_NVF_HPL_PANEL,DEF_SYS_NVF_FZP]
      RYSUNEK= 'PAS_3602_01_KR.png'
      WLASNY_RYSUNEK=TAK 
					ROZMIAR_X='100'
					ROZMIAR_Y='100'	
                    RYSUNEK=   'fix_podv1.vct'					
	  			    POLOZENIE_X='0'
					POLOZENIE_Y='0'
					WYMIARY_GRUPY
                    AKTYWNY=TAK 		

      ELEMENT[N]=< KOD=E_ALP_NVF_PAS_3603_01        NR_PRZEKROJU=517 ILOSC='1'                 STRONA=KOLOR_WEWN  >
      ELEMENT[N]=< KOD=E_ALP_NVF_PAS_3835_01        NR_PRZEKROJU=517 ILOSC='1*NVF_PODOVGUVACH' STRONA=KOLOR_WEWN  >
      ELEMENT[N]=< KOD=E_ALP_NVF_Zakl_5_10_DIN7337  NR_PRZEKROJU=517 ILOSC='2'                 STRONA=KOLOR_WEWN  >
      ELEMENT[N]=< KOD=E_ALP_NVF_Zakl_5_10_DIN7337  NR_PRZEKROJU=517 ILOSC='2*NVF_PODOVGUVACH' STRONA=KOLOR_WEWN  >
	  
      ELEMENT[N]=< KOD=E_ALP_NVF_TERMO_70_50_5      NR_PRZEKROJU=517 ILOSC='1'                 STRONA=KOLOR_WEWN  >  
	  >	   
	  
    GRUPA[1103]=
      <
      NAZWA=     'Кронштейн ПАС-3604.01 150х45х60 / БП 0,06м [НВФ]'
      OPIS=      'Кронштейн ПАС-3604.01 150х45х60 / БП 0,06м [НВФ]'
      ZESTAW=    '{ 1. Кронштейн оновленний <b>60mm</b> <FONT COLOR="#0000FF"><FONT-SIZE="2"><b><big>(Рухомий)</b><FONT-SIZE="1">}'

      RODZAJ=1
	  
      PARAMETRY=
	    <
        Z_LISTY=
            < KLUCZ='NVF_PODOVGUVACH' 
			  PYTANIE='Використовувати подовжувача до кронштейна:' 
              ELEMENT     = 'Без подовжувача'   
              ELEMENT     = 'З використаням подовжувача 100х60 (ПАС-3835.01)'   			  
              STANDARDOWO = '0'			  
		  >	  	  
		>		 
	  
	  SYSTEMY= [DEF_SYS_NVF_KERAM_KLIAM, DEF_SYS_NVF_KERAM_GLUE,DEF_SYS_NVF_AKP,DEF_SYS_NVF_HPL_PANEL,DEF_SYS_NVF_FZP]
      RYSUNEK= 'PAS_3602_01_KR.png'
      WLASNY_RYSUNEK=TAK 
					ROZMIAR_X='100'
					ROZMIAR_Y='100'	
                    RYSUNEK=   'fix_podv1.vct'					
	  			    POLOZENIE_X='0'
					POLOZENIE_Y='0'
					WYMIARY_GRUPY
                    AKTYWNY=TAK 		

      ELEMENT[N]=< KOD=E_ALP_NVF_PAS_3604_01        NR_PRZEKROJU=517 ILOSC='1'                 STRONA=KOLOR_WEWN  >
      ELEMENT[N]=< KOD=E_ALP_NVF_PAS_3835_01        NR_PRZEKROJU=517 ILOSC='1*NVF_PODOVGUVACH' STRONA=KOLOR_WEWN  >
      ELEMENT[N]=< KOD=E_ALP_NVF_Zakl_5_10_DIN7337  NR_PRZEKROJU=517 ILOSC='2'                 STRONA=KOLOR_WEWN  >
      ELEMENT[N]=< KOD=E_ALP_NVF_Zakl_5_10_DIN7337  NR_PRZEKROJU=517 ILOSC='2*NVF_PODOVGUVACH' STRONA=KOLOR_WEWN  >
	  
      ELEMENT[N]=< KOD=E_ALP_NVF_TERMO_70_50_5      NR_PRZEKROJU=517 ILOSC='1'                 STRONA=KOLOR_WEWN  >  
	  >	   
	  
    GRUPA[1104]=
      <
      NAZWA=     'Кронштейн ПАС-3605.01 170х45х60 / БП 0,06м [НВФ]'
      OPIS=      'Кронштейн ПАС-3605.01 170х45х60 / БП 0,06м [НВФ]'
      ZESTAW=    '{ 1. Кронштейн оновленний <b>60mm</b> <FONT COLOR="#0000FF"><FONT-SIZE="2"><b><big>(Рухомий)</b><FONT-SIZE="1">}'

      RODZAJ=1
	  
      PARAMETRY=
	    <
        Z_LISTY=
            < KLUCZ='NVF_PODOVGUVACH' 
			  PYTANIE='Використовувати подовжувача до кронштейна:' 
              ELEMENT     = 'Без подовжувача'   
              ELEMENT     = 'З використаням подовжувача 100х60 (ПАС-3835.01)'   			  
              STANDARDOWO = '0'			  
		  >	  	  
		>		 
	  
	  SYSTEMY= [DEF_SYS_NVF_KERAM_KLIAM, DEF_SYS_NVF_KERAM_GLUE,DEF_SYS_NVF_AKP,DEF_SYS_NVF_HPL_PANEL,DEF_SYS_NVF_FZP]
      RYSUNEK= 'PAS_3602_01_KR.png'
      WLASNY_RYSUNEK=TAK 
					ROZMIAR_X='100'
					ROZMIAR_Y='100'	
                    RYSUNEK=   'fix_podv1.vct'					
	  			    POLOZENIE_X='0'
					POLOZENIE_Y='0'
					WYMIARY_GRUPY
                    AKTYWNY=TAK 		

      ELEMENT[N]=< KOD=E_ALP_NVF_PAS_3605_01         NR_PRZEKROJU=517 ILOSC='1'                 STRONA=KOLOR_WEWN  >
      ELEMENT[N]=< KOD=E_ALP_NVF_PAS_3835_01        NR_PRZEKROJU=517 ILOSC='1*NVF_PODOVGUVACH' STRONA=KOLOR_WEWN  >
      ELEMENT[N]=< KOD=E_ALP_NVF_Zakl_5_10_DIN7337  NR_PRZEKROJU=517 ILOSC='2'                 STRONA=KOLOR_WEWN  >
      ELEMENT[N]=< KOD=E_ALP_NVF_Zakl_5_10_DIN7337  NR_PRZEKROJU=517 ILOSC='2*NVF_PODOVGUVACH' STRONA=KOLOR_WEWN  >
	  
      ELEMENT[N]=< KOD=E_ALP_NVF_TERMO_70_50_5      NR_PRZEKROJU=517 ILOSC='1'                 STRONA=KOLOR_WEWN  >  
	  >	  
	  
    GRUPA[1105]=
      <
      NAZWA=     'Кронштейн ПАС-3606.01 200х45х60 / БП 0,06м [НВФ]'
      OPIS=      'Кронштейн ПАС-3606.01 200х45х60 / БП 0,06м [НВФ]'
      ZESTAW=    '{ 1. Кронштейн оновленний <b>60mm</b> <FONT COLOR="#0000FF"><FONT-SIZE="2"><b><big>(Рухомий)</b><FONT-SIZE="1">}'

      RODZAJ=1
	  
      PARAMETRY=
	    <
        Z_LISTY=
            < KLUCZ='NVF_PODOVGUVACH' 
			  PYTANIE='Використовувати подовжувача до кронштейна:' 
              ELEMENT     = 'Без подовжувача'   
              ELEMENT     = 'З використаням подовжувача 100х60 (ПАС-3835.01)'   			  
              STANDARDOWO = '0'			  
		  >	  	  
		>		 
	  
	  SYSTEMY= [DEF_SYS_NVF_KERAM_KLIAM, DEF_SYS_NVF_KERAM_GLUE,DEF_SYS_NVF_AKP,DEF_SYS_NVF_HPL_PANEL,DEF_SYS_NVF_FZP]
      RYSUNEK= 'PAS_3602_01_KR.png'
      WLASNY_RYSUNEK=TAK 
					ROZMIAR_X='100'
					ROZMIAR_Y='100'	
                    RYSUNEK=   'fix_podv1.vct'					
	  			    POLOZENIE_X='0'
					POLOZENIE_Y='0'
					WYMIARY_GRUPY
                    AKTYWNY=TAK 		

      ELEMENT[N]=< KOD=E_ALP_NVF_PAS_3606_01        NR_PRZEKROJU=517 ILOSC='1'                 STRONA=KOLOR_WEWN  >
      ELEMENT[N]=< KOD=E_ALP_NVF_PAS_3835_01        NR_PRZEKROJU=517 ILOSC='1*NVF_PODOVGUVACH' STRONA=KOLOR_WEWN  >
      ELEMENT[N]=< KOD=E_ALP_NVF_Zakl_5_10_DIN7337  NR_PRZEKROJU=517 ILOSC='2'                 STRONA=KOLOR_WEWN  >
      ELEMENT[N]=< KOD=E_ALP_NVF_Zakl_5_10_DIN7337  NR_PRZEKROJU=517 ILOSC='2*NVF_PODOVGUVACH' STRONA=KOLOR_WEWN  >
	  
      ELEMENT[N]=< KOD=E_ALP_NVF_TERMO_70_50_5      NR_PRZEKROJU=517 ILOSC='1'                 STRONA=KOLOR_WEWN  >  
	  >	    

    GRUPA[1106]=
      <
      NAZWA=     'Кронштейн ПАС-3607.01 230х45х60 / БП 0,06м [НВФ]'
      OPIS=      'Кронштейн ПАС-3607.01 230х45х60 / БП 0,06м [НВФ]'
      ZESTAW=    '{ 1. Кронштейн оновленний <b>60mm</b> <FONT COLOR="#0000FF"><FONT-SIZE="2"><b><big>(Рухомий)</b><FONT-SIZE="1">}'

      RODZAJ=1
	  
      PARAMETRY=
	    <
        Z_LISTY=
            < KLUCZ='NVF_PODOVGUVACH' 
			  PYTANIE='Використовувати подовжувача до кронштейна:' 
              ELEMENT     = 'Без подовжувача'   
              ELEMENT     = 'З використаням подовжувача 100х60 (ПАС-3835.01)'   			  
              STANDARDOWO = '0'			  
		  >	  	  
		>		 
	  
	  SYSTEMY= [DEF_SYS_NVF_KERAM_KLIAM, DEF_SYS_NVF_KERAM_GLUE,DEF_SYS_NVF_AKP,DEF_SYS_NVF_HPL_PANEL,DEF_SYS_NVF_FZP]
      RYSUNEK= 'PAS_3602_01_KR.png'
      WLASNY_RYSUNEK=TAK 
					ROZMIAR_X='100'
					ROZMIAR_Y='100'	
                    RYSUNEK=   'fix_podv1.vct'					
	  			    POLOZENIE_X='0'
					POLOZENIE_Y='0'
					WYMIARY_GRUPY
                    AKTYWNY=TAK 		

      ELEMENT[N]=< KOD=E_ALP_NVF_PAS_3607_01        NR_PRZEKROJU=517 ILOSC='1'                 STRONA=KOLOR_WEWN  >
      ELEMENT[N]=< KOD=E_ALP_NVF_PAS_3835_01        NR_PRZEKROJU=517 ILOSC='1*NVF_PODOVGUVACH' STRONA=KOLOR_WEWN  >
      ELEMENT[N]=< KOD=E_ALP_NVF_Zakl_5_10_DIN7337  NR_PRZEKROJU=517 ILOSC='2'                 STRONA=KOLOR_WEWN  >
      ELEMENT[N]=< KOD=E_ALP_NVF_Zakl_5_10_DIN7337  NR_PRZEKROJU=517 ILOSC='2*NVF_PODOVGUVACH' STRONA=KOLOR_WEWN  >
	  
      ELEMENT[N]=< KOD=E_ALP_NVF_TERMO_70_50_5      NR_PRZEKROJU=517 ILOSC='1'                 STRONA=KOLOR_WEWN  >  
	  >	  
	  
  //***************************************	  
	  
    GRUPA[1107]=
      <
      NAZWA=     'Кронштейн ПАС-3602.02 100х45х90 / БП 0,09м [НВФ]'
      OPIS=      'Кронштейн ПАС-3602.02 100х45х90 / БП 0,09м [НВФ]'
      ZESTAW=    '{ 2. Кронштейн оновленний <b>90mm</b> <FONT COLOR="#0000FF"><FONT-SIZE="2"><b><big>(Рухомий)</b><FONT-SIZE="1">}'

      RODZAJ=1
	  
      PARAMETRY=
	    <
        Z_LISTY=
            < KLUCZ       = 'NVF_PODOVGUVACH' 
			  PYTANIE     = 'Використовувати подовжувача до кронштейна:' 
              ELEMENT     = 'Без подовжувача'   
              ELEMENT     = 'З використаням подовжувача 100х90 (ПАС-3835.02)'   			  
              STANDARDOWO = '0'			  
		  >	  	  
		>		 
	  
	  SYSTEMY= [DEF_SYS_NVF_KERAM_KLIAM, DEF_SYS_NVF_KERAM_GLUE,DEF_SYS_NVF_AKP,DEF_SYS_NVF_HPL_PANEL,DEF_SYS_NVF_FZP]
      RYSUNEK= 'PAS_3602_02_KR.png'
      WLASNY_RYSUNEK=TAK 
					ROZMIAR_X='100'
					ROZMIAR_Y='100'	
                    RYSUNEK=   'fix_podv1.vct'					
	  			    POLOZENIE_X='0'
					POLOZENIE_Y='0'
					WYMIARY_GRUPY
                    AKTYWNY=TAK 		

      ELEMENT[N]=< KOD=E_ALP_NVF_PAS_3602_02        NR_PRZEKROJU=517 ILOSC='1'                 STRONA=KOLOR_WEWN  >
      ELEMENT[N]=< KOD=E_ALP_NVF_PAS_3835_02        NR_PRZEKROJU=517 ILOSC='1*NVF_PODOVGUVACH' STRONA=KOLOR_WEWN  >
      ELEMENT[N]=< KOD=E_ALP_NVF_Zakl_5_10_DIN7337  NR_PRZEKROJU=517 ILOSC='2'                 STRONA=KOLOR_WEWN  >
      ELEMENT[N]=< KOD=E_ALP_NVF_Zakl_5_10_DIN7337  NR_PRZEKROJU=517 ILOSC='2*NVF_PODOVGUVACH' STRONA=KOLOR_WEWN  >
	  
      ELEMENT[N]=< KOD=E_ALP_NVF_TERMO_70_50_5      NR_PRZEKROJU=517 ILOSC='1'                 STRONA=KOLOR_WEWN  >  
	  >	  
	  
    GRUPA[1108]=
      <
      NAZWA=     'Кронштейн ПАС-3603.02 130х45х90 / БП 0,09м [НВФ]'
      OPIS=      'Кронштейн ПАС-3603.02 130х45х90 / БП 0,09м [НВФ]'
      ZESTAW=    '{ 2. Кронштейн оновленний <b>90mm</b> <FONT COLOR="#0000FF"><FONT-SIZE="2"><b><big>(Рухомий)</b><FONT-SIZE="1">}'

      RODZAJ=1
	  
      PARAMETRY=
	    <
        Z_LISTY=
            < KLUCZ       = 'NVF_PODOVGUVACH' 
			  PYTANIE     = 'Використовувати подовжувача до кронштейна:' 
              ELEMENT     = 'Без подовжувача'   
              ELEMENT     = 'З використаням подовжувача 100х90 (ПАС-3835.02)'   			  
              STANDARDOWO = '0'			  
		  >	  	  
		>		 
	  
	  SYSTEMY= [DEF_SYS_NVF_KERAM_KLIAM, DEF_SYS_NVF_KERAM_GLUE,DEF_SYS_NVF_AKP,DEF_SYS_NVF_HPL_PANEL,DEF_SYS_NVF_FZP]
      RYSUNEK= 'PAS_3602_02_KR.png'
      WLASNY_RYSUNEK=TAK 
					ROZMIAR_X='100'
					ROZMIAR_Y='100'	
                    RYSUNEK=   'fix_podv1.vct'					
	  			    POLOZENIE_X='0'
					POLOZENIE_Y='0'
					WYMIARY_GRUPY
                    AKTYWNY=TAK 		

      ELEMENT[N]=< KOD=E_ALP_NVF_PAS_3603_02        NR_PRZEKROJU=517 ILOSC='1'                 STRONA=KOLOR_WEWN  >
      ELEMENT[N]=< KOD=E_ALP_NVF_PAS_3835_02        NR_PRZEKROJU=517 ILOSC='1*NVF_PODOVGUVACH' STRONA=KOLOR_WEWN  >
      ELEMENT[N]=< KOD=E_ALP_NVF_Zakl_5_10_DIN7337  NR_PRZEKROJU=517 ILOSC='2'                 STRONA=KOLOR_WEWN  >
      ELEMENT[N]=< KOD=E_ALP_NVF_Zakl_5_10_DIN7337  NR_PRZEKROJU=517 ILOSC='2*NVF_PODOVGUVACH' STRONA=KOLOR_WEWN  >
	  
      ELEMENT[N]=< KOD=E_ALP_NVF_TERMO_70_50_5      NR_PRZEKROJU=517 ILOSC='1'                 STRONA=KOLOR_WEWN  >  
	  >	  
	  
    GRUPA[1109]=
      <
      NAZWA=     'Кронштейн ПАС-3604.02 150х45х90 / БП 0,09м [НВФ]'
      OPIS=      'Кронштейн ПАС-3604.02 150х45х90 / БП 0,09м [НВФ]'
      ZESTAW=    '{ 2. Кронштейн оновленний <b>90mm</b> <FONT COLOR="#0000FF"><FONT-SIZE="2"><b><big>(Рухомий)</b><FONT-SIZE="1">}'

      RODZAJ=1
	  
      PARAMETRY=
	    <
        Z_LISTY=
            < KLUCZ       = 'NVF_PODOVGUVACH' 
			  PYTANIE     = 'Використовувати подовжувача до кронштейна:' 
              ELEMENT     = 'Без подовжувача'   
              ELEMENT     = 'З використаням подовжувача 100х90 (ПАС-3835.02)'   			  
              STANDARDOWO = '0'			  
		  >	  	  
		>		 
	  
	  SYSTEMY= [DEF_SYS_NVF_KERAM_KLIAM, DEF_SYS_NVF_KERAM_GLUE,DEF_SYS_NVF_AKP,DEF_SYS_NVF_HPL_PANEL,DEF_SYS_NVF_FZP]
      RYSUNEK= 'PAS_3602_02_KR.png'
      WLASNY_RYSUNEK=TAK 
					ROZMIAR_X='100'
					ROZMIAR_Y='100'	
                    RYSUNEK=   'fix_podv1.vct'					
	  			    POLOZENIE_X='0'
					POLOZENIE_Y='0'
					WYMIARY_GRUPY
                    AKTYWNY=TAK 		

      ELEMENT[N]=< KOD=E_ALP_NVF_PAS_3604_02        NR_PRZEKROJU=517 ILOSC='1'                 STRONA=KOLOR_WEWN  >
      ELEMENT[N]=< KOD=E_ALP_NVF_PAS_3835_02        NR_PRZEKROJU=517 ILOSC='1*NVF_PODOVGUVACH' STRONA=KOLOR_WEWN  >
      ELEMENT[N]=< KOD=E_ALP_NVF_Zakl_5_10_DIN7337  NR_PRZEKROJU=517 ILOSC='2'                 STRONA=KOLOR_WEWN  >
      ELEMENT[N]=< KOD=E_ALP_NVF_Zakl_5_10_DIN7337  NR_PRZEKROJU=517 ILOSC='2*NVF_PODOVGUVACH' STRONA=KOLOR_WEWN  >
	  
      ELEMENT[N]=< KOD=E_ALP_NVF_TERMO_70_50_5      NR_PRZEKROJU=517 ILOSC='1'                 STRONA=KOLOR_WEWN  >  
	  >	  
	  
    GRUPA[1110]=
      <
      NAZWA=     'Кронштейн ПАС-3605.04 170х45х90 / БП 0,09м [НВФ]'
      OPIS=      'Кронштейн ПАС-3605.04 170х45х90 / БП 0,09м [НВФ]'
      ZESTAW=    '{ 2. Кронштейн оновленний <b>90mm</b> <FONT COLOR="#0000FF"><FONT-SIZE="2"><b><big>(Рухомий)</b><FONT-SIZE="1">}'

      RODZAJ=1
	  
      PARAMETRY=
	    <
        Z_LISTY=
            < KLUCZ       = 'NVF_PODOVGUVACH' 
			  PYTANIE     = 'Використовувати подовжувача до кронштейна:' 
              ELEMENT     = 'Без подовжувача'   
              ELEMENT     = 'З використаням подовжувача 100х90 (ПАС-3835.02)'   			  
              STANDARDOWO = '0'			  
		  >	  	  
		>		 
	  
	  SYSTEMY= [DEF_SYS_NVF_KERAM_KLIAM, DEF_SYS_NVF_KERAM_GLUE,DEF_SYS_NVF_AKP,DEF_SYS_NVF_HPL_PANEL,DEF_SYS_NVF_FZP]
      RYSUNEK= 'PAS_3602_02_KR.png'
      WLASNY_RYSUNEK=TAK 
					ROZMIAR_X='100'
					ROZMIAR_Y='100'	
                    RYSUNEK=   'fix_podv1.vct'					
	  			    POLOZENIE_X='0'
					POLOZENIE_Y='0'
					WYMIARY_GRUPY
                    AKTYWNY=TAK 		

      ELEMENT[N]=< KOD=E_ALP_NVF_PAS_3605_04        NR_PRZEKROJU=517 ILOSC='1'                 STRONA=KOLOR_WEWN  >
      ELEMENT[N]=< KOD=E_ALP_NVF_PAS_3835_02        NR_PRZEKROJU=517 ILOSC='1*NVF_PODOVGUVACH' STRONA=KOLOR_WEWN  >
      ELEMENT[N]=< KOD=E_ALP_NVF_Zakl_5_10_DIN7337  NR_PRZEKROJU=517 ILOSC='2'                 STRONA=KOLOR_WEWN  >
      ELEMENT[N]=< KOD=E_ALP_NVF_Zakl_5_10_DIN7337  NR_PRZEKROJU=517 ILOSC='2*NVF_PODOVGUVACH' STRONA=KOLOR_WEWN  >
	  
      ELEMENT[N]=< KOD=E_ALP_NVF_TERMO_70_50_5      NR_PRZEKROJU=517 ILOSC='1'                 STRONA=KOLOR_WEWN  >  
	  >	  
	  
    GRUPA[1111]=
      <
      NAZWA=     'Кронштейн ПАС-3606.03 200х45х90 / БП 0,09м [НВФ]'
      OPIS=      'Кронштейн ПАС-3606.03 200х45х90 / БП 0,09м [НВФ]'
      ZESTAW=    '{ 2. Кронштейн оновленний <b>90mm</b> <FONT COLOR="#0000FF"><FONT-SIZE="2"><b><big>(Рухомий)</b><FONT-SIZE="1">}'

      RODZAJ=1
	  
      PARAMETRY=
	    <
        Z_LISTY=
            < KLUCZ       = 'NVF_PODOVGUVACH' 
			  PYTANIE     = 'Використовувати подовжувача до кронштейна:' 
              ELEMENT     = 'Без подовжувача'   
              ELEMENT     = 'З використаням подовжувача 100х90 (ПАС-3835.02)'   			  
              STANDARDOWO = '0'			  
		  >	  	  
		>		 
	  
	  SYSTEMY= [DEF_SYS_NVF_KERAM_KLIAM, DEF_SYS_NVF_KERAM_GLUE,DEF_SYS_NVF_AKP,DEF_SYS_NVF_HPL_PANEL,DEF_SYS_NVF_FZP]
      RYSUNEK= 'PAS_3602_02_KR.png'
      WLASNY_RYSUNEK=TAK 
					ROZMIAR_X='100'
					ROZMIAR_Y='100'	
                    RYSUNEK=   'fix_podv1.vct'					
	  			    POLOZENIE_X='0'
					POLOZENIE_Y='0'
					WYMIARY_GRUPY
                    AKTYWNY=TAK 		

      ELEMENT[N]=< KOD=E_ALP_NVF_PAS_3606_03        NR_PRZEKROJU=517 ILOSC='1'                 STRONA=KOLOR_WEWN  >
      ELEMENT[N]=< KOD=E_ALP_NVF_PAS_3835_02        NR_PRZEKROJU=517 ILOSC='1*NVF_PODOVGUVACH' STRONA=KOLOR_WEWN  >
      ELEMENT[N]=< KOD=E_ALP_NVF_Zakl_5_10_DIN7337  NR_PRZEKROJU=517 ILOSC='2'                 STRONA=KOLOR_WEWN  >
      ELEMENT[N]=< KOD=E_ALP_NVF_Zakl_5_10_DIN7337  NR_PRZEKROJU=517 ILOSC='2*NVF_PODOVGUVACH' STRONA=KOLOR_WEWN  >
	  
      ELEMENT[N]=< KOD=E_ALP_NVF_TERMO_70_50_5      NR_PRZEKROJU=517 ILOSC='1'                 STRONA=KOLOR_WEWN  >  
	  >	  
	  
    GRUPA[1112]=
      <
      NAZWA=     'Кронштейн ПАС-3607.02 230х45х90 / БП 0,09м [НВФ]'
      OPIS=      'Кронштейн ПАС-3607.02 230х45х90 / БП 0,09м [НВФ]'
      ZESTAW=    '{ 2. Кронштейн оновленний <b>90mm</b> <FONT COLOR="#0000FF"><FONT-SIZE="2"><b><big>(Рухомий)</b><FONT-SIZE="1">}'

      RODZAJ=1
	  
      PARAMETRY=
	    <
        Z_LISTY=
            < KLUCZ       = 'NVF_PODOVGUVACH' 
			  PYTANIE     = 'Використовувати подовжувача до кронштейна:' 
              ELEMENT     = 'Без подовжувача'   
              ELEMENT     = 'З використаням подовжувача 100х90 (ПАС-3835.02)'   			  
              STANDARDOWO = '0'			  
		  >	  	  
		>		 
	  
	  SYSTEMY= [DEF_SYS_NVF_KERAM_KLIAM, DEF_SYS_NVF_KERAM_GLUE,DEF_SYS_NVF_AKP,DEF_SYS_NVF_HPL_PANEL,DEF_SYS_NVF_FZP]
      RYSUNEK= 'PAS_3602_02_KR.png'
      WLASNY_RYSUNEK=TAK 
					ROZMIAR_X='100'
					ROZMIAR_Y='100'	
                    RYSUNEK=   'fix_podv1.vct'					
	  			    POLOZENIE_X='0'
					POLOZENIE_Y='0'
					WYMIARY_GRUPY
                    AKTYWNY=TAK 		

      ELEMENT[N]=< KOD=E_ALP_NVF_PAS_3607_02        NR_PRZEKROJU=517 ILOSC='1'                 STRONA=KOLOR_WEWN  >
      ELEMENT[N]=< KOD=E_ALP_NVF_PAS_3835_02        NR_PRZEKROJU=517 ILOSC='1*NVF_PODOVGUVACH' STRONA=KOLOR_WEWN  >
      ELEMENT[N]=< KOD=E_ALP_NVF_Zakl_5_10_DIN7337  NR_PRZEKROJU=517 ILOSC='2'                 STRONA=KOLOR_WEWN  >
      ELEMENT[N]=< KOD=E_ALP_NVF_Zakl_5_10_DIN7337  NR_PRZEKROJU=517 ILOSC='2*NVF_PODOVGUVACH' STRONA=KOLOR_WEWN  >
	  
      ELEMENT[N]=< KOD=E_ALP_NVF_TERMO_70_50_5      NR_PRZEKROJU=517 ILOSC='1'                 STRONA=KOLOR_WEWN  >  
	  >	  

  //***************************************	  
	  
    GRUPA[1113]=
      <
      NAZWA=     'Кронштейн ПАС-3602.02 100х45х90 / БП 0,09м [НВФ]'
      OPIS=      'Кронштейн ПАС-3602.02 100х45х90 / БП 0,09м [НВФ]'
      ZESTAW=    '{ 3. Кронштейн оновленний <b>90mm</b> <FONT COLOR="#FF0000"><FONT-SIZE="2"><b><big>(Фіксовані)</b><FONT-SIZE="1">}'

      RODZAJ=1
	  
      PARAMETRY=
	    <
        Z_LISTY=
            < KLUCZ       = 'NVF_PODOVGUVACH' 
			  PYTANIE     = 'Використовувати подовжувача до кронштейна:' 
              ELEMENT     = 'Без подовжувача'   
              ELEMENT     = 'З використаням подовжувача 100х90 (ПАС-3835.02)'   			  
              STANDARDOWO = '0'			  
		  >	  	  
		>		 
	  
	  SYSTEMY= [DEF_SYS_NVF_KERAM_KLIAM, DEF_SYS_NVF_KERAM_GLUE,DEF_SYS_NVF_AKP,DEF_SYS_NVF_HPL_PANEL,DEF_SYS_NVF_FZP]
      RYSUNEK= 'PAS_3602_02_KR.png'
      WLASNY_RYSUNEK=TAK 
					ROZMIAR_X='100'
					ROZMIAR_Y='100'	
                    RYSUNEK=   'fix_nepodv.vct'					
	  			    POLOZENIE_X='0'
					POLOZENIE_Y='0'
					WYMIARY_GRUPY
                    AKTYWNY=TAK 		

      ELEMENT[N]=< KOD=E_ALP_NVF_PAS_3602_02        NR_PRZEKROJU=517 ILOSC='1'                 STRONA=KOLOR_WEWN  >
      ELEMENT[N]=< KOD=E_ALP_NVF_PAS_3835_02        NR_PRZEKROJU=517 ILOSC='1*NVF_PODOVGUVACH' STRONA=KOLOR_WEWN  >
      ELEMENT[N]=< KOD=E_ALP_NVF_Zakl_5_10_DIN7337  NR_PRZEKROJU=517 ILOSC='2'                 STRONA=KOLOR_WEWN  >
      ELEMENT[N]=< KOD=E_ALP_NVF_Zakl_5_10_DIN7337  NR_PRZEKROJU=517 ILOSC='2*NVF_PODOVGUVACH' STRONA=KOLOR_WEWN  >
	  
      ELEMENT[N]=< KOD=E_ALP_NVF_TERMO_70_50_5      NR_PRZEKROJU=517 ILOSC='1'                 STRONA=KOLOR_WEWN  >  
	  >	  
	  
    GRUPA[1114]=
      <
      NAZWA=     'Кронштейн ПАС-3603.02 130х45х90 / БП 0,09м [НВФ]'
      OPIS=      'Кронштейн ПАС-3603.02 130х45х90 / БП 0,09м [НВФ]'
      ZESTAW=    '{ 3. Кронштейн оновленний <b>90mm</b> <FONT COLOR="#FF0000"><FONT-SIZE="2"><b><big>(Фіксовані)</b><FONT-SIZE="1">}'

      RODZAJ=1
	  
      PARAMETRY=
	    <
        Z_LISTY=
            < KLUCZ       = 'NVF_PODOVGUVACH' 
			  PYTANIE     = 'Використовувати подовжувача до кронштейна:' 
              ELEMENT     = 'Без подовжувача'   
              ELEMENT     = 'З використаням подовжувача 100х90 (ПАС-3835.02)'   			  
              STANDARDOWO = '0'			  
		  >	  	  
		>		 
	  
	  SYSTEMY= [DEF_SYS_NVF_KERAM_KLIAM, DEF_SYS_NVF_KERAM_GLUE,DEF_SYS_NVF_AKP,DEF_SYS_NVF_HPL_PANEL,DEF_SYS_NVF_FZP]
      RYSUNEK= 'PAS_3602_02_KR.png'
      WLASNY_RYSUNEK=TAK 
					ROZMIAR_X='100'
					ROZMIAR_Y='100'	
                    RYSUNEK=   'fix_nepodv.vct'					
	  			    POLOZENIE_X='0'
					POLOZENIE_Y='0'
					WYMIARY_GRUPY
                    AKTYWNY=TAK 		

      ELEMENT[N]=< KOD=E_ALP_NVF_PAS_3603_02        NR_PRZEKROJU=517 ILOSC='1'                 STRONA=KOLOR_WEWN  >
      ELEMENT[N]=< KOD=E_ALP_NVF_PAS_3835_02        NR_PRZEKROJU=517 ILOSC='1*NVF_PODOVGUVACH' STRONA=KOLOR_WEWN  >
      ELEMENT[N]=< KOD=E_ALP_NVF_Zakl_5_10_DIN7337  NR_PRZEKROJU=517 ILOSC='2'                 STRONA=KOLOR_WEWN  >
      ELEMENT[N]=< KOD=E_ALP_NVF_Zakl_5_10_DIN7337  NR_PRZEKROJU=517 ILOSC='2*NVF_PODOVGUVACH' STRONA=KOLOR_WEWN  >
	  
      ELEMENT[N]=< KOD=E_ALP_NVF_TERMO_70_50_5      NR_PRZEKROJU=517 ILOSC='1'                 STRONA=KOLOR_WEWN  >  
	  >	  
	  
    GRUPA[1115]=
      <
      NAZWA=     'Кронштейн ПАС-3604.02 150х45х90 / БП 0,09м [НВФ]'
      OPIS=      'Кронштейн ПАС-3604.02 150х45х90 / БП 0,09м [НВФ]'
      ZESTAW=    '{ 3. Кронштейн оновленний <b>90mm</b> <FONT COLOR="#FF0000"><FONT-SIZE="2"><b><big>(Фіксовані)</b><FONT-SIZE="1">}'

      RODZAJ=1
	  
      PARAMETRY=
	    <
        Z_LISTY=
            < KLUCZ       = 'NVF_PODOVGUVACH' 
			  PYTANIE     = 'Використовувати подовжувача до кронштейна:' 
              ELEMENT     = 'Без подовжувача'   
              ELEMENT     = 'З використаням подовжувача 100х90 (ПАС-3835.02)'   			  
              STANDARDOWO = '0'			  
		  >	  	  
		>		 
	  
	  SYSTEMY= [DEF_SYS_NVF_KERAM_KLIAM, DEF_SYS_NVF_KERAM_GLUE,DEF_SYS_NVF_AKP,DEF_SYS_NVF_HPL_PANEL,DEF_SYS_NVF_FZP]
      RYSUNEK= 'PAS_3602_02_KR.png'
      WLASNY_RYSUNEK=TAK 
					ROZMIAR_X='100'
					ROZMIAR_Y='100'	
                    RYSUNEK=   'fix_nepodv.vct'					
	  			    POLOZENIE_X='0'
					POLOZENIE_Y='0'
					WYMIARY_GRUPY
                    AKTYWNY=TAK 		

      ELEMENT[N]=< KOD=E_ALP_NVF_PAS_3604_02        NR_PRZEKROJU=517 ILOSC='1'                 STRONA=KOLOR_WEWN  >
      ELEMENT[N]=< KOD=E_ALP_NVF_PAS_3835_02        NR_PRZEKROJU=517 ILOSC='1*NVF_PODOVGUVACH' STRONA=KOLOR_WEWN  >
      ELEMENT[N]=< KOD=E_ALP_NVF_Zakl_5_10_DIN7337  NR_PRZEKROJU=517 ILOSC='2'                 STRONA=KOLOR_WEWN  >
      ELEMENT[N]=< KOD=E_ALP_NVF_Zakl_5_10_DIN7337  NR_PRZEKROJU=517 ILOSC='2*NVF_PODOVGUVACH' STRONA=KOLOR_WEWN  >
	  
      ELEMENT[N]=< KOD=E_ALP_NVF_TERMO_70_50_5      NR_PRZEKROJU=517 ILOSC='1'                 STRONA=KOLOR_WEWN  >  
	  >	  
	  
    GRUPA[1116]=
      <
      NAZWA=     'Кронштейн ПАС-3605.04 170х45х90 / БП 0,09м [НВФ]'
      OPIS=      'Кронштейн ПАС-3605.04 170х45х90 / БП 0,09м [НВФ]'
      ZESTAW=    '{ 3. Кронштейн оновленний <b>90mm</b> <FONT COLOR="#FF0000"><FONT-SIZE="2"><b><big>(Фіксовані)</b><FONT-SIZE="1">}'

      RODZAJ=1
	  
      PARAMETRY=
	    <
        Z_LISTY=
            < KLUCZ       = 'NVF_PODOVGUVACH' 
			  PYTANIE     = 'Використовувати подовжувача до кронштейна:' 
              ELEMENT     = 'Без подовжувача'   
              ELEMENT     = 'З використаням подовжувача 100х90 (ПАС-3835.02)'   			  
              STANDARDOWO = '0'			  
		  >	  	  
		>		 
	  
	  SYSTEMY= [DEF_SYS_NVF_KERAM_KLIAM, DEF_SYS_NVF_KERAM_GLUE,DEF_SYS_NVF_AKP,DEF_SYS_NVF_HPL_PANEL,DEF_SYS_NVF_FZP]
      RYSUNEK= 'PAS_3602_02_KR.png'
      WLASNY_RYSUNEK=TAK 
					ROZMIAR_X='100'
					ROZMIAR_Y='100'	
                    RYSUNEK=   'fix_nepodv.vct'					
	  			    POLOZENIE_X='0'
					POLOZENIE_Y='0'
					WYMIARY_GRUPY
                    AKTYWNY=TAK 		

      ELEMENT[N]=< KOD=E_ALP_NVF_PAS_3605_04        NR_PRZEKROJU=517 ILOSC='1'                 STRONA=KOLOR_WEWN  >
      ELEMENT[N]=< KOD=E_ALP_NVF_PAS_3835_02        NR_PRZEKROJU=517 ILOSC='1*NVF_PODOVGUVACH' STRONA=KOLOR_WEWN  >
      ELEMENT[N]=< KOD=E_ALP_NVF_Zakl_5_10_DIN7337  NR_PRZEKROJU=517 ILOSC='2'                 STRONA=KOLOR_WEWN  >
      ELEMENT[N]=< KOD=E_ALP_NVF_Zakl_5_10_DIN7337  NR_PRZEKROJU=517 ILOSC='2*NVF_PODOVGUVACH' STRONA=KOLOR_WEWN  >
	  
      ELEMENT[N]=< KOD=E_ALP_NVF_TERMO_70_50_5      NR_PRZEKROJU=517 ILOSC='1'                 STRONA=KOLOR_WEWN  >  
	  >	  
	  
    GRUPA[1117]=
      <
      NAZWA=     'Кронштейн ПАС-3606.03 200х45х90 / БП 0,09м [НВФ]'
      OPIS=      'Кронштейн ПАС-3606.03 200х45х90 / БП 0,09м [НВФ]'
      ZESTAW=    '{ 3. Кронштейн оновленний <b>90mm</b> <FONT COLOR="#FF0000"><FONT-SIZE="2"><b><big>(Фіксовані)</b><FONT-SIZE="1">}'

      RODZAJ=1
	  
      PARAMETRY=
	    <
        Z_LISTY=
            < KLUCZ       = 'NVF_PODOVGUVACH' 
			  PYTANIE     = 'Використовувати подовжувача до кронштейна:' 
              ELEMENT     = 'Без подовжувача'   
              ELEMENT     = 'З використаням подовжувача 100х90 (ПАС-3835.02)'   			  
              STANDARDOWO = '0'			  
		  >	  	  
		>		 
	  
	  SYSTEMY= [DEF_SYS_NVF_KERAM_KLIAM, DEF_SYS_NVF_KERAM_GLUE,DEF_SYS_NVF_AKP,DEF_SYS_NVF_HPL_PANEL,DEF_SYS_NVF_FZP]
      RYSUNEK= 'PAS_3602_02_KR.png'
      WLASNY_RYSUNEK=TAK 
					ROZMIAR_X='100'
					ROZMIAR_Y='100'	
                    RYSUNEK=   'fix_nepodv.vct'					
	  			    POLOZENIE_X='0'
					POLOZENIE_Y='0'
					WYMIARY_GRUPY
                    AKTYWNY=TAK 		

      ELEMENT[N]=< KOD=E_ALP_NVF_PAS_3606_03        NR_PRZEKROJU=517 ILOSC='1'                 STRONA=KOLOR_WEWN  >
      ELEMENT[N]=< KOD=E_ALP_NVF_PAS_3835_02        NR_PRZEKROJU=517 ILOSC='1*NVF_PODOVGUVACH' STRONA=KOLOR_WEWN  >
      ELEMENT[N]=< KOD=E_ALP_NVF_Zakl_5_10_DIN7337  NR_PRZEKROJU=517 ILOSC='2'                 STRONA=KOLOR_WEWN  >
      ELEMENT[N]=< KOD=E_ALP_NVF_Zakl_5_10_DIN7337  NR_PRZEKROJU=517 ILOSC='2*NVF_PODOVGUVACH' STRONA=KOLOR_WEWN  >
	  
      ELEMENT[N]=< KOD=E_ALP_NVF_TERMO_70_50_5      NR_PRZEKROJU=517 ILOSC='1'                 STRONA=KOLOR_WEWN  >  
	  >	  
	  
    GRUPA[1118]=
      <
      NAZWA=     'Кронштейн ПАС-3607.02 230х45х90 / БП 0,09м [НВФ]'
      OPIS=      'Кронштейн ПАС-3607.02 230х45х90 / БП 0,09м [НВФ]'
      ZESTAW=    '{ 3. Кронштейн оновленний <b>90mm</b> <FONT COLOR="#FF0000"><FONT-SIZE="2"><b><big>(Фіксовані)</b><FONT-SIZE="1">}'

      RODZAJ=1
	  
      PARAMETRY=
	    <
        Z_LISTY=
            < KLUCZ       = 'NVF_PODOVGUVACH' 
			  PYTANIE     = 'Використовувати подовжувача до кронштейна:' 
              ELEMENT     = 'Без подовжувача'   
              ELEMENT     = 'З використаням подовжувача 100х90 (ПАС-3835.02)'   			  
              STANDARDOWO = '0'			  
		  >	  	  
		>		 
	  
	  SYSTEMY= [DEF_SYS_NVF_KERAM_KLIAM, DEF_SYS_NVF_KERAM_GLUE,DEF_SYS_NVF_AKP,DEF_SYS_NVF_HPL_PANEL,DEF_SYS_NVF_FZP]
      RYSUNEK= 'PAS_3602_02_KR.png'
      WLASNY_RYSUNEK=TAK 
					ROZMIAR_X='100'
					ROZMIAR_Y='100'	
                    RYSUNEK=   'fix_nepodv.vct'					
	  			    POLOZENIE_X='0'
					POLOZENIE_Y='0'
					WYMIARY_GRUPY
                    AKTYWNY=TAK 		

      ELEMENT[N]=< KOD=E_ALP_NVF_PAS_3607_02        NR_PRZEKROJU=517 ILOSC='1'                 STRONA=KOLOR_WEWN  >
      ELEMENT[N]=< KOD=E_ALP_NVF_PAS_3835_02        NR_PRZEKROJU=517 ILOSC='1*NVF_PODOVGUVACH' STRONA=KOLOR_WEWN  >
      ELEMENT[N]=< KOD=E_ALP_NVF_Zakl_5_10_DIN7337  NR_PRZEKROJU=517 ILOSC='2'                 STRONA=KOLOR_WEWN  >
      ELEMENT[N]=< KOD=E_ALP_NVF_Zakl_5_10_DIN7337  NR_PRZEKROJU=517 ILOSC='2*NVF_PODOVGUVACH' STRONA=KOLOR_WEWN  >
	  
      ELEMENT[N]=< KOD=E_ALP_NVF_TERMO_70_50_5      NR_PRZEKROJU=517 ILOSC='1'                 STRONA=KOLOR_WEWN  >  
	  >	  

  //***************************************	  
	  
    GRUPA[1119]=
      <
      NAZWA=     'Кронштейн ПАС-3602.03 100х45х120 / БП 0,12м [НВФ]'
      OPIS=      'Кронштейн ПАС-3602.03 100х45х120 / БП 0,12м [НВФ]'
      ZESTAW=    '{ 4. Кронштейн оновленний <b>120mm</b> <FONT COLOR="#FF0000"><FONT-SIZE="2"><b><big>(Фіксовані)</b><FONT-SIZE="1">}'

      RODZAJ=1
	  
      PARAMETRY=
	    <
        Z_LISTY=
            < KLUCZ       = 'NVF_PODOVGUVACH' 
			  PYTANIE     = 'Використовувати подовжувача до кронштейна:' 
              ELEMENT     = 'Без подовжувача'   
              ELEMENT     = 'З використаням подовжувача 100х120 (ПАС-3835.03)'   			  
              STANDARDOWO = '0'			  
		  >	  	  
		>		 
	  
	  SYSTEMY= [DEF_SYS_NVF_KERAM_KLIAM, DEF_SYS_NVF_KERAM_GLUE,DEF_SYS_NVF_AKP,DEF_SYS_NVF_HPL_PANEL,DEF_SYS_NVF_FZP]
      RYSUNEK= 'PAS_3602_03_KR.png'
      WLASNY_RYSUNEK=TAK 
					ROZMIAR_X='100'
					ROZMIAR_Y='100'	
                    RYSUNEK=   'fix_nepodv.vct'					
	  			    POLOZENIE_X='0'
					POLOZENIE_Y='0'
					WYMIARY_GRUPY
                    AKTYWNY=TAK 		

      ELEMENT[N]=< KOD=E_ALP_NVF_PAS_3602_03        NR_PRZEKROJU=517 ILOSC='1'                 STRONA=KOLOR_WEWN  >
      ELEMENT[N]=< KOD=E_ALP_NVF_PAS_3835_03        NR_PRZEKROJU=517 ILOSC='1*NVF_PODOVGUVACH' STRONA=KOLOR_WEWN  >
      ELEMENT[N]=< KOD=E_ALP_NVF_Zakl_5_10_DIN7337  NR_PRZEKROJU=517 ILOSC='2'                 STRONA=KOLOR_WEWN  >
      ELEMENT[N]=< KOD=E_ALP_NVF_Zakl_5_10_DIN7337  NR_PRZEKROJU=517 ILOSC='2*NVF_PODOVGUVACH' STRONA=KOLOR_WEWN  >
	  
      ELEMENT[N]=< KOD=E_ALP_NVF_TERMO_140_50_5     NR_PRZEKROJU=517 ILOSC='1'                 STRONA=KOLOR_WEWN  >  
	  >	  
	  
    GRUPA[1120]=
      <
      NAZWA=     'Кронштейн ПАС-3603.07 130х45х120 / БП 0,12м [НВФ]'
      OPIS=      'Кронштейн ПАС-3603.07 130х45х120 / БП 0,12м [НВФ]'
      ZESTAW=    '{ 4. Кронштейн оновленний <b>120mm</b> <FONT COLOR="#FF0000"><FONT-SIZE="2"><b><big>(Фіксовані)</b><FONT-SIZE="1">}'

      RODZAJ=1
	  
      PARAMETRY=
	    <
        Z_LISTY=
            < KLUCZ       = 'NVF_PODOVGUVACH' 
			  PYTANIE     = 'Використовувати подовжувача до кронштейна:' 
              ELEMENT     = 'Без подовжувача'   
              ELEMENT     = 'З використаням подовжувача 100х120 (ПАС-3835.03)'   			  
              STANDARDOWO = '0'			  
		  >	  	  
		>		 
	  
	  SYSTEMY= [DEF_SYS_NVF_KERAM_KLIAM, DEF_SYS_NVF_KERAM_GLUE,DEF_SYS_NVF_AKP,DEF_SYS_NVF_HPL_PANEL,DEF_SYS_NVF_FZP]
      RYSUNEK= 'PAS_3602_03_KR.png'
      WLASNY_RYSUNEK=TAK 
					ROZMIAR_X='100'
					ROZMIAR_Y='100'	
                    RYSUNEK=   'fix_nepodv.vct'					
	  			    POLOZENIE_X='0'
					POLOZENIE_Y='0'
					WYMIARY_GRUPY
                    AKTYWNY=TAK 		

      ELEMENT[N]=< KOD=E_ALP_NVF_PAS_3603_07        NR_PRZEKROJU=517 ILOSC='1'                 STRONA=KOLOR_WEWN  >
      ELEMENT[N]=< KOD=E_ALP_NVF_PAS_3835_03        NR_PRZEKROJU=517 ILOSC='1*NVF_PODOVGUVACH' STRONA=KOLOR_WEWN  >
      ELEMENT[N]=< KOD=E_ALP_NVF_Zakl_5_10_DIN7337  NR_PRZEKROJU=517 ILOSC='2'                 STRONA=KOLOR_WEWN  >
      ELEMENT[N]=< KOD=E_ALP_NVF_Zakl_5_10_DIN7337  NR_PRZEKROJU=517 ILOSC='2*NVF_PODOVGUVACH' STRONA=KOLOR_WEWN  >
	  
      ELEMENT[N]=< KOD=E_ALP_NVF_TERMO_140_50_5     NR_PRZEKROJU=517 ILOSC='1'                 STRONA=KOLOR_WEWN  >  
	  >	  
	  
    GRUPA[1121]=
      <
      NAZWA=     'Кронштейн ПАС-3604.07 150х45х120 / БП 0,12м [НВФ]'
      OPIS=      'Кронштейн ПАС-3604.07 150х45х120 / БП 0,12м [НВФ]'
      ZESTAW=    '{ 4. Кронштейн оновленний <b>120mm</b> <FONT COLOR="#FF0000"><FONT-SIZE="2"><b><big>(Фіксовані)</b><FONT-SIZE="1">}'

      RODZAJ=1
	  
      PARAMETRY=
	    <
        Z_LISTY=
            < KLUCZ       = 'NVF_PODOVGUVACH' 
			  PYTANIE     = 'Використовувати подовжувача до кронштейна:' 
              ELEMENT     = 'Без подовжувача'   
              ELEMENT     = 'З використаням подовжувача 100х120 (ПАС-3835.03)'   			  
              STANDARDOWO = '0'			  
		  >	  	  
		>		 
	  
	  SYSTEMY= [DEF_SYS_NVF_KERAM_KLIAM, DEF_SYS_NVF_KERAM_GLUE,DEF_SYS_NVF_AKP,DEF_SYS_NVF_HPL_PANEL,DEF_SYS_NVF_FZP]
      RYSUNEK= 'PAS_3602_03_KR.png'
      WLASNY_RYSUNEK=TAK 
					ROZMIAR_X='100'
					ROZMIAR_Y='100'	
                    RYSUNEK=   'fix_nepodv.vct'					
	  			    POLOZENIE_X='0'
					POLOZENIE_Y='0'
					WYMIARY_GRUPY
                    AKTYWNY=TAK 		

      ELEMENT[N]=< KOD=E_ALP_NVF_PAS_3604_07        NR_PRZEKROJU=517 ILOSC='1'                 STRONA=KOLOR_WEWN  >
      ELEMENT[N]=< KOD=E_ALP_NVF_PAS_3835_03        NR_PRZEKROJU=517 ILOSC='1*NVF_PODOVGUVACH' STRONA=KOLOR_WEWN  >
      ELEMENT[N]=< KOD=E_ALP_NVF_Zakl_5_10_DIN7337  NR_PRZEKROJU=517 ILOSC='2'                 STRONA=KOLOR_WEWN  >
      ELEMENT[N]=< KOD=E_ALP_NVF_Zakl_5_10_DIN7337  NR_PRZEKROJU=517 ILOSC='2*NVF_PODOVGUVACH' STRONA=KOLOR_WEWN  >
	  
      ELEMENT[N]=< KOD=E_ALP_NVF_TERMO_140_50_5     NR_PRZEKROJU=517 ILOSC='1'                 STRONA=KOLOR_WEWN  >  
	  >	  
	  
    GRUPA[1122]=
      <
      NAZWA=     'Кронштейн ПАС-3605.02 170х45х120 / БП 0,12м [НВФ]'
      OPIS=      'Кронштейн ПАС-3605.02 170х45х120 / БП 0,12м [НВФ]'
      ZESTAW=    '{ 4. Кронштейн оновленний <b>120mm</b> <FONT COLOR="#FF0000"><FONT-SIZE="2"><b><big>(Фіксовані)</b><FONT-SIZE="1">}'

      RODZAJ=1
	  
      PARAMETRY=
	    <
        Z_LISTY=
            < KLUCZ       = 'NVF_PODOVGUVACH' 
			  PYTANIE     = 'Використовувати подовжувача до кронштейна:' 
              ELEMENT     = 'Без подовжувача'   
              ELEMENT     = 'З використаням подовжувача 100х120 (ПАС-3835.03)'   			  
              STANDARDOWO = '0'			  
		  >	  	  
		>		 
	  
	  SYSTEMY= [DEF_SYS_NVF_KERAM_KLIAM, DEF_SYS_NVF_KERAM_GLUE,DEF_SYS_NVF_AKP,DEF_SYS_NVF_HPL_PANEL,DEF_SYS_NVF_FZP]
      RYSUNEK= 'PAS_3602_03_KR.png'
      WLASNY_RYSUNEK=TAK 
					ROZMIAR_X='100'
					ROZMIAR_Y='100'	
                    RYSUNEK=   'fix_nepodv.vct'					
	  			    POLOZENIE_X='0'
					POLOZENIE_Y='0'
					WYMIARY_GRUPY
                    AKTYWNY=TAK 		

      ELEMENT[N]=< KOD=E_ALP_NVF_PAS_3605_02        NR_PRZEKROJU=517 ILOSC='1'                 STRONA=KOLOR_WEWN  >
      ELEMENT[N]=< KOD=E_ALP_NVF_PAS_3835_03        NR_PRZEKROJU=517 ILOSC='1*NVF_PODOVGUVACH' STRONA=KOLOR_WEWN  >
      ELEMENT[N]=< KOD=E_ALP_NVF_Zakl_5_10_DIN7337  NR_PRZEKROJU=517 ILOSC='2'                 STRONA=KOLOR_WEWN  >
      ELEMENT[N]=< KOD=E_ALP_NVF_Zakl_5_10_DIN7337  NR_PRZEKROJU=517 ILOSC='2*NVF_PODOVGUVACH' STRONA=KOLOR_WEWN  >
	  
      ELEMENT[N]=< KOD=E_ALP_NVF_TERMO_140_50_5     NR_PRZEKROJU=517 ILOSC='1'                 STRONA=KOLOR_WEWN  >  
	  >	   
	  
    GRUPA[1123]=
      <
      NAZWA=     'Кронштейн ПАС-3606.02 200х45х120 / БП 0,12м [НВФ]'
      OPIS=      'Кронштейн ПАС-3606.02 200х45х120 / БП 0,12м [НВФ]'
      ZESTAW=    '{ 4. Кронштейн оновленний <b>120mm</b> <FONT COLOR="#FF0000"><FONT-SIZE="2"><b><big>(Фіксовані)</b><FONT-SIZE="1">}'

      RODZAJ=1
	  
      PARAMETRY=
	    <
        Z_LISTY=
            < KLUCZ       = 'NVF_PODOVGUVACH' 
			  PYTANIE     = 'Використовувати подовжувача до кронштейна:' 
              ELEMENT     = 'Без подовжувача'   
              ELEMENT     = 'З використаням подовжувача 100х120 (ПАС-3835.03)'   			  
              STANDARDOWO = '0'			  
		  >	  	  
		>		 
	  
	  SYSTEMY= [DEF_SYS_NVF_KERAM_KLIAM, DEF_SYS_NVF_KERAM_GLUE,DEF_SYS_NVF_AKP,DEF_SYS_NVF_HPL_PANEL,DEF_SYS_NVF_FZP]
      RYSUNEK= 'PAS_3602_03_KR.png'
      WLASNY_RYSUNEK=TAK 
					ROZMIAR_X='100'
					ROZMIAR_Y='100'	
                    RYSUNEK=   'fix_nepodv.vct'					
	  			    POLOZENIE_X='0'
					POLOZENIE_Y='0'
					WYMIARY_GRUPY
                    AKTYWNY=TAK 		

      ELEMENT[N]=< KOD=E_ALP_NVF_PAS_3606_02        NR_PRZEKROJU=517 ILOSC='1'                 STRONA=KOLOR_WEWN  >
      ELEMENT[N]=< KOD=E_ALP_NVF_PAS_3835_03        NR_PRZEKROJU=517 ILOSC='1*NVF_PODOVGUVACH' STRONA=KOLOR_WEWN  >
      ELEMENT[N]=< KOD=E_ALP_NVF_Zakl_5_10_DIN7337  NR_PRZEKROJU=517 ILOSC='2'                 STRONA=KOLOR_WEWN  >
      ELEMENT[N]=< KOD=E_ALP_NVF_Zakl_5_10_DIN7337  NR_PRZEKROJU=517 ILOSC='2*NVF_PODOVGUVACH' STRONA=KOLOR_WEWN  >
	  
      ELEMENT[N]=< KOD=E_ALP_NVF_TERMO_140_50_5     NR_PRZEKROJU=517 ILOSC='1'                 STRONA=KOLOR_WEWN  >  
	  >	  
	  
    GRUPA[1124]=
      <
      NAZWA=     'Кронштейн ПАС-3607.03 230х45х120 / БП 0,12м [НВФ]'
      OPIS=      'Кронштейн ПАС-3607.03 230х45х120 / БП 0,12м [НВФ]'
      ZESTAW=    '{ 4. Кронштейн оновленний <b>120mm</b> <FONT COLOR="#FF0000"><FONT-SIZE="2"><b><big>(Фіксовані)</b><FONT-SIZE="1">}'

      RODZAJ=1
	  
      PARAMETRY=
	    <
        Z_LISTY=
            < KLUCZ       = 'NVF_PODOVGUVACH' 
			  PYTANIE     = 'Використовувати подовжувача до кронштейна:' 
              ELEMENT     = 'Без подовжувача'   
              ELEMENT     = 'З використаням подовжувача 100х120 (ПАС-3835.03)'   			  
              STANDARDOWO = '0'			  
		  >	  	  
		>		 
	  
	  SYSTEMY= [DEF_SYS_NVF_KERAM_KLIAM, DEF_SYS_NVF_KERAM_GLUE,DEF_SYS_NVF_AKP,DEF_SYS_NVF_HPL_PANEL,DEF_SYS_NVF_FZP]
      RYSUNEK= 'PAS_3602_03_KR.png'
      WLASNY_RYSUNEK=TAK 
					ROZMIAR_X='100'
					ROZMIAR_Y='100'	
                    RYSUNEK=   'fix_nepodv.vct'					
	  			    POLOZENIE_X='0'
					POLOZENIE_Y='0'
					WYMIARY_GRUPY
                    AKTYWNY=TAK 		

      ELEMENT[N]=< KOD=E_ALP_NVF_PAS_3607_03        NR_PRZEKROJU=517 ILOSC='1'                 STRONA=KOLOR_WEWN  >
      ELEMENT[N]=< KOD=E_ALP_NVF_PAS_3835_03        NR_PRZEKROJU=517 ILOSC='1*NVF_PODOVGUVACH' STRONA=KOLOR_WEWN  >
      ELEMENT[N]=< KOD=E_ALP_NVF_Zakl_5_10_DIN7337  NR_PRZEKROJU=517 ILOSC='2'                 STRONA=KOLOR_WEWN  >
      ELEMENT[N]=< KOD=E_ALP_NVF_Zakl_5_10_DIN7337  NR_PRZEKROJU=517 ILOSC='2*NVF_PODOVGUVACH' STRONA=KOLOR_WEWN  >
	  
      ELEMENT[N]=< KOD=E_ALP_NVF_TERMO_140_50_5     NR_PRZEKROJU=517 ILOSC='1'                 STRONA=KOLOR_WEWN  >  
	  >	   

  //***************************************	  
	  
    GRUPA[1125]=
      <
      NAZWA=     'Кронштейн ПАС-3602.04 100х45х140 / БП 0,14м [НВФ]'
      OPIS=      'Кронштейн ПАС-3602.04 100х45х140 / БП 0,14м [НВФ]'
      ZESTAW=    '{ 5. Кронштейн оновленний <b>140mm</b> <FONT COLOR="#FF0000"><FONT-SIZE="2"><b><big>(Фіксовані)</b><FONT-SIZE="1">}'

      RODZAJ=1
	  
      PARAMETRY=
	    <
        Z_LISTY=
            < KLUCZ       = 'NVF_PODOVGUVACH' 
			  PYTANIE     = 'Використовувати подовжувача до кронштейна:' 
              ELEMENT     = 'Без подовжувача'   
              ELEMENT     = 'З використаням подовжувача 100х140 (ПАС-3835.04)'   			  
              STANDARDOWO = '0'			  
		  >	  	  
		>		 
	  
	  SYSTEMY= [DEF_SYS_NVF_KERAM_KLIAM, DEF_SYS_NVF_KERAM_GLUE,DEF_SYS_NVF_AKP,DEF_SYS_NVF_HPL_PANEL,DEF_SYS_NVF_FZP]
      RYSUNEK= 'PAS_3602_04_KR.png'
      WLASNY_RYSUNEK=TAK 
					ROZMIAR_X='100'
					ROZMIAR_Y='100'	
                    RYSUNEK=   'fix_nepodv.vct'					
	  			    POLOZENIE_X='0'
					POLOZENIE_Y='0'
					WYMIARY_GRUPY
                    AKTYWNY=TAK 		

      ELEMENT[N]=< KOD=E_ALP_NVF_PAS_3602_04        NR_PRZEKROJU=517 ILOSC='1'                 STRONA=KOLOR_WEWN  >
      ELEMENT[N]=< KOD=E_ALP_NVF_PAS_3835_04        NR_PRZEKROJU=517 ILOSC='1*NVF_PODOVGUVACH' STRONA=KOLOR_WEWN  >
      ELEMENT[N]=< KOD=E_ALP_NVF_Zakl_5_10_DIN7337  NR_PRZEKROJU=517 ILOSC='2'                 STRONA=KOLOR_WEWN  >
      ELEMENT[N]=< KOD=E_ALP_NVF_Zakl_5_10_DIN7337  NR_PRZEKROJU=517 ILOSC='2*NVF_PODOVGUVACH' STRONA=KOLOR_WEWN  >
	  
      ELEMENT[N]=< KOD=E_ALP_NVF_TERMO_140_50_5     NR_PRZEKROJU=517 ILOSC='1'                 STRONA=KOLOR_WEWN  >  
	  >	  
	  
    GRUPA[1126]=
      <
      NAZWA=     'Кронштейн ПАС-3603.03 130х45х140 / БП 0,14м [НВФ]'
      OPIS=      'Кронштейн ПАС-3603.03 130х45х140 / БП 0,14м [НВФ]'
      ZESTAW=    '{ 5. Кронштейн оновленний <b>140mm</b> <FONT COLOR="#FF0000"><FONT-SIZE="2"><b><big>(Фіксовані)</b><FONT-SIZE="1">}'

      RODZAJ=1
	  
      PARAMETRY=
	    <
        Z_LISTY=
            < KLUCZ       = 'NVF_PODOVGUVACH' 
			  PYTANIE     = 'Використовувати подовжувача до кронштейна:' 
              ELEMENT     = 'Без подовжувача'   
              ELEMENT     = 'З використаням подовжувача 100х140 (ПАС-3835.04)'   			  
              STANDARDOWO = '0'			  
		  >	  	  
		>		 
	  
	  SYSTEMY= [DEF_SYS_NVF_KERAM_KLIAM, DEF_SYS_NVF_KERAM_GLUE,DEF_SYS_NVF_AKP,DEF_SYS_NVF_HPL_PANEL,DEF_SYS_NVF_FZP]
      RYSUNEK= 'PAS_3602_04_KR.png'
      WLASNY_RYSUNEK=TAK 
					ROZMIAR_X='100'
					ROZMIAR_Y='100'	
                    RYSUNEK=   'fix_nepodv.vct'					
	  			    POLOZENIE_X='0'
					POLOZENIE_Y='0'
					WYMIARY_GRUPY
                    AKTYWNY=TAK 		

      ELEMENT[N]=< KOD=E_ALP_NVF_PAS_3603_03        NR_PRZEKROJU=517 ILOSC='1'                 STRONA=KOLOR_WEWN  >
      ELEMENT[N]=< KOD=E_ALP_NVF_PAS_3835_04        NR_PRZEKROJU=517 ILOSC='1*NVF_PODOVGUVACH' STRONA=KOLOR_WEWN  >
      ELEMENT[N]=< KOD=E_ALP_NVF_Zakl_5_10_DIN7337  NR_PRZEKROJU=517 ILOSC='2'                 STRONA=KOLOR_WEWN  >
      ELEMENT[N]=< KOD=E_ALP_NVF_Zakl_5_10_DIN7337  NR_PRZEKROJU=517 ILOSC='2*NVF_PODOVGUVACH' STRONA=KOLOR_WEWN  >
	  
      ELEMENT[N]=< KOD=E_ALP_NVF_TERMO_140_50_5     NR_PRZEKROJU=517 ILOSC='1'                 STRONA=KOLOR_WEWN  >  
	  >	  
	  
    GRUPA[1127]=
      <
      NAZWA=     'Кронштейн ПАС-3604.03 150х45х140 / БП 0,14м [НВФ]'
      OPIS=      'Кронштейн ПАС-3604.03 150х45х140 / БП 0,14м [НВФ]'
      ZESTAW=    '{ 5. Кронштейн оновленний <b>140mm</b> <FONT COLOR="#FF0000"><FONT-SIZE="2"><b><big>(Фіксовані)</b><FONT-SIZE="1">}'

      RODZAJ=1
	  
      PARAMETRY=
	    <
        Z_LISTY=
            < KLUCZ       = 'NVF_PODOVGUVACH' 
			  PYTANIE     = 'Використовувати подовжувача до кронштейна:' 
              ELEMENT     = 'Без подовжувача'   
              ELEMENT     = 'З використаням подовжувача 100х140 (ПАС-3835.04)'   			  
              STANDARDOWO = '0'			  
		  >	  	  
		>		 
	  
	  SYSTEMY= [DEF_SYS_NVF_KERAM_KLIAM, DEF_SYS_NVF_KERAM_GLUE,DEF_SYS_NVF_AKP,DEF_SYS_NVF_HPL_PANEL,DEF_SYS_NVF_FZP]
      RYSUNEK= 'PAS_3602_04_KR.png'
      WLASNY_RYSUNEK=TAK 
					ROZMIAR_X='100'
					ROZMIAR_Y='100'	
                    RYSUNEK=   'fix_nepodv.vct'					
	  			    POLOZENIE_X='0'
					POLOZENIE_Y='0'
					WYMIARY_GRUPY
                    AKTYWNY=TAK 		

      ELEMENT[N]=< KOD=E_ALP_NVF_PAS_3604_03        NR_PRZEKROJU=517 ILOSC='1'                 STRONA=KOLOR_WEWN  >
      ELEMENT[N]=< KOD=E_ALP_NVF_PAS_3835_04        NR_PRZEKROJU=517 ILOSC='1*NVF_PODOVGUVACH' STRONA=KOLOR_WEWN  >
      ELEMENT[N]=< KOD=E_ALP_NVF_Zakl_5_10_DIN7337  NR_PRZEKROJU=517 ILOSC='2'                 STRONA=KOLOR_WEWN  >
      ELEMENT[N]=< KOD=E_ALP_NVF_Zakl_5_10_DIN7337  NR_PRZEKROJU=517 ILOSC='2*NVF_PODOVGUVACH' STRONA=KOLOR_WEWN  >
	  
      ELEMENT[N]=< KOD=E_ALP_NVF_TERMO_140_50_5     NR_PRZEKROJU=517 ILOSC='1'                 STRONA=KOLOR_WEWN  >  
	  >	  
	  
    GRUPA[1128]=
      <
      NAZWA=     'Кронштейн ПАС-3605.03 170х45х140 / БП 0,14м [НВФ]'
      OPIS=      'Кронштейн ПАС-3605.03 170х45х140 / БП 0,14м [НВФ]'
      ZESTAW=    '{ 5. Кронштейн оновленний <b>140mm</b> <FONT COLOR="#FF0000"><FONT-SIZE="2"><b><big>(Фіксовані)</b><FONT-SIZE="1">}'

      RODZAJ=1
	  
      PARAMETRY=
	    <
        Z_LISTY=
            < KLUCZ       = 'NVF_PODOVGUVACH' 
			  PYTANIE     = 'Використовувати подовжувача до кронштейна:' 
              ELEMENT     = 'Без подовжувача'   
              ELEMENT     = 'З використаням подовжувача 100х140 (ПАС-3835.04)'   			  
              STANDARDOWO = '0'			  
		  >	  	  
		>		 
	  
	  SYSTEMY= [DEF_SYS_NVF_KERAM_KLIAM, DEF_SYS_NVF_KERAM_GLUE,DEF_SYS_NVF_AKP,DEF_SYS_NVF_HPL_PANEL,DEF_SYS_NVF_FZP]
      RYSUNEK= 'PAS_3602_04_KR.png'
      WLASNY_RYSUNEK=TAK 
					ROZMIAR_X='100'
					ROZMIAR_Y='100'	
                    RYSUNEK=   'fix_nepodv.vct'					
	  			    POLOZENIE_X='0'
					POLOZENIE_Y='0'
					WYMIARY_GRUPY
                    AKTYWNY=TAK 		

      ELEMENT[N]=< KOD=E_ALP_NVF_PAS_3605_03        NR_PRZEKROJU=517 ILOSC='1'                 STRONA=KOLOR_WEWN  >
      ELEMENT[N]=< KOD=E_ALP_NVF_PAS_3835_04        NR_PRZEKROJU=517 ILOSC='1*NVF_PODOVGUVACH' STRONA=KOLOR_WEWN  >
      ELEMENT[N]=< KOD=E_ALP_NVF_Zakl_5_10_DIN7337  NR_PRZEKROJU=517 ILOSC='2'                 STRONA=KOLOR_WEWN  >
      ELEMENT[N]=< KOD=E_ALP_NVF_Zakl_5_10_DIN7337  NR_PRZEKROJU=517 ILOSC='2*NVF_PODOVGUVACH' STRONA=KOLOR_WEWN  >
	  
      ELEMENT[N]=< KOD=E_ALP_NVF_TERMO_140_50_5     NR_PRZEKROJU=517 ILOSC='1'                 STRONA=KOLOR_WEWN  >  
	  >	  
	  
    GRUPA[1129]=
      <
      NAZWA=     'Кронштейн ПАС-3606.04 200х45х140 / БП 0,14м [НВФ]'
      OPIS=      'Кронштейн ПАС-3606.04 200х45х140 / БП 0,14м [НВФ]'
      ZESTAW=    '{ 5. Кронштейн оновленний <b>140mm</b> <FONT COLOR="#FF0000"><FONT-SIZE="2"><b><big>(Фіксовані)</b><FONT-SIZE="1">}'

      RODZAJ=1
	  
      PARAMETRY=
	    <
        Z_LISTY=
            < KLUCZ       = 'NVF_PODOVGUVACH' 
			  PYTANIE     = 'Використовувати подовжувача до кронштейна:' 
              ELEMENT     = 'Без подовжувача'   
              ELEMENT     = 'З використаням подовжувача 100х140 (ПАС-3835.04)'   			  
              STANDARDOWO = '0'			  
		  >	  	  
		>		 
	  
	  SYSTEMY= [DEF_SYS_NVF_KERAM_KLIAM, DEF_SYS_NVF_KERAM_GLUE,DEF_SYS_NVF_AKP,DEF_SYS_NVF_HPL_PANEL,DEF_SYS_NVF_FZP]
      RYSUNEK= 'PAS_3602_04_KR.png'
      WLASNY_RYSUNEK=TAK 
					ROZMIAR_X='100'
					ROZMIAR_Y='100'	
                    RYSUNEK=   'fix_nepodv.vct'					
	  			    POLOZENIE_X='0'
					POLOZENIE_Y='0'
					WYMIARY_GRUPY
                    AKTYWNY=TAK 		

      ELEMENT[N]=< KOD=E_ALP_NVF_PAS_3606_04        NR_PRZEKROJU=517 ILOSC='1'                 STRONA=KOLOR_WEWN  >
      ELEMENT[N]=< KOD=E_ALP_NVF_PAS_3835_04        NR_PRZEKROJU=517 ILOSC='1*NVF_PODOVGUVACH' STRONA=KOLOR_WEWN  >
      ELEMENT[N]=< KOD=E_ALP_NVF_Zakl_5_10_DIN7337  NR_PRZEKROJU=517 ILOSC='2'                 STRONA=KOLOR_WEWN  >
      ELEMENT[N]=< KOD=E_ALP_NVF_Zakl_5_10_DIN7337  NR_PRZEKROJU=517 ILOSC='2*NVF_PODOVGUVACH' STRONA=KOLOR_WEWN  >
	  
      ELEMENT[N]=< KOD=E_ALP_NVF_TERMO_140_50_5     NR_PRZEKROJU=517 ILOSC='1'                 STRONA=KOLOR_WEWN  >  
	  >	  
	  
    GRUPA[1130]=
      <
      NAZWA=     'Кронштейн ПАС-3607.04 230х45х140 / БП 0,14м [НВФ]'
      OPIS=      'Кронштейн ПАС-3607.04 230х45х140 / БП 0,14м [НВФ]'
      ZESTAW=    '{ 5. Кронштейн оновленний <b>140mm</b> <FONT COLOR="#FF0000"><FONT-SIZE="2"><b><big>(Фіксовані)</b><FONT-SIZE="1">}'

      RODZAJ=1
	  
      PARAMETRY=
	    <
        Z_LISTY=
            < KLUCZ       = 'NVF_PODOVGUVACH' 
			  PYTANIE     = 'Використовувати подовжувача до кронштейна:' 
              ELEMENT     = 'Без подовжувача'   
              ELEMENT     = 'З використаням подовжувача 100х140 (ПАС-3835.04)'   			  
              STANDARDOWO = '0'			  
		  >	  	  
		>		 
	  
	  SYSTEMY= [DEF_SYS_NVF_KERAM_KLIAM, DEF_SYS_NVF_KERAM_GLUE,DEF_SYS_NVF_AKP,DEF_SYS_NVF_HPL_PANEL,DEF_SYS_NVF_FZP]
      RYSUNEK= 'PAS_3602_04_KR.png'
      WLASNY_RYSUNEK=TAK 
					ROZMIAR_X='100'
					ROZMIAR_Y='100'	
                    RYSUNEK=   'fix_nepodv.vct'					
	  			    POLOZENIE_X='0'
					POLOZENIE_Y='0'
					WYMIARY_GRUPY
                    AKTYWNY=TAK 		

      ELEMENT[N]=< KOD=E_ALP_NVF_PAS_3607_04        NR_PRZEKROJU=517 ILOSC='1'                 STRONA=KOLOR_WEWN  >
      ELEMENT[N]=< KOD=E_ALP_NVF_PAS_3835_04        NR_PRZEKROJU=517 ILOSC='1*NVF_PODOVGUVACH' STRONA=KOLOR_WEWN  >
      ELEMENT[N]=< KOD=E_ALP_NVF_Zakl_5_10_DIN7337  NR_PRZEKROJU=517 ILOSC='2'                 STRONA=KOLOR_WEWN  >
      ELEMENT[N]=< KOD=E_ALP_NVF_Zakl_5_10_DIN7337  NR_PRZEKROJU=517 ILOSC='2*NVF_PODOVGUVACH' STRONA=KOLOR_WEWN  >
	  
      ELEMENT[N]=< KOD=E_ALP_NVF_TERMO_140_50_5     NR_PRZEKROJU=517 ILOSC='1'                 STRONA=KOLOR_WEWN  >  
	  >	  

  //***************************************	  
	  
    GRUPA[1131]=
      <
      NAZWA=     'Кронштейн 3117.02 80х40х60 / БП 0,06м [НВФ]'
      OPIS=      'Кронштейн 3117.02 80х40х60 / БП 0,06м [НВФ]'
      ZESTAW=    '{ 6. Кронштейн класичні <b>60mm</b> <FONT COLOR="#0000FF"><FONT-SIZE="2"><b><big>(Рухомий)</b><FONT-SIZE="1">}'

      RODZAJ=1
	  
      PARAMETRY=
	    <
        Z_LISTY=
            < KLUCZ       = 'NVF_PODOVGUVACH' 
			  PYTANIE     = 'Використовувати подовжувача до кронштейна:' 
              ELEMENT     = 'Без подовжувача'   
              ELEMENT     = 'З використаням подовжувача 100х60 (ПАС-3836.01)'   			  
              STANDARDOWO = '0'			  
		  >	  	  
		>		 
	  
	  SYSTEMY= [DEF_SYS_NVF_KERAM_KLIAM, DEF_SYS_NVF_KERAM_GLUE,DEF_SYS_NVF_AKP,DEF_SYS_NVF_HPL_PANEL,DEF_SYS_NVF_FZP]
      RYSUNEK= '3117_02_KR.png'
      WLASNY_RYSUNEK=TAK 
					ROZMIAR_X='100'
					ROZMIAR_Y='100'	
                    RYSUNEK=   'fix_podv1.vct'					
	  			    POLOZENIE_X='0'
					POLOZENIE_Y='0'
					WYMIARY_GRUPY
                    AKTYWNY=TAK 		

      ELEMENT[N]=< KOD=E_ALP_NVF_3117_02            NR_PRZEKROJU=517 ILOSC='1'                 STRONA=KOLOR_WEWN  >
      ELEMENT[N]=< KOD=E_ALP_NVF_PAS_3836_01        NR_PRZEKROJU=517 ILOSC='1*NVF_PODOVGUVACH' STRONA=KOLOR_WEWN  >
      ELEMENT[N]=< KOD=E_ALP_NVF_Zakl_5_10_DIN7337  NR_PRZEKROJU=517 ILOSC='2'                 STRONA=KOLOR_WEWN  >
      ELEMENT[N]=< KOD=E_ALP_NVF_Zakl_5_10_DIN7337  NR_PRZEKROJU=517 ILOSC='2*NVF_PODOVGUVACH' STRONA=KOLOR_WEWN  >
	  
      ELEMENT[N]=< KOD=E_ALP_NVF_TERMO_70_50_5      NR_PRZEKROJU=517 ILOSC='1'                 STRONA=KOLOR_WEWN  >  
	  >	  
	  
    GRUPA[1132]=
      <
      NAZWA=     'Кронштейн 3179.01 100х40х60 / БП 0,06м [НВФ]'
      OPIS=      'Кронштейн 3179.01 100х40х60 / БП 0,06м [НВФ]'
      ZESTAW=    '{ 6. Кронштейн класичні <b>60mm</b> <FONT COLOR="#0000FF"><FONT-SIZE="2"><b><big>(Рухомий)</b><FONT-SIZE="1">}'

      RODZAJ=1
	  
      PARAMETRY=
	    <
        Z_LISTY=
            < KLUCZ       = 'NVF_PODOVGUVACH' 
			  PYTANIE     = 'Використовувати подовжувача до кронштейна:' 
              ELEMENT     = 'Без подовжувача'   
              ELEMENT     = 'З використаням подовжувача 100х60 (ПАС-3836.01)'   			  
              STANDARDOWO = '0'			  
		  >	  	  
		>		 
	  
	  SYSTEMY= [DEF_SYS_NVF_KERAM_KLIAM, DEF_SYS_NVF_KERAM_GLUE,DEF_SYS_NVF_AKP,DEF_SYS_NVF_HPL_PANEL,DEF_SYS_NVF_FZP]
      RYSUNEK= '3117_02_KR.png'
      WLASNY_RYSUNEK=TAK 
					ROZMIAR_X='100'
					ROZMIAR_Y='100'	
                    RYSUNEK=   'fix_podv1.vct'					
	  			    POLOZENIE_X='0'
					POLOZENIE_Y='0'
					WYMIARY_GRUPY
                    AKTYWNY=TAK 		

      ELEMENT[N]=< KOD=E_ALP_NVF_3179_01            NR_PRZEKROJU=517 ILOSC='1'                 STRONA=KOLOR_WEWN  >
      ELEMENT[N]=< KOD=E_ALP_NVF_PAS_3836_01        NR_PRZEKROJU=517 ILOSC='1*NVF_PODOVGUVACH' STRONA=KOLOR_WEWN  >
      ELEMENT[N]=< KOD=E_ALP_NVF_Zakl_5_10_DIN7337  NR_PRZEKROJU=517 ILOSC='2'                 STRONA=KOLOR_WEWN  >
      ELEMENT[N]=< KOD=E_ALP_NVF_Zakl_5_10_DIN7337  NR_PRZEKROJU=517 ILOSC='2*NVF_PODOVGUVACH' STRONA=KOLOR_WEWN  >
	  
      ELEMENT[N]=< KOD=E_ALP_NVF_TERMO_70_50_5      NR_PRZEKROJU=517 ILOSC='1'                 STRONA=KOLOR_WEWN  >  
	  >	  
	  
    GRUPA[1133]=
      <
      NAZWA=     'Кронштейн 3118.01 120х40х60 / БП 0,06м [НВФ]'
      OPIS=      'Кронштейн 3118.01 120х40х60 / БП 0,06м [НВФ]'
      ZESTAW=    '{ 6. Кронштейн класичні <b>60mm</b> <FONT COLOR="#0000FF"><FONT-SIZE="2"><b><big>(Рухомий)</b><FONT-SIZE="1">}'

      RODZAJ=1
	  
      PARAMETRY=
	    <
        Z_LISTY=
            < KLUCZ       = 'NVF_PODOVGUVACH' 
			  PYTANIE     = 'Використовувати подовжувача до кронштейна:' 
              ELEMENT     = 'Без подовжувача'   
              ELEMENT     = 'З використаням подовжувача 100х60 (ПАС-3836.01)'   			  
              STANDARDOWO = '0'			  
		  >	  	  
		>		 
	  
	  SYSTEMY= [DEF_SYS_NVF_KERAM_KLIAM, DEF_SYS_NVF_KERAM_GLUE,DEF_SYS_NVF_AKP,DEF_SYS_NVF_HPL_PANEL,DEF_SYS_NVF_FZP]
      RYSUNEK= '3117_02_KR.png'
      WLASNY_RYSUNEK=TAK 
					ROZMIAR_X='100'
					ROZMIAR_Y='100'	
                    RYSUNEK=   'fix_podv1.vct'					
	  			    POLOZENIE_X='0'
					POLOZENIE_Y='0'
					WYMIARY_GRUPY
                    AKTYWNY=TAK 		

      ELEMENT[N]=< KOD=E_ALP_NVF_3118_01            NR_PRZEKROJU=517 ILOSC='1'                 STRONA=KOLOR_WEWN  >
      ELEMENT[N]=< KOD=E_ALP_NVF_PAS_3836_01        NR_PRZEKROJU=517 ILOSC='1*NVF_PODOVGUVACH' STRONA=KOLOR_WEWN  >
      ELEMENT[N]=< KOD=E_ALP_NVF_Zakl_5_10_DIN7337  NR_PRZEKROJU=517 ILOSC='2'                 STRONA=KOLOR_WEWN  >
      ELEMENT[N]=< KOD=E_ALP_NVF_Zakl_5_10_DIN7337  NR_PRZEKROJU=517 ILOSC='2*NVF_PODOVGUVACH' STRONA=KOLOR_WEWN  >
	  
      ELEMENT[N]=< KOD=E_ALP_NVF_TERMO_70_50_5      NR_PRZEKROJU=517 ILOSC='1'                 STRONA=KOLOR_WEWN  >  
	  >	  
	  
    GRUPA[1134]=
      <
      NAZWA=     'Кронштейн ПАС-3546.01 140х40х60 / БП 0,06м [НВФ]'
      OPIS=      'Кронштейн ПАС-3546.01 140х40х60 / БП 0,06м [НВФ]'
      ZESTAW=    '{ 6. Кронштейн класичні <b>60mm</b> <FONT COLOR="#0000FF"><FONT-SIZE="2"><b><big>(Рухомий)</b><FONT-SIZE="1">}'

      RODZAJ=1
	  
      PARAMETRY=
	    <
        Z_LISTY=
            < KLUCZ       = 'NVF_PODOVGUVACH' 
			  PYTANIE     = 'Використовувати подовжувача до кронштейна:' 
              ELEMENT     = 'Без подовжувача'   
              ELEMENT     = 'З використаням подовжувача 100х60 (ПАС-3836.01)'   			  
              STANDARDOWO = '0'			  
		  >	  	  
		>		 
	  
	  SYSTEMY= [DEF_SYS_NVF_KERAM_KLIAM, DEF_SYS_NVF_KERAM_GLUE,DEF_SYS_NVF_AKP,DEF_SYS_NVF_HPL_PANEL,DEF_SYS_NVF_FZP]
      RYSUNEK= '3117_02_KR.png'
      WLASNY_RYSUNEK=TAK 
					ROZMIAR_X='100'
					ROZMIAR_Y='100'	
                    RYSUNEK=   'fix_podv1.vct'					
	  			    POLOZENIE_X='0'
					POLOZENIE_Y='0'
					WYMIARY_GRUPY
                    AKTYWNY=TAK 		

      ELEMENT[N]=< KOD=E_ALP_NVF_PAS_3546_01        NR_PRZEKROJU=517 ILOSC='1'                 STRONA=KOLOR_WEWN  >
      ELEMENT[N]=< KOD=E_ALP_NVF_PAS_3836_01        NR_PRZEKROJU=517 ILOSC='1*NVF_PODOVGUVACH' STRONA=KOLOR_WEWN  >
      ELEMENT[N]=< KOD=E_ALP_NVF_Zakl_5_10_DIN7337  NR_PRZEKROJU=517 ILOSC='2'                 STRONA=KOLOR_WEWN  >
      ELEMENT[N]=< KOD=E_ALP_NVF_Zakl_5_10_DIN7337  NR_PRZEKROJU=517 ILOSC='2*NVF_PODOVGUVACH' STRONA=KOLOR_WEWN  >
	  
      ELEMENT[N]=< KOD=E_ALP_NVF_TERMO_70_50_5      NR_PRZEKROJU=517 ILOSC='1'                 STRONA=KOLOR_WEWN  >  
	  >	  
	  
    GRUPA[1135]=
      <
      NAZWA=     'Кронштейн ПАС-3547.01 160х40х60 / БП 0,06м [НВФ]'
      OPIS=      'Кронштейн ПАС-3547.01 160х40х60 / БП 0,06м [НВФ]'
      ZESTAW=    '{ 6. Кронштейн класичні <b>60mm</b> <FONT COLOR="#0000FF"><FONT-SIZE="2"><b><big>(Рухомий)</b><FONT-SIZE="1">}'

      RODZAJ=1
	  
      PARAMETRY=
	    <
        Z_LISTY=
            < KLUCZ       = 'NVF_PODOVGUVACH' 
			  PYTANIE     = 'Використовувати подовжувача до кронштейна:' 
              ELEMENT     = 'Без подовжувача'   
              ELEMENT     = 'З використаням подовжувача 100х60 (ПАС-3836.01)'   			  
              STANDARDOWO = '0'			  
		  >	  	  
		>		 
	  
	  SYSTEMY= [DEF_SYS_NVF_KERAM_KLIAM, DEF_SYS_NVF_KERAM_GLUE,DEF_SYS_NVF_AKP,DEF_SYS_NVF_HPL_PANEL,DEF_SYS_NVF_FZP]
      RYSUNEK= '3117_02_KR.png'
      WLASNY_RYSUNEK=TAK 
					ROZMIAR_X='100'
					ROZMIAR_Y='100'	
                    RYSUNEK=   'fix_podv1.vct'					
	  			    POLOZENIE_X='0'
					POLOZENIE_Y='0'
					WYMIARY_GRUPY
                    AKTYWNY=TAK 		

      ELEMENT[N]=< KOD=E_ALP_NVF_PAS_3547_01        NR_PRZEKROJU=517 ILOSC='1'                 STRONA=KOLOR_WEWN  >
      ELEMENT[N]=< KOD=E_ALP_NVF_PAS_3836_01        NR_PRZEKROJU=517 ILOSC='1*NVF_PODOVGUVACH' STRONA=KOLOR_WEWN  >
      ELEMENT[N]=< KOD=E_ALP_NVF_Zakl_5_10_DIN7337  NR_PRZEKROJU=517 ILOSC='2'                 STRONA=KOLOR_WEWN  >
      ELEMENT[N]=< KOD=E_ALP_NVF_Zakl_5_10_DIN7337  NR_PRZEKROJU=517 ILOSC='2*NVF_PODOVGUVACH' STRONA=KOLOR_WEWN  >
	  
      ELEMENT[N]=< KOD=E_ALP_NVF_TERMO_70_50_5      NR_PRZEKROJU=517 ILOSC='1'                 STRONA=KOLOR_WEWN  >  
	  >	  
	  
    GRUPA[1136]=
      <
      NAZWA=     'Кронштейн 3379.01 180х40х60 / БП 0,06м [НВФ]'
      OPIS=      'Кронштейн 3379.01 180х40х60 / БП 0,06м [НВФ]'
      ZESTAW=    '{ 6. Кронштейн класичні <b>60mm</b> <FONT COLOR="#0000FF"><FONT-SIZE="2"><b><big>(Рухомий)</b><FONT-SIZE="1">}'

      RODZAJ=1
	  
      PARAMETRY=
	    <
        Z_LISTY=
            < KLUCZ       = 'NVF_PODOVGUVACH' 
			  PYTANIE     = 'Використовувати подовжувача до кронштейна:' 
              ELEMENT     = 'Без подовжувача'   
              ELEMENT     = 'З використаням подовжувача 100х60 (ПАС-3836.01)'   			  
              STANDARDOWO = '0'			  
		  >	  	  
		>		 
	  
	  SYSTEMY= [DEF_SYS_NVF_KERAM_KLIAM, DEF_SYS_NVF_KERAM_GLUE,DEF_SYS_NVF_AKP,DEF_SYS_NVF_HPL_PANEL,DEF_SYS_NVF_FZP]
      RYSUNEK= '3117_02_KR.png'
      WLASNY_RYSUNEK=TAK 
					ROZMIAR_X='100'
					ROZMIAR_Y='100'	
                    RYSUNEK=   'fix_podv1.vct'					
	  			    POLOZENIE_X='0'
					POLOZENIE_Y='0'
					WYMIARY_GRUPY
                    AKTYWNY=TAK 		

      ELEMENT[N]=< KOD=E_ALP_NVF_3379_01            NR_PRZEKROJU=517 ILOSC='1'                 STRONA=KOLOR_WEWN  >
      ELEMENT[N]=< KOD=E_ALP_NVF_PAS_3836_01        NR_PRZEKROJU=517 ILOSC='1*NVF_PODOVGUVACH' STRONA=KOLOR_WEWN  >
      ELEMENT[N]=< KOD=E_ALP_NVF_Zakl_5_10_DIN7337  NR_PRZEKROJU=517 ILOSC='2'                 STRONA=KOLOR_WEWN  >
      ELEMENT[N]=< KOD=E_ALP_NVF_Zakl_5_10_DIN7337  NR_PRZEKROJU=517 ILOSC='2*NVF_PODOVGUVACH' STRONA=KOLOR_WEWN  >
	  
      ELEMENT[N]=< KOD=E_ALP_NVF_TERMO_70_50_5      NR_PRZEKROJU=517 ILOSC='1'                 STRONA=KOLOR_WEWN  >  
	  >	  
	  
    GRUPA[1137]=
      <
      NAZWA=     'Кронштейн ПАС-3668.01 210х40х60 / БП 0,06м [НВФ]'
      OPIS=      'Кронштейн ПАС-3668.01 210х40х60 / БП 0,06м [НВФ]'
      ZESTAW=    '{ 6. Кронштейн класичні <b>60mm</b> <FONT COLOR="#0000FF"><FONT-SIZE="2"><b><big>(Рухомий)</b><FONT-SIZE="1">}'

      RODZAJ=1
	  
      PARAMETRY=
	    <
        Z_LISTY=
            < KLUCZ       = 'NVF_PODOVGUVACH' 
			  PYTANIE     = 'Використовувати подовжувача до кронштейна:' 
              ELEMENT     = 'Без подовжувача'   
              ELEMENT     = 'З використаням подовжувача 100х60 (ПАС-3836.01)'   			  
              STANDARDOWO = '0'			  
		  >	  	  
		>		 
	  
	  SYSTEMY= [DEF_SYS_NVF_KERAM_KLIAM, DEF_SYS_NVF_KERAM_GLUE,DEF_SYS_NVF_AKP,DEF_SYS_NVF_HPL_PANEL,DEF_SYS_NVF_FZP]
      RYSUNEK= '3117_02_KR.png'
      WLASNY_RYSUNEK=TAK 
					ROZMIAR_X='100'
					ROZMIAR_Y='100'	
                    RYSUNEK=   'fix_podv1.vct'					
	  			    POLOZENIE_X='0'
					POLOZENIE_Y='0'
					WYMIARY_GRUPY
                    AKTYWNY=TAK 		

      ELEMENT[N]=< KOD=E_ALP_NVF_PAS_3668_01        NR_PRZEKROJU=517 ILOSC='1'                 STRONA=KOLOR_WEWN  >
      ELEMENT[N]=< KOD=E_ALP_NVF_PAS_3836_01        NR_PRZEKROJU=517 ILOSC='1*NVF_PODOVGUVACH' STRONA=KOLOR_WEWN  >
      ELEMENT[N]=< KOD=E_ALP_NVF_Zakl_5_10_DIN7337  NR_PRZEKROJU=517 ILOSC='2'                 STRONA=KOLOR_WEWN  >
      ELEMENT[N]=< KOD=E_ALP_NVF_Zakl_5_10_DIN7337  NR_PRZEKROJU=517 ILOSC='2*NVF_PODOVGUVACH' STRONA=KOLOR_WEWN  >
	  
      ELEMENT[N]=< KOD=E_ALP_NVF_TERMO_70_50_5      NR_PRZEKROJU=517 ILOSC='1'                 STRONA=KOLOR_WEWN  >  
	  >	  
	  
    GRUPA[1138]=
      <
      NAZWA=     'Кронштейн ПАС-3705.01 230х40х60 / БП 0,06м [НВФ]'
      OPIS=      'Кронштейн ПАС-3705.01 230х40х60 / БП 0,06м [НВФ]'
      ZESTAW=    '{ 6. Кронштейн класичні <b>60mm</b> <FONT COLOR="#0000FF"><FONT-SIZE="2"><b><big>(Рухомий)</b><FONT-SIZE="1">}'

      RODZAJ=1
	  
      PARAMETRY=
	    <
        Z_LISTY=
            < KLUCZ       = 'NVF_PODOVGUVACH' 
			  PYTANIE     = 'Використовувати подовжувача до кронштейна:' 
              ELEMENT     = 'Без подовжувача'   
              ELEMENT     = 'З використаням подовжувача 100х60 (ПАС-3836.01)'   			  
              STANDARDOWO = '0'			  
		  >	  	  
		>		 
	  
	  SYSTEMY= [DEF_SYS_NVF_KERAM_KLIAM, DEF_SYS_NVF_KERAM_GLUE,DEF_SYS_NVF_AKP,DEF_SYS_NVF_HPL_PANEL,DEF_SYS_NVF_FZP]
      RYSUNEK= '3117_02_KR.png'
      WLASNY_RYSUNEK=TAK 
					ROZMIAR_X='100'
					ROZMIAR_Y='100'	
                    RYSUNEK=   'fix_podv1.vct'					
	  			    POLOZENIE_X='0'
					POLOZENIE_Y='0'
					WYMIARY_GRUPY
                    AKTYWNY=TAK 		

      ELEMENT[N]=< KOD=E_ALP_NVF_PAS_3705_01        NR_PRZEKROJU=517 ILOSC='1'                 STRONA=KOLOR_WEWN  >
      ELEMENT[N]=< KOD=E_ALP_NVF_PAS_3836_01        NR_PRZEKROJU=517 ILOSC='1*NVF_PODOVGUVACH' STRONA=KOLOR_WEWN  >
      ELEMENT[N]=< KOD=E_ALP_NVF_Zakl_5_10_DIN7337  NR_PRZEKROJU=517 ILOSC='2'                 STRONA=KOLOR_WEWN  >
      ELEMENT[N]=< KOD=E_ALP_NVF_Zakl_5_10_DIN7337  NR_PRZEKROJU=517 ILOSC='2*NVF_PODOVGUVACH' STRONA=KOLOR_WEWN  >
	  
      ELEMENT[N]=< KOD=E_ALP_NVF_TERMO_70_50_5      NR_PRZEKROJU=517 ILOSC='1'                 STRONA=KOLOR_WEWN  >  
	  >	  

  //***************************************	  
	  
    GRUPA[1139]=
      <
      NAZWA=     'Кронштейн 3117.01 80х40х90 / БП 0,09м [НВФ]'
      OPIS=      'Кронштейн 3117.01 80х40х90 / БП 0,09м [НВФ]'
      ZESTAW=    '{ 7. Кронштейн класичні <b>90mm</b> <FONT COLOR="#0000FF"><FONT-SIZE="2"><b><big>(Рухомий)</b><FONT-SIZE="1">}'

      RODZAJ=1
	  
      PARAMETRY=
	    <
        Z_LISTY=
            < KLUCZ       = 'NVF_PODOVGUVACH' 
			  PYTANIE     = 'Використовувати подовжувача до кронштейна:' 
              ELEMENT     = 'Без подовжувача'   
              ELEMENT     = 'З використаням подовжувача 100х90 (ПАС-3836.02)'   			  
              STANDARDOWO = '0'			  
		  >	  	  
		>		 
	  
	  SYSTEMY= [DEF_SYS_NVF_KERAM_KLIAM, DEF_SYS_NVF_KERAM_GLUE,DEF_SYS_NVF_AKP,DEF_SYS_NVF_HPL_PANEL,DEF_SYS_NVF_FZP]
      RYSUNEK= '3117_01_KR.png'
      WLASNY_RYSUNEK=TAK 
					ROZMIAR_X='100'
					ROZMIAR_Y='100'	
                    RYSUNEK=   'fix_podv1.vct'					
	  			    POLOZENIE_X='0'
					POLOZENIE_Y='0'
					WYMIARY_GRUPY
                    AKTYWNY=TAK 		

      ELEMENT[N]=< KOD=E_ALP_NVF_3117_01            NR_PRZEKROJU=517 ILOSC='1'                 STRONA=KOLOR_WEWN  >
      ELEMENT[N]=< KOD=E_ALP_NVF_PAS_3836_02        NR_PRZEKROJU=517 ILOSC='1*NVF_PODOVGUVACH' STRONA=KOLOR_WEWN  >
      ELEMENT[N]=< KOD=E_ALP_NVF_Zakl_5_10_DIN7337  NR_PRZEKROJU=517 ILOSC='2'                 STRONA=KOLOR_WEWN  >
      ELEMENT[N]=< KOD=E_ALP_NVF_Zakl_5_10_DIN7337  NR_PRZEKROJU=517 ILOSC='2*NVF_PODOVGUVACH' STRONA=KOLOR_WEWN  >
	  
      ELEMENT[N]=< KOD=E_ALP_NVF_TERMO_70_50_5      NR_PRZEKROJU=517 ILOSC='1'                 STRONA=KOLOR_WEWN  >  
	  >	  
	  
    GRUPA[1140]=
      <
      NAZWA=     'Кронштейн 3179.02 100х40х90 / БП 0,06м [НВФ]'
      OPIS=      'Кронштейн 3179.02 100х40х90 / БП 0,06м [НВФ]'
      ZESTAW=    '{ 7. Кронштейн класичні <b>90mm</b> <FONT COLOR="#0000FF"><FONT-SIZE="2"><b><big>(Рухомий)</b><FONT-SIZE="1">}'

      RODZAJ=1
	  
      PARAMETRY=
	    <
        Z_LISTY=
            < KLUCZ       = 'NVF_PODOVGUVACH' 
			  PYTANIE     = 'Використовувати подовжувача до кронштейна:' 
              ELEMENT     = 'Без подовжувача'   
              ELEMENT     = 'З використаням подовжувача 100х90 (ПАС-3836.02)'   			  
              STANDARDOWO = '0'			  
		  >	  	  
		>		 
	  
	  SYSTEMY= [DEF_SYS_NVF_KERAM_KLIAM, DEF_SYS_NVF_KERAM_GLUE,DEF_SYS_NVF_AKP,DEF_SYS_NVF_HPL_PANEL,DEF_SYS_NVF_FZP]
      RYSUNEK= '3117_01_KR.png'
      WLASNY_RYSUNEK=TAK 
					ROZMIAR_X='100'
					ROZMIAR_Y='100'	
                    RYSUNEK=   'fix_podv1.vct'					
	  			    POLOZENIE_X='0'
					POLOZENIE_Y='0'
					WYMIARY_GRUPY
                    AKTYWNY=TAK 		

      ELEMENT[N]=< KOD=E_ALP_NVF_3179_02            NR_PRZEKROJU=517 ILOSC='1'                 STRONA=KOLOR_WEWN  >
      ELEMENT[N]=< KOD=E_ALP_NVF_PAS_3836_02        NR_PRZEKROJU=517 ILOSC='1*NVF_PODOVGUVACH' STRONA=KOLOR_WEWN  >
      ELEMENT[N]=< KOD=E_ALP_NVF_Zakl_5_10_DIN7337  NR_PRZEKROJU=517 ILOSC='2'                 STRONA=KOLOR_WEWN  >
      ELEMENT[N]=< KOD=E_ALP_NVF_Zakl_5_10_DIN7337  NR_PRZEKROJU=517 ILOSC='2*NVF_PODOVGUVACH' STRONA=KOLOR_WEWN  >
	  
      ELEMENT[N]=< KOD=E_ALP_NVF_TERMO_70_50_5      NR_PRZEKROJU=517 ILOSC='1'                 STRONA=KOLOR_WEWN  >  
	  >	  
	  
    GRUPA[1141]=
      <
      NAZWA=     'Кронштейн 3118.02 120х40х90 / БП 0,06м [НВФ]'
      OPIS=      'Кронштейн 3118.02 120х40х90 / БП 0,06м [НВФ]'
      ZESTAW=    '{ 7. Кронштейн класичні <b>90mm</b> <FONT COLOR="#0000FF"><FONT-SIZE="2"><b><big>(Рухомий)</b><FONT-SIZE="1">}'

      RODZAJ=1
	  
      PARAMETRY=
	    <
        Z_LISTY=
            < KLUCZ       = 'NVF_PODOVGUVACH' 
			  PYTANIE     = 'Використовувати подовжувача до кронштейна:' 
              ELEMENT     = 'Без подовжувача'   
              ELEMENT     = 'З використаням подовжувача 100х90 (ПАС-3836.02)'   			  
              STANDARDOWO = '0'			  
		  >	  	  
		>		 
	  
	  SYSTEMY= [DEF_SYS_NVF_KERAM_KLIAM, DEF_SYS_NVF_KERAM_GLUE,DEF_SYS_NVF_AKP,DEF_SYS_NVF_HPL_PANEL,DEF_SYS_NVF_FZP]
      RYSUNEK= '3117_01_KR.png'
      WLASNY_RYSUNEK=TAK 
					ROZMIAR_X='100'
					ROZMIAR_Y='100'	
                    RYSUNEK=   'fix_podv1.vct'					
	  			    POLOZENIE_X='0'
					POLOZENIE_Y='0'
					WYMIARY_GRUPY
                    AKTYWNY=TAK 		

      ELEMENT[N]=< KOD=E_ALP_NVF_3118_02            NR_PRZEKROJU=517 ILOSC='1'                 STRONA=KOLOR_WEWN  >
      ELEMENT[N]=< KOD=E_ALP_NVF_PAS_3836_02        NR_PRZEKROJU=517 ILOSC='1*NVF_PODOVGUVACH' STRONA=KOLOR_WEWN  >
      ELEMENT[N]=< KOD=E_ALP_NVF_Zakl_5_10_DIN7337  NR_PRZEKROJU=517 ILOSC='2'                 STRONA=KOLOR_WEWN  >
      ELEMENT[N]=< KOD=E_ALP_NVF_Zakl_5_10_DIN7337  NR_PRZEKROJU=517 ILOSC='2*NVF_PODOVGUVACH' STRONA=KOLOR_WEWN  >
	  
      ELEMENT[N]=< KOD=E_ALP_NVF_TERMO_70_50_5      NR_PRZEKROJU=517 ILOSC='1'                 STRONA=KOLOR_WEWN  >  
	  >	  
	  
    GRUPA[1142]=
      <
      NAZWA=     'Кронштейн ПАС-3546.02 140х40х90 / БП 0,06м [НВФ]'
      OPIS=      'Кронштейн ПАС-3546.02 140х40х90 / БП 0,06м [НВФ]'
      ZESTAW=    '{ 7. Кронштейн класичні <b>90mm</b> <FONT COLOR="#0000FF"><FONT-SIZE="2"><b><big>(Рухомий)</b><FONT-SIZE="1">}'

      RODZAJ=1
	  
      PARAMETRY=
	    <
        Z_LISTY=
            < KLUCZ       = 'NVF_PODOVGUVACH' 
			  PYTANIE     = 'Використовувати подовжувача до кронштейна:' 
              ELEMENT     = 'Без подовжувача'   
              ELEMENT     = 'З використаням подовжувача 100х90 (ПАС-3836.02)'   			  
              STANDARDOWO = '0'			  
		  >	  	  
		>		 
	  
	  SYSTEMY= [DEF_SYS_NVF_KERAM_KLIAM, DEF_SYS_NVF_KERAM_GLUE,DEF_SYS_NVF_AKP,DEF_SYS_NVF_HPL_PANEL,DEF_SYS_NVF_FZP]
      RYSUNEK= '3117_01_KR.png'
      WLASNY_RYSUNEK=TAK 
					ROZMIAR_X='100'
					ROZMIAR_Y='100'	
                    RYSUNEK=   'fix_podv1.vct'					
	  			    POLOZENIE_X='0'
					POLOZENIE_Y='0'
					WYMIARY_GRUPY
                    AKTYWNY=TAK 		

      ELEMENT[N]=< KOD=E_ALP_NVF_PAS_3546_02            NR_PRZEKROJU=517 ILOSC='1'                 STRONA=KOLOR_WEWN  >
      ELEMENT[N]=< KOD=E_ALP_NVF_PAS_3836_02        NR_PRZEKROJU=517 ILOSC='1*NVF_PODOVGUVACH' STRONA=KOLOR_WEWN  >
      ELEMENT[N]=< KOD=E_ALP_NVF_Zakl_5_10_DIN7337  NR_PRZEKROJU=517 ILOSC='2'                 STRONA=KOLOR_WEWN  >
      ELEMENT[N]=< KOD=E_ALP_NVF_Zakl_5_10_DIN7337  NR_PRZEKROJU=517 ILOSC='2*NVF_PODOVGUVACH' STRONA=KOLOR_WEWN  >
	  
      ELEMENT[N]=< KOD=E_ALP_NVF_TERMO_70_50_5      NR_PRZEKROJU=517 ILOSC='1'                 STRONA=KOLOR_WEWN  >  
	  >	  
	  
    GRUPA[1143]=
      <
      NAZWA=     'Кронштейн ПАС-3546.02 140х40х90 / БП 0,06м [НВФ]'
      OPIS=      'Кронштейн ПАС-3546.02 140х40х90 / БП 0,06м [НВФ]'
      ZESTAW=    '{ 7. Кронштейн класичні <b>90mm</b> <FONT COLOR="#0000FF"><FONT-SIZE="2"><b><big>(Рухомий)</b><FONT-SIZE="1">}'

      RODZAJ=1
	  
      PARAMETRY=
	    <
        Z_LISTY=
            < KLUCZ       = 'NVF_PODOVGUVACH' 
			  PYTANIE     = 'Використовувати подовжувача до кронштейна:' 
              ELEMENT     = 'Без подовжувача'   
              ELEMENT     = 'З використаням подовжувача 100х90 (ПАС-3836.02)'   			  
              STANDARDOWO = '0'			  
		  >	  	  
		>		 
	  
	  SYSTEMY= [DEF_SYS_NVF_KERAM_KLIAM, DEF_SYS_NVF_KERAM_GLUE,DEF_SYS_NVF_AKP,DEF_SYS_NVF_HPL_PANEL,DEF_SYS_NVF_FZP]
      RYSUNEK= '3117_01_KR.png'
      WLASNY_RYSUNEK=TAK 
					ROZMIAR_X='100'
					ROZMIAR_Y='100'	
                    RYSUNEK=   'fix_podv1.vct'					
	  			    POLOZENIE_X='0'
					POLOZENIE_Y='0'
					WYMIARY_GRUPY
                    AKTYWNY=TAK 		

      ELEMENT[N]=< KOD=E_ALP_NVF_PAS_3546_02            NR_PRZEKROJU=517 ILOSC='1'                 STRONA=KOLOR_WEWN  >
      ELEMENT[N]=< KOD=E_ALP_NVF_PAS_3836_02        NR_PRZEKROJU=517 ILOSC='1*NVF_PODOVGUVACH' STRONA=KOLOR_WEWN  >
      ELEMENT[N]=< KOD=E_ALP_NVF_Zakl_5_10_DIN7337  NR_PRZEKROJU=517 ILOSC='2'                 STRONA=KOLOR_WEWN  >
      ELEMENT[N]=< KOD=E_ALP_NVF_Zakl_5_10_DIN7337  NR_PRZEKROJU=517 ILOSC='2*NVF_PODOVGUVACH' STRONA=KOLOR_WEWN  >
	  
      ELEMENT[N]=< KOD=E_ALP_NVF_TERMO_70_50_5      NR_PRZEKROJU=517 ILOSC='1'                 STRONA=KOLOR_WEWN  >  
	  >	  
	  
    GRUPA[1144]=
      <
      NAZWA=     'Кронштейн ПАС-3547.02 160х40х90 / БП 0,06м [НВФ]'
      OPIS=      'Кронштейн ПАС-3547.02 160х40х90 / БП 0,06м [НВФ]'
      ZESTAW=    '{ 7. Кронштейн класичні <b>90mm</b> <FONT COLOR="#0000FF"><FONT-SIZE="2"><b><big>(Рухомий)</b><FONT-SIZE="1">}'

      RODZAJ=1
	  
      PARAMETRY=
	    <
        Z_LISTY=
            < KLUCZ       = 'NVF_PODOVGUVACH' 
			  PYTANIE     = 'Використовувати подовжувача до кронштейна:' 
              ELEMENT     = 'Без подовжувача'   
              ELEMENT     = 'З використаням подовжувача 100х90 (ПАС-3836.02)'   			  
              STANDARDOWO = '0'			  
		  >	  	  
		>		 
	  
	  SYSTEMY= [DEF_SYS_NVF_KERAM_KLIAM, DEF_SYS_NVF_KERAM_GLUE,DEF_SYS_NVF_AKP,DEF_SYS_NVF_HPL_PANEL,DEF_SYS_NVF_FZP]
      RYSUNEK= '3117_01_KR.png'
      WLASNY_RYSUNEK=TAK 
					ROZMIAR_X='100'
					ROZMIAR_Y='100'	
                    RYSUNEK=   'fix_podv1.vct'					
	  			    POLOZENIE_X='0'
					POLOZENIE_Y='0'
					WYMIARY_GRUPY
                    AKTYWNY=TAK 		

      ELEMENT[N]=< KOD=E_ALP_NVF_PAS_3547_02            NR_PRZEKROJU=517 ILOSC='1'                 STRONA=KOLOR_WEWN  >
      ELEMENT[N]=< KOD=E_ALP_NVF_PAS_3836_02        NR_PRZEKROJU=517 ILOSC='1*NVF_PODOVGUVACH' STRONA=KOLOR_WEWN  >
      ELEMENT[N]=< KOD=E_ALP_NVF_Zakl_5_10_DIN7337  NR_PRZEKROJU=517 ILOSC='2'                 STRONA=KOLOR_WEWN  >
      ELEMENT[N]=< KOD=E_ALP_NVF_Zakl_5_10_DIN7337  NR_PRZEKROJU=517 ILOSC='2*NVF_PODOVGUVACH' STRONA=KOLOR_WEWN  >
	  
      ELEMENT[N]=< KOD=E_ALP_NVF_TERMO_70_50_5      NR_PRZEKROJU=517 ILOSC='1'                 STRONA=KOLOR_WEWN  >  
	  >	  
	  
    GRUPA[1145]=
      <
      NAZWA=     'Кронштейн 3379.02 180х40х90 / БП 0,06м [НВФ]'
      OPIS=      'Кронштейн 3379.02 180х40х90 / БП 0,06м [НВФ]'
      ZESTAW=    '{ 7. Кронштейн класичні <b>90mm</b> <FONT COLOR="#0000FF"><FONT-SIZE="2"><b><big>(Рухомий)</b><FONT-SIZE="1">}'

      RODZAJ=1
	  
      PARAMETRY=
	    <
        Z_LISTY=
            < KLUCZ       = 'NVF_PODOVGUVACH' 
			  PYTANIE     = 'Використовувати подовжувача до кронштейна:' 
              ELEMENT     = 'Без подовжувача'   
              ELEMENT     = 'З використаням подовжувача 100х90 (ПАС-3836.02)'   			  
              STANDARDOWO = '0'			  
		  >	  	  
		>		 
	  
	  SYSTEMY= [DEF_SYS_NVF_KERAM_KLIAM, DEF_SYS_NVF_KERAM_GLUE,DEF_SYS_NVF_AKP,DEF_SYS_NVF_HPL_PANEL,DEF_SYS_NVF_FZP]
      RYSUNEK= '3117_01_KR.png'
      WLASNY_RYSUNEK=TAK 
					ROZMIAR_X='100'
					ROZMIAR_Y='100'	
                    RYSUNEK=   'fix_podv1.vct'					
	  			    POLOZENIE_X='0'
					POLOZENIE_Y='0'
					WYMIARY_GRUPY
                    AKTYWNY=TAK 		

      ELEMENT[N]=< KOD=E_ALP_NVF_3379_02            NR_PRZEKROJU=517 ILOSC='1'                 STRONA=KOLOR_WEWN  >
      ELEMENT[N]=< KOD=E_ALP_NVF_PAS_3836_02        NR_PRZEKROJU=517 ILOSC='1*NVF_PODOVGUVACH' STRONA=KOLOR_WEWN  >
      ELEMENT[N]=< KOD=E_ALP_NVF_Zakl_5_10_DIN7337  NR_PRZEKROJU=517 ILOSC='2'                 STRONA=KOLOR_WEWN  >
      ELEMENT[N]=< KOD=E_ALP_NVF_Zakl_5_10_DIN7337  NR_PRZEKROJU=517 ILOSC='2*NVF_PODOVGUVACH' STRONA=KOLOR_WEWN  >
	  
      ELEMENT[N]=< KOD=E_ALP_NVF_TERMO_70_50_5      NR_PRZEKROJU=517 ILOSC='1'                 STRONA=KOLOR_WEWN  >  
	  >	  
	  
    GRUPA[1146]=
      <
      NAZWA=     'Кронштейн ПАС-3668.02 210х40х90 / БП 0,06м [НВФ]'
      OPIS=      'Кронштейн ПАС-3668.02 210х40х90 / БП 0,06м [НВФ]'
      ZESTAW=    '{ 7. Кронштейн класичні <b>90mm</b> <FONT COLOR="#0000FF"><FONT-SIZE="2"><b><big>(Рухомий)</b><FONT-SIZE="1">}'

      RODZAJ=1
	  
      PARAMETRY=
	    <
        Z_LISTY=
            < KLUCZ       = 'NVF_PODOVGUVACH' 
			  PYTANIE     = 'Використовувати подовжувача до кронштейна:' 
              ELEMENT     = 'Без подовжувача'   
              ELEMENT     = 'З використаням подовжувача 100х90 (ПАС-3836.02)'   			  
              STANDARDOWO = '0'			  
		  >	  	  
		>		 
	  
	  SYSTEMY= [DEF_SYS_NVF_KERAM_KLIAM, DEF_SYS_NVF_KERAM_GLUE,DEF_SYS_NVF_AKP,DEF_SYS_NVF_HPL_PANEL,DEF_SYS_NVF_FZP]
      RYSUNEK= '3117_01_KR.png'
      WLASNY_RYSUNEK=TAK 
					ROZMIAR_X='100'
					ROZMIAR_Y='100'	
                    RYSUNEK=   'fix_podv1.vct'					
	  			    POLOZENIE_X='0'
					POLOZENIE_Y='0'
					WYMIARY_GRUPY
                    AKTYWNY=TAK 		

      ELEMENT[N]=< KOD=E_ALP_NVF_PAS_3668_02            NR_PRZEKROJU=517 ILOSC='1'                 STRONA=KOLOR_WEWN  >
      ELEMENT[N]=< KOD=E_ALP_NVF_PAS_3836_02        NR_PRZEKROJU=517 ILOSC='1*NVF_PODOVGUVACH' STRONA=KOLOR_WEWN  >
      ELEMENT[N]=< KOD=E_ALP_NVF_Zakl_5_10_DIN7337  NR_PRZEKROJU=517 ILOSC='2'                 STRONA=KOLOR_WEWN  >
      ELEMENT[N]=< KOD=E_ALP_NVF_Zakl_5_10_DIN7337  NR_PRZEKROJU=517 ILOSC='2*NVF_PODOVGUVACH' STRONA=KOLOR_WEWN  >
	  
      ELEMENT[N]=< KOD=E_ALP_NVF_TERMO_70_50_5      NR_PRZEKROJU=517 ILOSC='1'                 STRONA=KOLOR_WEWN  >  
	  >	  
	  
    GRUPA[1147]=
      <
      NAZWA=     'Кронштейн ПАС-3705.02 230х40х90 / БП 0,06м [НВФ]'
      OPIS=      'Кронштейн ПАС-3705.02 230х40х90 / БП 0,06м [НВФ]'
      ZESTAW=    '{ 7. Кронштейн класичні <b>90mm</b> <FONT COLOR="#0000FF"><FONT-SIZE="2"><b><big>(Рухомий)</b><FONT-SIZE="1">}'

      RODZAJ=1
	  
      PARAMETRY=
	    <
        Z_LISTY=
            < KLUCZ       = 'NVF_PODOVGUVACH' 
			  PYTANIE     = 'Використовувати подовжувача до кронштейна:' 
              ELEMENT     = 'Без подовжувача'   
              ELEMENT     = 'З використаням подовжувача 100х90 (ПАС-3836.02)'   			  
              STANDARDOWO = '0'			  
		  >	  	  
		>		 
	  
	  SYSTEMY= [DEF_SYS_NVF_KERAM_KLIAM, DEF_SYS_NVF_KERAM_GLUE,DEF_SYS_NVF_AKP,DEF_SYS_NVF_HPL_PANEL,DEF_SYS_NVF_FZP]
      RYSUNEK= '3117_01_KR.png'
      WLASNY_RYSUNEK=TAK 
					ROZMIAR_X='100'
					ROZMIAR_Y='100'	
                    RYSUNEK=   'fix_podv1.vct'					
	  			    POLOZENIE_X='0'
					POLOZENIE_Y='0'
					WYMIARY_GRUPY
                    AKTYWNY=TAK 		

      ELEMENT[N]=< KOD=E_ALP_NVF_PAS_3705_02            NR_PRZEKROJU=517 ILOSC='1'                 STRONA=KOLOR_WEWN  >
      ELEMENT[N]=< KOD=E_ALP_NVF_PAS_3836_02        NR_PRZEKROJU=517 ILOSC='1*NVF_PODOVGUVACH' STRONA=KOLOR_WEWN  >
      ELEMENT[N]=< KOD=E_ALP_NVF_Zakl_5_10_DIN7337  NR_PRZEKROJU=517 ILOSC='2'                 STRONA=KOLOR_WEWN  >
      ELEMENT[N]=< KOD=E_ALP_NVF_Zakl_5_10_DIN7337  NR_PRZEKROJU=517 ILOSC='2*NVF_PODOVGUVACH' STRONA=KOLOR_WEWN  >
	  
      ELEMENT[N]=< KOD=E_ALP_NVF_TERMO_70_50_5      NR_PRZEKROJU=517 ILOSC='1'                 STRONA=KOLOR_WEWN  >  
	  >	  	  
	  
  //***************************************	  
	  
    GRUPA[1148]=
      <
      NAZWA=     'Кронштейн 3117.01 80х40х90 / БП 0,09м [НВФ]'
      OPIS=      'Кронштейн 3117.01 80х40х90 / БП 0,09м [НВФ]'
      ZESTAW=    '{ 8. Кронштейн класичні <b>90mm</b> <FONT COLOR="#FF0000"><FONT-SIZE="2"><b><big>(Фіксовані)</b><FONT-SIZE="1">}'

      RODZAJ=1
	  
      PARAMETRY=
	    <
        Z_LISTY=
            < KLUCZ       = 'NVF_PODOVGUVACH' 
			  PYTANIE     = 'Використовувати подовжувача до кронштейна:' 
              ELEMENT     = 'Без подовжувача'   
              ELEMENT     = 'З використаням подовжувача 100х90 (ПАС-3836.02)'   			  
              STANDARDOWO = '0'			  
		  >	  	  
		>		 
	  
	  SYSTEMY= [DEF_SYS_NVF_KERAM_KLIAM, DEF_SYS_NVF_KERAM_GLUE,DEF_SYS_NVF_AKP,DEF_SYS_NVF_HPL_PANEL,DEF_SYS_NVF_FZP]
      RYSUNEK= '3117_01_KR.png'
      WLASNY_RYSUNEK=TAK 
					ROZMIAR_X='100'
					ROZMIAR_Y='100'	
                    RYSUNEK=   'fix_nepodv.vct'					
	  			    POLOZENIE_X='0'
					POLOZENIE_Y='0'
					WYMIARY_GRUPY
                    AKTYWNY=TAK 		

      ELEMENT[N]=< KOD=E_ALP_NVF_3117_01            NR_PRZEKROJU=517 ILOSC='1'                 STRONA=KOLOR_WEWN  >
      ELEMENT[N]=< KOD=E_ALP_NVF_PAS_3836_02        NR_PRZEKROJU=517 ILOSC='1*NVF_PODOVGUVACH' STRONA=KOLOR_WEWN  >
      ELEMENT[N]=< KOD=E_ALP_NVF_Zakl_5_10_DIN7337  NR_PRZEKROJU=517 ILOSC='2'                 STRONA=KOLOR_WEWN  >
      ELEMENT[N]=< KOD=E_ALP_NVF_Zakl_5_10_DIN7337  NR_PRZEKROJU=517 ILOSC='2*NVF_PODOVGUVACH' STRONA=KOLOR_WEWN  >
	  
      ELEMENT[N]=< KOD=E_ALP_NVF_TERMO_70_50_5      NR_PRZEKROJU=517 ILOSC='1'                 STRONA=KOLOR_WEWN  >  
	  >	  
	  
    GRUPA[1149]=
      <
      NAZWA=     'Кронштейн 3179.02 100х40х90 / БП 0,06м [НВФ]'
      OPIS=      'Кронштейн 3179.02 100х40х90 / БП 0,06м [НВФ]'
      ZESTAW=    '{ 8. Кронштейн класичні <b>90mm</b> <FONT COLOR="#FF0000"><FONT-SIZE="2"><b><big>(Фіксовані)</b><FONT-SIZE="1">}'

      RODZAJ=1
	  
      PARAMETRY=
	    <
        Z_LISTY=
            < KLUCZ       = 'NVF_PODOVGUVACH' 
			  PYTANIE     = 'Використовувати подовжувача до кронштейна:' 
              ELEMENT     = 'Без подовжувача'   
              ELEMENT     = 'З використаням подовжувача 100х90 (ПАС-3836.02)'   			  
              STANDARDOWO = '0'			  
		  >	  	  
		>		 
	  
	  SYSTEMY= [DEF_SYS_NVF_KERAM_KLIAM, DEF_SYS_NVF_KERAM_GLUE,DEF_SYS_NVF_AKP,DEF_SYS_NVF_HPL_PANEL,DEF_SYS_NVF_FZP]
      RYSUNEK= '3117_01_KR.png'
      WLASNY_RYSUNEK=TAK 
					ROZMIAR_X='100'
					ROZMIAR_Y='100'	
                    RYSUNEK=   'fix_nepodv.vct'					
	  			    POLOZENIE_X='0'
					POLOZENIE_Y='0'
					WYMIARY_GRUPY
                    AKTYWNY=TAK 		

      ELEMENT[N]=< KOD=E_ALP_NVF_3179_02            NR_PRZEKROJU=517 ILOSC='1'                 STRONA=KOLOR_WEWN  >
      ELEMENT[N]=< KOD=E_ALP_NVF_PAS_3836_02        NR_PRZEKROJU=517 ILOSC='1*NVF_PODOVGUVACH' STRONA=KOLOR_WEWN  >
      ELEMENT[N]=< KOD=E_ALP_NVF_Zakl_5_10_DIN7337  NR_PRZEKROJU=517 ILOSC='2'                 STRONA=KOLOR_WEWN  >
      ELEMENT[N]=< KOD=E_ALP_NVF_Zakl_5_10_DIN7337  NR_PRZEKROJU=517 ILOSC='2*NVF_PODOVGUVACH' STRONA=KOLOR_WEWN  >
	  
      ELEMENT[N]=< KOD=E_ALP_NVF_TERMO_70_50_5      NR_PRZEKROJU=517 ILOSC='1'                 STRONA=KOLOR_WEWN  >  
	  >	  
	  
    GRUPA[1150]=
      <
      NAZWA=     'Кронштейн 3118.02 120х40х90 / БП 0,06м [НВФ]'
      OPIS=      'Кронштейн 3118.02 120х40х90 / БП 0,06м [НВФ]'
      ZESTAW=    '{ 8. Кронштейн класичні <b>90mm</b> <FONT COLOR="#FF0000"><FONT-SIZE="2"><b><big>(Фіксовані)</b><FONT-SIZE="1">}'

      RODZAJ=1
	  
      PARAMETRY=
	    <
        Z_LISTY=
            < KLUCZ       = 'NVF_PODOVGUVACH' 
			  PYTANIE     = 'Використовувати подовжувача до кронштейна:' 
              ELEMENT     = 'Без подовжувача'   
              ELEMENT     = 'З використаням подовжувача 100х90 (ПАС-3836.02)'   			  
              STANDARDOWO = '0'			  
		  >	  	  
		>		 
	  
	  SYSTEMY= [DEF_SYS_NVF_KERAM_KLIAM, DEF_SYS_NVF_KERAM_GLUE,DEF_SYS_NVF_AKP,DEF_SYS_NVF_HPL_PANEL,DEF_SYS_NVF_FZP]
      RYSUNEK= '3117_01_KR.png'
      WLASNY_RYSUNEK=TAK 
					ROZMIAR_X='100'
					ROZMIAR_Y='100'	
                    RYSUNEK=   'fix_nepodv.vct'					
	  			    POLOZENIE_X='0'
					POLOZENIE_Y='0'
					WYMIARY_GRUPY
                    AKTYWNY=TAK 		

      ELEMENT[N]=< KOD=E_ALP_NVF_3118_02            NR_PRZEKROJU=517 ILOSC='1'                 STRONA=KOLOR_WEWN  >
      ELEMENT[N]=< KOD=E_ALP_NVF_PAS_3836_02        NR_PRZEKROJU=517 ILOSC='1*NVF_PODOVGUVACH' STRONA=KOLOR_WEWN  >
      ELEMENT[N]=< KOD=E_ALP_NVF_Zakl_5_10_DIN7337  NR_PRZEKROJU=517 ILOSC='2'                 STRONA=KOLOR_WEWN  >
      ELEMENT[N]=< KOD=E_ALP_NVF_Zakl_5_10_DIN7337  NR_PRZEKROJU=517 ILOSC='2*NVF_PODOVGUVACH' STRONA=KOLOR_WEWN  >
	  
      ELEMENT[N]=< KOD=E_ALP_NVF_TERMO_70_50_5      NR_PRZEKROJU=517 ILOSC='1'                 STRONA=KOLOR_WEWN  >  
	  >	  
	  
    GRUPA[1151]=
      <
      NAZWA=     'Кронштейн ПАС-3546.02 140х40х90 / БП 0,06м [НВФ]'
      OPIS=      'Кронштейн ПАС-3546.02 140х40х90 / БП 0,06м [НВФ]'
      ZESTAW=    '{ 8. Кронштейн класичні <b>90mm</b> <FONT COLOR="#FF0000"><FONT-SIZE="2"><b><big>(Фіксовані)</b><FONT-SIZE="1">}'

      RODZAJ=1
	  
      PARAMETRY=
	    <
        Z_LISTY=
            < KLUCZ       = 'NVF_PODOVGUVACH' 
			  PYTANIE     = 'Використовувати подовжувача до кронштейна:' 
              ELEMENT     = 'Без подовжувача'   
              ELEMENT     = 'З використаням подовжувача 100х90 (ПАС-3836.02)'   			  
              STANDARDOWO = '0'			  
		  >	  	  
		>		 
	  
	  SYSTEMY= [DEF_SYS_NVF_KERAM_KLIAM, DEF_SYS_NVF_KERAM_GLUE,DEF_SYS_NVF_AKP,DEF_SYS_NVF_HPL_PANEL,DEF_SYS_NVF_FZP]
      RYSUNEK= '3117_01_KR.png'
      WLASNY_RYSUNEK=TAK 
					ROZMIAR_X='100'
					ROZMIAR_Y='100'	
                    RYSUNEK=   'fix_nepodv.vct'					
	  			    POLOZENIE_X='0'
					POLOZENIE_Y='0'
					WYMIARY_GRUPY
                    AKTYWNY=TAK 		

      ELEMENT[N]=< KOD=E_ALP_NVF_PAS_3546_02            NR_PRZEKROJU=517 ILOSC='1'                 STRONA=KOLOR_WEWN  >
      ELEMENT[N]=< KOD=E_ALP_NVF_PAS_3836_02        NR_PRZEKROJU=517 ILOSC='1*NVF_PODOVGUVACH' STRONA=KOLOR_WEWN  >
      ELEMENT[N]=< KOD=E_ALP_NVF_Zakl_5_10_DIN7337  NR_PRZEKROJU=517 ILOSC='2'                 STRONA=KOLOR_WEWN  >
      ELEMENT[N]=< KOD=E_ALP_NVF_Zakl_5_10_DIN7337  NR_PRZEKROJU=517 ILOSC='2*NVF_PODOVGUVACH' STRONA=KOLOR_WEWN  >
	  
      ELEMENT[N]=< KOD=E_ALP_NVF_TERMO_70_50_5      NR_PRZEKROJU=517 ILOSC='1'                 STRONA=KOLOR_WEWN  >  
	  >	  
	  
    GRUPA[1152]=
      <
      NAZWA=     'Кронштейн ПАС-3546.02 140х40х90 / БП 0,06м [НВФ]'
      OPIS=      'Кронштейн ПАС-3546.02 140х40х90 / БП 0,06м [НВФ]'
      ZESTAW=    '{ 8. Кронштейн класичні <b>90mm</b> <FONT COLOR="#FF0000"><FONT-SIZE="2"><b><big>(Фіксовані)</b><FONT-SIZE="1">}'

      RODZAJ=1
	  
      PARAMETRY=
	    <
        Z_LISTY=
            < KLUCZ       = 'NVF_PODOVGUVACH' 
			  PYTANIE     = 'Використовувати подовжувача до кронштейна:' 
              ELEMENT     = 'Без подовжувача'   
              ELEMENT     = 'З використаням подовжувача 100х90 (ПАС-3836.02)'   			  
              STANDARDOWO = '0'			  
		  >	  	  
		>		 
	  
	  SYSTEMY= [DEF_SYS_NVF_KERAM_KLIAM, DEF_SYS_NVF_KERAM_GLUE,DEF_SYS_NVF_AKP,DEF_SYS_NVF_HPL_PANEL,DEF_SYS_NVF_FZP]
      RYSUNEK= '3117_01_KR.png'
      WLASNY_RYSUNEK=TAK 
					ROZMIAR_X='100'
					ROZMIAR_Y='100'	
                    RYSUNEK=   'fix_nepodv.vct'					
	  			    POLOZENIE_X='0'
					POLOZENIE_Y='0'
					WYMIARY_GRUPY
                    AKTYWNY=TAK 		

      ELEMENT[N]=< KOD=E_ALP_NVF_PAS_3546_02            NR_PRZEKROJU=517 ILOSC='1'                 STRONA=KOLOR_WEWN  >
      ELEMENT[N]=< KOD=E_ALP_NVF_PAS_3836_02        NR_PRZEKROJU=517 ILOSC='1*NVF_PODOVGUVACH' STRONA=KOLOR_WEWN  >
      ELEMENT[N]=< KOD=E_ALP_NVF_Zakl_5_10_DIN7337  NR_PRZEKROJU=517 ILOSC='2'                 STRONA=KOLOR_WEWN  >
      ELEMENT[N]=< KOD=E_ALP_NVF_Zakl_5_10_DIN7337  NR_PRZEKROJU=517 ILOSC='2*NVF_PODOVGUVACH' STRONA=KOLOR_WEWN  >
	  
      ELEMENT[N]=< KOD=E_ALP_NVF_TERMO_70_50_5      NR_PRZEKROJU=517 ILOSC='1'                 STRONA=KOLOR_WEWN  >  
	  >	  
	  
    GRUPA[1153]=
      <
      NAZWA=     'Кронштейн ПАС-3547.02 160х40х90 / БП 0,06м [НВФ]'
      OPIS=      'Кронштейн ПАС-3547.02 160х40х90 / БП 0,06м [НВФ]'
      ZESTAW=    '{ 7. Кронштейн класичні <b>90mm</b> <FONT COLOR="#0000FF"><FONT-SIZE="2"><b><big>(Рухомий)</b><FONT-SIZE="1">}'

      RODZAJ=1
	  
      PARAMETRY=
	    <
        Z_LISTY=
            < KLUCZ       = 'NVF_PODOVGUVACH' 
			  PYTANIE     = 'Використовувати подовжувача до кронштейна:' 
              ELEMENT     = 'Без подовжувача'   
              ELEMENT     = 'З використаням подовжувача 100х90 (ПАС-3836.02)'   			  
              STANDARDOWO = '0'			  
		  >	  	  
		>		 
	  
	  SYSTEMY= [DEF_SYS_NVF_KERAM_KLIAM, DEF_SYS_NVF_KERAM_GLUE,DEF_SYS_NVF_AKP,DEF_SYS_NVF_HPL_PANEL,DEF_SYS_NVF_FZP]
      RYSUNEK= '3117_01_KR.png'
      WLASNY_RYSUNEK=TAK 
					ROZMIAR_X='100'
					ROZMIAR_Y='100'	
                    RYSUNEK=   'fix_nepodv.vct'					
	  			    POLOZENIE_X='0'
					POLOZENIE_Y='0'
					WYMIARY_GRUPY
                    AKTYWNY=TAK 		

      ELEMENT[N]=< KOD=E_ALP_NVF_PAS_3547_02            NR_PRZEKROJU=517 ILOSC='1'                 STRONA=KOLOR_WEWN  >
      ELEMENT[N]=< KOD=E_ALP_NVF_PAS_3836_02        NR_PRZEKROJU=517 ILOSC='1*NVF_PODOVGUVACH' STRONA=KOLOR_WEWN  >
      ELEMENT[N]=< KOD=E_ALP_NVF_Zakl_5_10_DIN7337  NR_PRZEKROJU=517 ILOSC='2'                 STRONA=KOLOR_WEWN  >
      ELEMENT[N]=< KOD=E_ALP_NVF_Zakl_5_10_DIN7337  NR_PRZEKROJU=517 ILOSC='2*NVF_PODOVGUVACH' STRONA=KOLOR_WEWN  >
	  
      ELEMENT[N]=< KOD=E_ALP_NVF_TERMO_70_50_5      NR_PRZEKROJU=517 ILOSC='1'                 STRONA=KOLOR_WEWN  >  
	  >	  
	  
    GRUPA[1154]=
      <
      NAZWA=     'Кронштейн 3379.02 180х40х90 / БП 0,06м [НВФ]'
      OPIS=      'Кронштейн 3379.02 180х40х90 / БП 0,06м [НВФ]'
      ZESTAW=    '{ 8. Кронштейн класичні <b>90mm</b> <FONT COLOR="#FF0000"><FONT-SIZE="2"><b><big>(Фіксовані)</b><FONT-SIZE="1">}'

      RODZAJ=1
	  
      PARAMETRY=
	    <
        Z_LISTY=
            < KLUCZ       = 'NVF_PODOVGUVACH' 
			  PYTANIE     = 'Використовувати подовжувача до кронштейна:' 
              ELEMENT     = 'Без подовжувача'   
              ELEMENT     = 'З використаням подовжувача 100х90 (ПАС-3836.02)'   			  
              STANDARDOWO = '0'			  
		  >	  	  
		>		 
	  
	  SYSTEMY= [DEF_SYS_NVF_KERAM_KLIAM, DEF_SYS_NVF_KERAM_GLUE,DEF_SYS_NVF_AKP,DEF_SYS_NVF_HPL_PANEL,DEF_SYS_NVF_FZP]
      RYSUNEK= '3117_01_KR.png'
      WLASNY_RYSUNEK=TAK 
					ROZMIAR_X='100'
					ROZMIAR_Y='100'	
                    RYSUNEK=   'fix_nepodv.vct'					
	  			    POLOZENIE_X='0'
					POLOZENIE_Y='0'
					WYMIARY_GRUPY
                    AKTYWNY=TAK 		

      ELEMENT[N]=< KOD=E_ALP_NVF_3379_02            NR_PRZEKROJU=517 ILOSC='1'                 STRONA=KOLOR_WEWN  >
      ELEMENT[N]=< KOD=E_ALP_NVF_PAS_3836_02        NR_PRZEKROJU=517 ILOSC='1*NVF_PODOVGUVACH' STRONA=KOLOR_WEWN  >
      ELEMENT[N]=< KOD=E_ALP_NVF_Zakl_5_10_DIN7337  NR_PRZEKROJU=517 ILOSC='2'                 STRONA=KOLOR_WEWN  >
      ELEMENT[N]=< KOD=E_ALP_NVF_Zakl_5_10_DIN7337  NR_PRZEKROJU=517 ILOSC='2*NVF_PODOVGUVACH' STRONA=KOLOR_WEWN  >
	  
      ELEMENT[N]=< KOD=E_ALP_NVF_TERMO_70_50_5      NR_PRZEKROJU=517 ILOSC='1'                 STRONA=KOLOR_WEWN  >  
	  >	  
	  
    GRUPA[1155]=
      <
      NAZWA=     'Кронштейн ПАС-3668.02 210х40х90 / БП 0,06м [НВФ]'
      OPIS=      'Кронштейн ПАС-3668.02 210х40х90 / БП 0,06м [НВФ]'
      ZESTAW=    '{ 8. Кронштейн класичні <b>90mm</b> <FONT COLOR="#FF0000"><FONT-SIZE="2"><b><big>(Фіксовані)</b><FONT-SIZE="1">}'

      RODZAJ=1
	  
      PARAMETRY=
	    <
        Z_LISTY=
            < KLUCZ       = 'NVF_PODOVGUVACH' 
			  PYTANIE     = 'Використовувати подовжувача до кронштейна:' 
              ELEMENT     = 'Без подовжувача'   
              ELEMENT     = 'З використаням подовжувача 100х90 (ПАС-3836.02)'   			  
              STANDARDOWO = '0'			  
		  >	  	  
		>		 
	  
	  SYSTEMY= [DEF_SYS_NVF_KERAM_KLIAM, DEF_SYS_NVF_KERAM_GLUE,DEF_SYS_NVF_AKP,DEF_SYS_NVF_HPL_PANEL,DEF_SYS_NVF_FZP]
      RYSUNEK= '3117_01_KR.png'
      WLASNY_RYSUNEK=TAK 
					ROZMIAR_X='100'
					ROZMIAR_Y='100'	
                    RYSUNEK=   'fix_nepodv.vct'					
	  			    POLOZENIE_X='0'
					POLOZENIE_Y='0'
					WYMIARY_GRUPY
                    AKTYWNY=TAK 		

      ELEMENT[N]=< KOD=E_ALP_NVF_PAS_3668_02            NR_PRZEKROJU=517 ILOSC='1'                 STRONA=KOLOR_WEWN  >
      ELEMENT[N]=< KOD=E_ALP_NVF_PAS_3836_02        NR_PRZEKROJU=517 ILOSC='1*NVF_PODOVGUVACH' STRONA=KOLOR_WEWN  >
      ELEMENT[N]=< KOD=E_ALP_NVF_Zakl_5_10_DIN7337  NR_PRZEKROJU=517 ILOSC='2'                 STRONA=KOLOR_WEWN  >
      ELEMENT[N]=< KOD=E_ALP_NVF_Zakl_5_10_DIN7337  NR_PRZEKROJU=517 ILOSC='2*NVF_PODOVGUVACH' STRONA=KOLOR_WEWN  >
	  
      ELEMENT[N]=< KOD=E_ALP_NVF_TERMO_70_50_5      NR_PRZEKROJU=517 ILOSC='1'                 STRONA=KOLOR_WEWN  >  
	  >	  
	  
    GRUPA[1156]=
      <
      NAZWA=     'Кронштейн ПАС-3705.02 230х40х90 / БП 0,06м [НВФ]'
      OPIS=      'Кронштейн ПАС-3705.02 230х40х90 / БП 0,06м [НВФ]'
      ZESTAW=    '{ 8. Кронштейн класичні <b>90mm</b> <FONT COLOR="#FF0000"><FONT-SIZE="2"><b><big>(Фіксовані)</b><FONT-SIZE="1">}'

      RODZAJ=1
	  
      PARAMETRY=
	    <
        Z_LISTY=
            < KLUCZ       = 'NVF_PODOVGUVACH' 
			  PYTANIE     = 'Використовувати подовжувача до кронштейна:' 
              ELEMENT     = 'Без подовжувача'   
              ELEMENT     = 'З використаням подовжувача 100х90 (ПАС-3836.02)'   			  
              STANDARDOWO = '0'			  
		  >	  	  
		>		 
	  
	  SYSTEMY= [DEF_SYS_NVF_KERAM_KLIAM, DEF_SYS_NVF_KERAM_GLUE,DEF_SYS_NVF_AKP,DEF_SYS_NVF_HPL_PANEL,DEF_SYS_NVF_FZP]
      RYSUNEK= '3117_01_KR.png'
      WLASNY_RYSUNEK=TAK 
					ROZMIAR_X='100'
					ROZMIAR_Y='100'	
                    RYSUNEK=   'fix_nepodv.vct'					
	  			    POLOZENIE_X='0'
					POLOZENIE_Y='0'
					WYMIARY_GRUPY
                    AKTYWNY=TAK 		

      ELEMENT[N]=< KOD=E_ALP_NVF_PAS_3705_02            NR_PRZEKROJU=517 ILOSC='1'                 STRONA=KOLOR_WEWN  >
      ELEMENT[N]=< KOD=E_ALP_NVF_PAS_3836_02        NR_PRZEKROJU=517 ILOSC='1*NVF_PODOVGUVACH' STRONA=KOLOR_WEWN  >
      ELEMENT[N]=< KOD=E_ALP_NVF_Zakl_5_10_DIN7337  NR_PRZEKROJU=517 ILOSC='2'                 STRONA=KOLOR_WEWN  >
      ELEMENT[N]=< KOD=E_ALP_NVF_Zakl_5_10_DIN7337  NR_PRZEKROJU=517 ILOSC='2*NVF_PODOVGUVACH' STRONA=KOLOR_WEWN  >
	  
      ELEMENT[N]=< KOD=E_ALP_NVF_TERMO_70_50_5      NR_PRZEKROJU=517 ILOSC='1'                 STRONA=KOLOR_WEWN  >  
	  >	  

  //***************************************	  
	  
    GRUPA[1157]=
      <
      NAZWA=     'Кронштейн 3117.04 80х40х120 / БП 0,09м [НВФ]'
      OPIS=      'Кронштейн 3117.04 80х40х120 / БП 0,09м [НВФ]'
      ZESTAW=    '{ 9. Кронштейн класичні <b>120mm</b> <FONT COLOR="#FF0000"><FONT-SIZE="2"><b><big>(Фіксовані)</b><FONT-SIZE="1">}'

      RODZAJ=1
	  
      PARAMETRY=
	    <
        Z_LISTY=
            < KLUCZ       = 'NVF_PODOVGUVACH' 
			  PYTANIE     = 'Використовувати подовжувача до кронштейна:' 
              ELEMENT     = 'Без подовжувача'   
              ELEMENT     = 'З використаням подовжувача 100х120 (ПАС-3836.03)'   			  
              STANDARDOWO = '0'			  
		  >	  	  
		>		 
	  
	  SYSTEMY= [DEF_SYS_NVF_KERAM_KLIAM, DEF_SYS_NVF_KERAM_GLUE,DEF_SYS_NVF_AKP,DEF_SYS_NVF_HPL_PANEL,DEF_SYS_NVF_FZP]
      RYSUNEK= '3117_04_KR.png'
      WLASNY_RYSUNEK=TAK 
					ROZMIAR_X='100'
					ROZMIAR_Y='100'	
                    RYSUNEK=   'fix_nepodv.vct'					
	  			    POLOZENIE_X='0'
					POLOZENIE_Y='0'
					WYMIARY_GRUPY
                    AKTYWNY=TAK 		

      ELEMENT[N]=< KOD=E_ALP_NVF_3117_04            NR_PRZEKROJU=517 ILOSC='1'                 STRONA=KOLOR_WEWN  >
      ELEMENT[N]=< KOD=E_ALP_NVF_PAS_3836_03        NR_PRZEKROJU=517 ILOSC='1*NVF_PODOVGUVACH' STRONA=KOLOR_WEWN  >
      ELEMENT[N]=< KOD=E_ALP_NVF_Zakl_5_10_DIN7337  NR_PRZEKROJU=517 ILOSC='2'                 STRONA=KOLOR_WEWN  >
      ELEMENT[N]=< KOD=E_ALP_NVF_Zakl_5_10_DIN7337  NR_PRZEKROJU=517 ILOSC='2*NVF_PODOVGUVACH' STRONA=KOLOR_WEWN  >
	  
      ELEMENT[N]=< KOD=E_ALP_NVF_TERMO_140_50_5     NR_PRZEKROJU=517 ILOSC='1'                 STRONA=KOLOR_WEWN  >  
	  >	  
	  
    GRUPA[1158]=
      <
      NAZWA=     'Кронштейн 3179.04 100х40х120 / БП 0,06м [НВФ]'
      OPIS=      'Кронштейн 3179.04 100х40х120 / БП 0,06м [НВФ]'
      ZESTAW=    '{ 9. Кронштейн класичні <b>120mm</b> <FONT COLOR="#FF0000"><FONT-SIZE="2"><b><big>(Фіксовані)</b><FONT-SIZE="1">}'

      RODZAJ=1
	  
      PARAMETRY=
	    <
        Z_LISTY=
            < KLUCZ       = 'NVF_PODOVGUVACH' 
			  PYTANIE     = 'Використовувати подовжувача до кронштейна:' 
              ELEMENT     = 'Без подовжувача'   
              ELEMENT     = 'З використаням подовжувача 100х120 (ПАС-3836.03)'   			  
              STANDARDOWO = '0'			  
		  >	  	  
		>		 
	  
	  SYSTEMY= [DEF_SYS_NVF_KERAM_KLIAM, DEF_SYS_NVF_KERAM_GLUE,DEF_SYS_NVF_AKP,DEF_SYS_NVF_HPL_PANEL,DEF_SYS_NVF_FZP]
      RYSUNEK= '3117_04_KR.png'
      WLASNY_RYSUNEK=TAK 
					ROZMIAR_X='100'
					ROZMIAR_Y='100'	
                    RYSUNEK=   'fix_nepodv.vct'					
	  			    POLOZENIE_X='0'
					POLOZENIE_Y='0'
					WYMIARY_GRUPY
                    AKTYWNY=TAK 		

      ELEMENT[N]=< KOD=E_ALP_NVF_3179_04            NR_PRZEKROJU=517 ILOSC='1'                 STRONA=KOLOR_WEWN  >
      ELEMENT[N]=< KOD=E_ALP_NVF_PAS_3836_03        NR_PRZEKROJU=517 ILOSC='1*NVF_PODOVGUVACH' STRONA=KOLOR_WEWN  >
      ELEMENT[N]=< KOD=E_ALP_NVF_Zakl_5_10_DIN7337  NR_PRZEKROJU=517 ILOSC='2'                 STRONA=KOLOR_WEWN  >
      ELEMENT[N]=< KOD=E_ALP_NVF_Zakl_5_10_DIN7337  NR_PRZEKROJU=517 ILOSC='2*NVF_PODOVGUVACH' STRONA=KOLOR_WEWN  >
	  
      ELEMENT[N]=< KOD=E_ALP_NVF_TERMO_140_50_5     NR_PRZEKROJU=517 ILOSC='1'                 STRONA=KOLOR_WEWN  >  
	  >	  
	  
    GRUPA[1159]=
      <
      NAZWA=     'Кронштейн 3179.04 100х40х120 / БП 0,06м [НВФ]'
      OPIS=      'Кронштейн 3179.04 100х40х120 / БП 0,06м [НВФ]'
      ZESTAW=    '{ 9. Кронштейн класичні <b>120mm</b> <FONT COLOR="#FF0000"><FONT-SIZE="2"><b><big>(Фіксовані)</b><FONT-SIZE="1">}'

      RODZAJ=1
	  
      PARAMETRY=
	    <
        Z_LISTY=
            < KLUCZ       = 'NVF_PODOVGUVACH' 
			  PYTANIE     = 'Використовувати подовжувача до кронштейна:' 
              ELEMENT     = 'Без подовжувача'   
              ELEMENT     = 'З використаням подовжувача 100х120 (ПАС-3836.03)'   			  
              STANDARDOWO = '0'			  
		  >	  	  
		>		 
	  
	  SYSTEMY= [DEF_SYS_NVF_KERAM_KLIAM, DEF_SYS_NVF_KERAM_GLUE,DEF_SYS_NVF_AKP,DEF_SYS_NVF_HPL_PANEL,DEF_SYS_NVF_FZP]
      RYSUNEK= '3117_04_KR.png'
      WLASNY_RYSUNEK=TAK 
					ROZMIAR_X='100'
					ROZMIAR_Y='100'	
                    RYSUNEK=   'fix_nepodv.vct'					
	  			    POLOZENIE_X='0'
					POLOZENIE_Y='0'
					WYMIARY_GRUPY
                    AKTYWNY=TAK 		

      ELEMENT[N]=< KOD=E_ALP_NVF_3179_04            NR_PRZEKROJU=517 ILOSC='1'                 STRONA=KOLOR_WEWN  >
      ELEMENT[N]=< KOD=E_ALP_NVF_PAS_3836_03        NR_PRZEKROJU=517 ILOSC='1*NVF_PODOVGUVACH' STRONA=KOLOR_WEWN  >
      ELEMENT[N]=< KOD=E_ALP_NVF_Zakl_5_10_DIN7337  NR_PRZEKROJU=517 ILOSC='2'                 STRONA=KOLOR_WEWN  >
      ELEMENT[N]=< KOD=E_ALP_NVF_Zakl_5_10_DIN7337  NR_PRZEKROJU=517 ILOSC='2*NVF_PODOVGUVACH' STRONA=KOLOR_WEWN  >
	  
      ELEMENT[N]=< KOD=E_ALP_NVF_TERMO_140_50_5     NR_PRZEKROJU=517 ILOSC='1'                 STRONA=KOLOR_WEWN  >  
	  >	  
	  
    GRUPA[1160]=
      <
      NAZWA=     'Кронштейн 3118.04 120х40х120 / БП 0,06м [НВФ]'
      OPIS=      'Кронштейн 3118.04 120х40х120 / БП 0,06м [НВФ]'
      ZESTAW=    '{ 9. Кронштейн класичні <b>120mm</b> <FONT COLOR="#FF0000"><FONT-SIZE="2"><b><big>(Фіксовані)</b><FONT-SIZE="1">}'

      RODZAJ=1
	  
      PARAMETRY=
	    <
        Z_LISTY=
            < KLUCZ       = 'NVF_PODOVGUVACH' 
			  PYTANIE     = 'Використовувати подовжувача до кронштейна:' 
              ELEMENT     = 'Без подовжувача'   
              ELEMENT     = 'З використаням подовжувача 100х120 (ПАС-3836.03)'   			  
              STANDARDOWO = '0'			  
		  >	  	  
		>		 
	  
	  SYSTEMY= [DEF_SYS_NVF_KERAM_KLIAM, DEF_SYS_NVF_KERAM_GLUE,DEF_SYS_NVF_AKP,DEF_SYS_NVF_HPL_PANEL,DEF_SYS_NVF_FZP]
      RYSUNEK= '3117_04_KR.png'
      WLASNY_RYSUNEK=TAK 
					ROZMIAR_X='100'
					ROZMIAR_Y='100'	
                    RYSUNEK=   'fix_nepodv.vct'					
	  			    POLOZENIE_X='0'
					POLOZENIE_Y='0'
					WYMIARY_GRUPY
                    AKTYWNY=TAK 		

      ELEMENT[N]=< KOD=E_ALP_NVF_3118_04            NR_PRZEKROJU=517 ILOSC='1'                 STRONA=KOLOR_WEWN  >
      ELEMENT[N]=< KOD=E_ALP_NVF_PAS_3836_03        NR_PRZEKROJU=517 ILOSC='1*NVF_PODOVGUVACH' STRONA=KOLOR_WEWN  >
      ELEMENT[N]=< KOD=E_ALP_NVF_Zakl_5_10_DIN7337  NR_PRZEKROJU=517 ILOSC='2'                 STRONA=KOLOR_WEWN  >
      ELEMENT[N]=< KOD=E_ALP_NVF_Zakl_5_10_DIN7337  NR_PRZEKROJU=517 ILOSC='2*NVF_PODOVGUVACH' STRONA=KOLOR_WEWN  >
	  
      ELEMENT[N]=< KOD=E_ALP_NVF_TERMO_140_50_5     NR_PRZEKROJU=517 ILOSC='1'                 STRONA=KOLOR_WEWN  >  
	  >	  
	  
    GRUPA[1161]=
      <
      NAZWA=     'Кронштейн ПАС-3546.04 140х40х120 / БП 0,06м [НВФ]'
      OPIS=      'Кронштейн ПАС-3546.04 140х40х120 / БП 0,06м [НВФ]'
      ZESTAW=    '{ 9. Кронштейн класичні <b>120mm</b> <FONT COLOR="#FF0000"><FONT-SIZE="2"><b><big>(Фіксовані)</b><FONT-SIZE="1">}'

      RODZAJ=1
	  
      PARAMETRY=
	    <
        Z_LISTY=
            < KLUCZ       = 'NVF_PODOVGUVACH' 
			  PYTANIE     = 'Використовувати подовжувача до кронштейна:' 
              ELEMENT     = 'Без подовжувача'   
              ELEMENT     = 'З використаням подовжувача 100х120 (ПАС-3836.03)'   			  
              STANDARDOWO = '0'			  
		  >	  	  
		>		 
	  
	  SYSTEMY= [DEF_SYS_NVF_KERAM_KLIAM, DEF_SYS_NVF_KERAM_GLUE,DEF_SYS_NVF_AKP,DEF_SYS_NVF_HPL_PANEL,DEF_SYS_NVF_FZP]
      RYSUNEK= '3117_04_KR.png'
      WLASNY_RYSUNEK=TAK 
					ROZMIAR_X='100'
					ROZMIAR_Y='100'	
                    RYSUNEK=   'fix_nepodv.vct'					
	  			    POLOZENIE_X='0'
					POLOZENIE_Y='0'
					WYMIARY_GRUPY
                    AKTYWNY=TAK 		

      ELEMENT[N]=< KOD=E_ALP_NVF_PAS_3546_04            NR_PRZEKROJU=517 ILOSC='1'                 STRONA=KOLOR_WEWN  >
      ELEMENT[N]=< KOD=E_ALP_NVF_PAS_3836_03        NR_PRZEKROJU=517 ILOSC='1*NVF_PODOVGUVACH' STRONA=KOLOR_WEWN  >
      ELEMENT[N]=< KOD=E_ALP_NVF_Zakl_5_10_DIN7337  NR_PRZEKROJU=517 ILOSC='2'                 STRONA=KOLOR_WEWN  >
      ELEMENT[N]=< KOD=E_ALP_NVF_Zakl_5_10_DIN7337  NR_PRZEKROJU=517 ILOSC='2*NVF_PODOVGUVACH' STRONA=KOLOR_WEWN  >
	  
      ELEMENT[N]=< KOD=E_ALP_NVF_TERMO_140_50_5     NR_PRZEKROJU=517 ILOSC='1'                 STRONA=KOLOR_WEWN  >  
	  >	  
	  
    GRUPA[1162]=
      <
      NAZWA=     'Кронштейн ПАС-3547.04 160х40х120 / БП 0,06м [НВФ]'
      OPIS=      'Кронштейн ПАС-3547.04 160х40х120 / БП 0,06м [НВФ]'
      ZESTAW=    '{ 9. Кронштейн класичні <b>120mm</b> <FONT COLOR="#FF0000"><FONT-SIZE="2"><b><big>(Фіксовані)</b><FONT-SIZE="1">}'

      RODZAJ=1
	  
      PARAMETRY=
	    <
        Z_LISTY=
            < KLUCZ       = 'NVF_PODOVGUVACH' 
			  PYTANIE     = 'Використовувати подовжувача до кронштейна:' 
              ELEMENT     = 'Без подовжувача'   
              ELEMENT     = 'З використаням подовжувача 100х120 (ПАС-3836.03)'   			  
              STANDARDOWO = '0'			  
		  >	  	  
		>		 
	  
	  SYSTEMY= [DEF_SYS_NVF_KERAM_KLIAM, DEF_SYS_NVF_KERAM_GLUE,DEF_SYS_NVF_AKP,DEF_SYS_NVF_HPL_PANEL,DEF_SYS_NVF_FZP]
      RYSUNEK= '3117_04_KR.png'
      WLASNY_RYSUNEK=TAK 
					ROZMIAR_X='100'
					ROZMIAR_Y='100'	
                    RYSUNEK=   'fix_nepodv.vct'					
	  			    POLOZENIE_X='0'
					POLOZENIE_Y='0'
					WYMIARY_GRUPY
                    AKTYWNY=TAK 		

      ELEMENT[N]=< KOD=E_ALP_NVF_PAS_3547_04            NR_PRZEKROJU=517 ILOSC='1'                 STRONA=KOLOR_WEWN  >
      ELEMENT[N]=< KOD=E_ALP_NVF_PAS_3836_03        NR_PRZEKROJU=517 ILOSC='1*NVF_PODOVGUVACH' STRONA=KOLOR_WEWN  >
      ELEMENT[N]=< KOD=E_ALP_NVF_Zakl_5_10_DIN7337  NR_PRZEKROJU=517 ILOSC='2'                 STRONA=KOLOR_WEWN  >
      ELEMENT[N]=< KOD=E_ALP_NVF_Zakl_5_10_DIN7337  NR_PRZEKROJU=517 ILOSC='2*NVF_PODOVGUVACH' STRONA=KOLOR_WEWN  >
	  
      ELEMENT[N]=< KOD=E_ALP_NVF_TERMO_140_50_5     NR_PRZEKROJU=517 ILOSC='1'                 STRONA=KOLOR_WEWN  >  
	  >	  
	  
    GRUPA[1163]=
      <
      NAZWA=     'Кронштейн 3379.04 180х40х120 / БП 0,06м [НВФ]'
      OPIS=      'Кронштейн 3379.04 180х40х120 / БП 0,06м [НВФ]'
      ZESTAW=    '{ 9. Кронштейн класичні <b>120mm</b> <FONT COLOR="#FF0000"><FONT-SIZE="2"><b><big>(Фіксовані)</b><FONT-SIZE="1">}'

      RODZAJ=1
	  
      PARAMETRY=
	    <
        Z_LISTY=
            < KLUCZ       = 'NVF_PODOVGUVACH' 
			  PYTANIE     = 'Використовувати подовжувача до кронштейна:' 
              ELEMENT     = 'Без подовжувача'   
              ELEMENT     = 'З використаням подовжувача 100х120 (ПАС-3836.03)'   			  
              STANDARDOWO = '0'			  
		  >	  	  
		>		 
	  
	  SYSTEMY= [DEF_SYS_NVF_KERAM_KLIAM, DEF_SYS_NVF_KERAM_GLUE,DEF_SYS_NVF_AKP,DEF_SYS_NVF_HPL_PANEL,DEF_SYS_NVF_FZP]
      RYSUNEK= '3117_04_KR.png'
      WLASNY_RYSUNEK=TAK 
					ROZMIAR_X='100'
					ROZMIAR_Y='100'	
                    RYSUNEK=   'fix_nepodv.vct'					
	  			    POLOZENIE_X='0'
					POLOZENIE_Y='0'
					WYMIARY_GRUPY
                    AKTYWNY=TAK 		

      ELEMENT[N]=< KOD=E_ALP_NVF_3379_04            NR_PRZEKROJU=517 ILOSC='1'                 STRONA=KOLOR_WEWN  >
      ELEMENT[N]=< KOD=E_ALP_NVF_PAS_3836_03        NR_PRZEKROJU=517 ILOSC='1*NVF_PODOVGUVACH' STRONA=KOLOR_WEWN  >
      ELEMENT[N]=< KOD=E_ALP_NVF_Zakl_5_10_DIN7337  NR_PRZEKROJU=517 ILOSC='2'                 STRONA=KOLOR_WEWN  >
      ELEMENT[N]=< KOD=E_ALP_NVF_Zakl_5_10_DIN7337  NR_PRZEKROJU=517 ILOSC='2*NVF_PODOVGUVACH' STRONA=KOLOR_WEWN  >
	  
      ELEMENT[N]=< KOD=E_ALP_NVF_TERMO_140_50_5     NR_PRZEKROJU=517 ILOSC='1'                 STRONA=KOLOR_WEWN  >  
	  >	  
	  
    GRUPA[1164]=
      <
      NAZWA=     'Кронштейн ПАС-3668.04 210х40х120 / БП 0,06м [НВФ]'
      OPIS=      'Кронштейн ПАС-3668.04 210х40х120 / БП 0,06м [НВФ]'
      ZESTAW=    '{ 9. Кронштейн класичні <b>120mm</b> <FONT COLOR="#FF0000"><FONT-SIZE="2"><b><big>(Фіксовані)</b><FONT-SIZE="1">}'

      RODZAJ=1
	  
      PARAMETRY=
	    <
        Z_LISTY=
            < KLUCZ       = 'NVF_PODOVGUVACH' 
			  PYTANIE     = 'Використовувати подовжувача до кронштейна:' 
              ELEMENT     = 'Без подовжувача'   
              ELEMENT     = 'З використаням подовжувача 100х120 (ПАС-3836.03)'   			  
              STANDARDOWO = '0'			  
		  >	  	  
		>		 
	  
	  SYSTEMY= [DEF_SYS_NVF_KERAM_KLIAM, DEF_SYS_NVF_KERAM_GLUE,DEF_SYS_NVF_AKP,DEF_SYS_NVF_HPL_PANEL,DEF_SYS_NVF_FZP]
      RYSUNEK= '3117_04_KR.png'
      WLASNY_RYSUNEK=TAK 
					ROZMIAR_X='100'
					ROZMIAR_Y='100'	
                    RYSUNEK=   'fix_nepodv.vct'					
	  			    POLOZENIE_X='0'
					POLOZENIE_Y='0'
					WYMIARY_GRUPY
                    AKTYWNY=TAK 		

      ELEMENT[N]=< KOD=E_ALP_NVF_PAS_3668_04            NR_PRZEKROJU=517 ILOSC='1'                 STRONA=KOLOR_WEWN  >
      ELEMENT[N]=< KOD=E_ALP_NVF_PAS_3836_03        NR_PRZEKROJU=517 ILOSC='1*NVF_PODOVGUVACH' STRONA=KOLOR_WEWN  >
      ELEMENT[N]=< KOD=E_ALP_NVF_Zakl_5_10_DIN7337  NR_PRZEKROJU=517 ILOSC='2'                 STRONA=KOLOR_WEWN  >
      ELEMENT[N]=< KOD=E_ALP_NVF_Zakl_5_10_DIN7337  NR_PRZEKROJU=517 ILOSC='2*NVF_PODOVGUVACH' STRONA=KOLOR_WEWN  >
	  
      ELEMENT[N]=< KOD=E_ALP_NVF_TERMO_140_50_5     NR_PRZEKROJU=517 ILOSC='1'                 STRONA=KOLOR_WEWN  >  
	  >	  
	  
    GRUPA[1165]=
      <
      NAZWA=     'Кронштейн ПАС-3705.03 230х40х120 / БП 0,06м [НВФ]'
      OPIS=      'Кронштейн ПАС-3705.03 230х40х120 / БП 0,06м [НВФ]'
      ZESTAW=    '{ 9. Кронштейн класичні <b>120mm</b> <FONT COLOR="#FF0000"><FONT-SIZE="2"><b><big>(Фіксовані)</b><FONT-SIZE="1">}'

      RODZAJ=1
	  
      PARAMETRY=
	    <
        Z_LISTY=
            < KLUCZ       = 'NVF_PODOVGUVACH' 
			  PYTANIE     = 'Використовувати подовжувача до кронштейна:' 
              ELEMENT     = 'Без подовжувача'   
              ELEMENT     = 'З використаням подовжувача 100х120 (ПАС-3836.03)'   			  
              STANDARDOWO = '0'			  
		  >	  	  
		>		 
	  
	  SYSTEMY= [DEF_SYS_NVF_KERAM_KLIAM, DEF_SYS_NVF_KERAM_GLUE,DEF_SYS_NVF_AKP,DEF_SYS_NVF_HPL_PANEL,DEF_SYS_NVF_FZP]
      RYSUNEK= '3117_04_KR.png'
      WLASNY_RYSUNEK=TAK 
					ROZMIAR_X='100'
					ROZMIAR_Y='100'	
                    RYSUNEK=   'fix_nepodv.vct'					
	  			    POLOZENIE_X='0'
					POLOZENIE_Y='0'
					WYMIARY_GRUPY
                    AKTYWNY=TAK 		

      ELEMENT[N]=< KOD=E_ALP_NVF_PAS_3705_03            NR_PRZEKROJU=517 ILOSC='1'                 STRONA=KOLOR_WEWN  >
      ELEMENT[N]=< KOD=E_ALP_NVF_PAS_3836_03        NR_PRZEKROJU=517 ILOSC='1*NVF_PODOVGUVACH' STRONA=KOLOR_WEWN  >
      ELEMENT[N]=< KOD=E_ALP_NVF_Zakl_5_10_DIN7337  NR_PRZEKROJU=517 ILOSC='2'                 STRONA=KOLOR_WEWN  >
      ELEMENT[N]=< KOD=E_ALP_NVF_Zakl_5_10_DIN7337  NR_PRZEKROJU=517 ILOSC='2*NVF_PODOVGUVACH' STRONA=KOLOR_WEWN  >
	  
      ELEMENT[N]=< KOD=E_ALP_NVF_TERMO_140_50_5     NR_PRZEKROJU=517 ILOSC='1'                 STRONA=KOLOR_WEWN  >  
	  >	  

  //***************************************	  
	  
    GRUPA[1166]=
      <
      NAZWA=     'Кронштейн 3117.03 80х40х140 / БП 0,09м [НВФ]'
      OPIS=      'Кронштейн 3117.03 80х40х140 / БП 0,09м [НВФ]'
      ZESTAW=    '{10. Кронштейн класичні <b>140mm</b> <FONT COLOR="#FF0000"><FONT-SIZE="2"><b><big>(Фіксовані)</b><FONT-SIZE="1">}'

      RODZAJ=1
	  
      PARAMETRY=
	    <
        Z_LISTY=
            < KLUCZ       = 'NVF_PODOVGUVACH' 
			  PYTANIE     = 'Використовувати подовжувача до кронштейна:' 
              ELEMENT     = 'Без подовжувача'   
              ELEMENT     = 'З використаням подовжувача 100х140 (ПАС-3836.04)'   			  
              STANDARDOWO = '0'			  
		  >	  	  
		>		 
	  
	  SYSTEMY= [DEF_SYS_NVF_KERAM_KLIAM, DEF_SYS_NVF_KERAM_GLUE,DEF_SYS_NVF_AKP,DEF_SYS_NVF_HPL_PANEL,DEF_SYS_NVF_FZP]
      RYSUNEK= '3117_03_KR.png'
      WLASNY_RYSUNEK=TAK 
					ROZMIAR_X='100'
					ROZMIAR_Y='100'	
                    RYSUNEK=   'fix_nepodv.vct'					
	  			    POLOZENIE_X='0'
					POLOZENIE_Y='0'
					WYMIARY_GRUPY
                    AKTYWNY=TAK 		

      ELEMENT[N]=< KOD=E_ALP_NVF_3117_03            NR_PRZEKROJU=517 ILOSC='1'                 STRONA=KOLOR_WEWN  >
      ELEMENT[N]=< KOD=E_ALP_NVF_PAS_3836_04        NR_PRZEKROJU=517 ILOSC='1*NVF_PODOVGUVACH' STRONA=KOLOR_WEWN  >
      ELEMENT[N]=< KOD=E_ALP_NVF_Zakl_5_10_DIN7337  NR_PRZEKROJU=517 ILOSC='2'                 STRONA=KOLOR_WEWN  >
      ELEMENT[N]=< KOD=E_ALP_NVF_Zakl_5_10_DIN7337  NR_PRZEKROJU=517 ILOSC='2*NVF_PODOVGUVACH' STRONA=KOLOR_WEWN  >
	  
      ELEMENT[N]=< KOD=E_ALP_NVF_TERMO_140_50_5     NR_PRZEKROJU=517 ILOSC='1'                 STRONA=KOLOR_WEWN  >  
	  >	  
	  
    GRUPA[1167]=
      <
      NAZWA=     'Кронштейн 3179.03 100х40х140 / БП 0,06м [НВФ]'
      OPIS=      'Кронштейн 3179.03 100х40х140 / БП 0,06м [НВФ]'
      ZESTAW=    '{10. Кронштейн класичні <b>140mm</b> <FONT COLOR="#FF0000"><FONT-SIZE="2"><b><big>(Фіксовані)</b><FONT-SIZE="1">}'

      RODZAJ=1
	  
      PARAMETRY=
	    <
        Z_LISTY=
            < KLUCZ       = 'NVF_PODOVGUVACH' 
			  PYTANIE     = 'Використовувати подовжувача до кронштейна:' 
              ELEMENT     = 'Без подовжувача'   
              ELEMENT     = 'З використаням подовжувача 100х140 (ПАС-3836.04)'   			  
              STANDARDOWO = '0'			  
		  >	  	  
		>		 
	  
	  SYSTEMY= [DEF_SYS_NVF_KERAM_KLIAM, DEF_SYS_NVF_KERAM_GLUE,DEF_SYS_NVF_AKP,DEF_SYS_NVF_HPL_PANEL,DEF_SYS_NVF_FZP]
      RYSUNEK= '3117_03_KR.png'
      WLASNY_RYSUNEK=TAK 
					ROZMIAR_X='100'
					ROZMIAR_Y='100'	
                    RYSUNEK=   'fix_nepodv.vct'					
	  			    POLOZENIE_X='0'
					POLOZENIE_Y='0'
					WYMIARY_GRUPY
                    AKTYWNY=TAK 		

      ELEMENT[N]=< KOD=E_ALP_NVF_3179_03            NR_PRZEKROJU=517 ILOSC='1'                 STRONA=KOLOR_WEWN  >
      ELEMENT[N]=< KOD=E_ALP_NVF_PAS_3836_04        NR_PRZEKROJU=517 ILOSC='1*NVF_PODOVGUVACH' STRONA=KOLOR_WEWN  >
      ELEMENT[N]=< KOD=E_ALP_NVF_Zakl_5_10_DIN7337  NR_PRZEKROJU=517 ILOSC='2'                 STRONA=KOLOR_WEWN  >
      ELEMENT[N]=< KOD=E_ALP_NVF_Zakl_5_10_DIN7337  NR_PRZEKROJU=517 ILOSC='2*NVF_PODOVGUVACH' STRONA=KOLOR_WEWN  >
	  
      ELEMENT[N]=< KOD=E_ALP_NVF_TERMO_140_50_5     NR_PRZEKROJU=517 ILOSC='1'                 STRONA=KOLOR_WEWN  >  
	  >	  
	  
    GRUPA[1168]=
      <
      NAZWA=     'Кронштейн 3118.03 120х40х140 / БП 0,06м [НВФ]'
      OPIS=      'Кронштейн 3118.03 120х40х140 / БП 0,06м [НВФ]'
      ZESTAW=    '{10. Кронштейн класичні <b>140mm</b> <FONT COLOR="#FF0000"><FONT-SIZE="2"><b><big>(Фіксовані)</b><FONT-SIZE="1">}'

      RODZAJ=1
	  
      PARAMETRY=
	    <
        Z_LISTY=
            < KLUCZ       = 'NVF_PODOVGUVACH' 
			  PYTANIE     = 'Використовувати подовжувача до кронштейна:' 
              ELEMENT     = 'Без подовжувача'   
              ELEMENT     = 'З використаням подовжувача 100х140 (ПАС-3836.04)'   			  
              STANDARDOWO = '0'			  
		  >	  	  
		>		 
	  
	  SYSTEMY= [DEF_SYS_NVF_KERAM_KLIAM, DEF_SYS_NVF_KERAM_GLUE,DEF_SYS_NVF_AKP,DEF_SYS_NVF_HPL_PANEL,DEF_SYS_NVF_FZP]
      RYSUNEK= '3117_03_KR.png'
      WLASNY_RYSUNEK=TAK 
					ROZMIAR_X='100'
					ROZMIAR_Y='100'	
                    RYSUNEK=   'fix_nepodv.vct'					
	  			    POLOZENIE_X='0'
					POLOZENIE_Y='0'
					WYMIARY_GRUPY
                    AKTYWNY=TAK 		

      ELEMENT[N]=< KOD=E_ALP_NVF_3118_03            NR_PRZEKROJU=517 ILOSC='1'                 STRONA=KOLOR_WEWN  >
      ELEMENT[N]=< KOD=E_ALP_NVF_PAS_3836_04        NR_PRZEKROJU=517 ILOSC='1*NVF_PODOVGUVACH' STRONA=KOLOR_WEWN  >
      ELEMENT[N]=< KOD=E_ALP_NVF_Zakl_5_10_DIN7337  NR_PRZEKROJU=517 ILOSC='2'                 STRONA=KOLOR_WEWN  >
      ELEMENT[N]=< KOD=E_ALP_NVF_Zakl_5_10_DIN7337  NR_PRZEKROJU=517 ILOSC='2*NVF_PODOVGUVACH' STRONA=KOLOR_WEWN  >
	  
      ELEMENT[N]=< KOD=E_ALP_NVF_TERMO_140_50_5     NR_PRZEKROJU=517 ILOSC='1'                 STRONA=KOLOR_WEWN  >  
	  >	  
	  
    GRUPA[1169]=
      <
      NAZWA=     'Кронштейн ПАС-3546.03 140х40х140 / БП 0,06м [НВФ]'
      OPIS=      'Кронштейн ПАС-3546.03 140х40х140 / БП 0,06м [НВФ]'
      ZESTAW=    '{10. Кронштейн класичні <b>140mm</b> <FONT COLOR="#FF0000"><FONT-SIZE="2"><b><big>(Фіксовані)</b><FONT-SIZE="1">}'

      RODZAJ=1
	  
      PARAMETRY=
	    <
        Z_LISTY=
            < KLUCZ       = 'NVF_PODOVGUVACH' 
			  PYTANIE     = 'Використовувати подовжувача до кронштейна:' 
              ELEMENT     = 'Без подовжувача'   
              ELEMENT     = 'З використаням подовжувача 100х140 (ПАС-3836.04)'   			  
              STANDARDOWO = '0'			  
		  >	  	  
		>		 
	  
	  SYSTEMY= [DEF_SYS_NVF_KERAM_KLIAM, DEF_SYS_NVF_KERAM_GLUE,DEF_SYS_NVF_AKP,DEF_SYS_NVF_HPL_PANEL,DEF_SYS_NVF_FZP]
      RYSUNEK= '3117_03_KR.png'
      WLASNY_RYSUNEK=TAK 
					ROZMIAR_X='100'
					ROZMIAR_Y='100'	
                    RYSUNEK=   'fix_nepodv.vct'					
	  			    POLOZENIE_X='0'
					POLOZENIE_Y='0'
					WYMIARY_GRUPY
                    AKTYWNY=TAK 		

      ELEMENT[N]=< KOD=E_ALP_NVF_PAS_3546_03            NR_PRZEKROJU=517 ILOSC='1'                 STRONA=KOLOR_WEWN  >
      ELEMENT[N]=< KOD=E_ALP_NVF_PAS_3836_04        NR_PRZEKROJU=517 ILOSC='1*NVF_PODOVGUVACH' STRONA=KOLOR_WEWN  >
      ELEMENT[N]=< KOD=E_ALP_NVF_Zakl_5_10_DIN7337  NR_PRZEKROJU=517 ILOSC='2'                 STRONA=KOLOR_WEWN  >
      ELEMENT[N]=< KOD=E_ALP_NVF_Zakl_5_10_DIN7337  NR_PRZEKROJU=517 ILOSC='2*NVF_PODOVGUVACH' STRONA=KOLOR_WEWN  >
	  
      ELEMENT[N]=< KOD=E_ALP_NVF_TERMO_140_50_5     NR_PRZEKROJU=517 ILOSC='1'                 STRONA=KOLOR_WEWN  >  
	  >	  
	  
    GRUPA[1170]=
      <
      NAZWA=     'Кронштейн ПАС-3547.03 160х40х140 / БП 0,06м [НВФ]'
      OPIS=      'Кронштейн ПАС-3547.03 160х40х140 / БП 0,06м [НВФ]'
      ZESTAW=    '{10. Кронштейн класичні <b>140mm</b> <FONT COLOR="#FF0000"><FONT-SIZE="2"><b><big>(Фіксовані)</b><FONT-SIZE="1">}'

      RODZAJ=1
	  
      PARAMETRY=
	    <
        Z_LISTY=
            < KLUCZ       = 'NVF_PODOVGUVACH' 
			  PYTANIE     = 'Використовувати подовжувача до кронштейна:' 
              ELEMENT     = 'Без подовжувача'   
              ELEMENT     = 'З використаням подовжувача 100х140 (ПАС-3836.04)'   			  
              STANDARDOWO = '0'			  
		  >	  	  
		>		 
	  
	  SYSTEMY= [DEF_SYS_NVF_KERAM_KLIAM, DEF_SYS_NVF_KERAM_GLUE,DEF_SYS_NVF_AKP,DEF_SYS_NVF_HPL_PANEL,DEF_SYS_NVF_FZP]
      RYSUNEK= '3117_03_KR.png'
      WLASNY_RYSUNEK=TAK 
					ROZMIAR_X='100'
					ROZMIAR_Y='100'	
                    RYSUNEK=   'fix_nepodv.vct'					
	  			    POLOZENIE_X='0'
					POLOZENIE_Y='0'
					WYMIARY_GRUPY
                    AKTYWNY=TAK 		

      ELEMENT[N]=< KOD=E_ALP_NVF_PAS_3547_03            NR_PRZEKROJU=517 ILOSC='1'                 STRONA=KOLOR_WEWN  >
      ELEMENT[N]=< KOD=E_ALP_NVF_PAS_3836_04        NR_PRZEKROJU=517 ILOSC='1*NVF_PODOVGUVACH' STRONA=KOLOR_WEWN  >
      ELEMENT[N]=< KOD=E_ALP_NVF_Zakl_5_10_DIN7337  NR_PRZEKROJU=517 ILOSC='2'                 STRONA=KOLOR_WEWN  >
      ELEMENT[N]=< KOD=E_ALP_NVF_Zakl_5_10_DIN7337  NR_PRZEKROJU=517 ILOSC='2*NVF_PODOVGUVACH' STRONA=KOLOR_WEWN  >
	  
      ELEMENT[N]=< KOD=E_ALP_NVF_TERMO_140_50_5     NR_PRZEKROJU=517 ILOSC='1'                 STRONA=KOLOR_WEWN  >  
	  >	  
	  
    GRUPA[1171]=
      <
      NAZWA=     'Кронштейн 3379.03 180х40х140 / БП 0,06м [НВФ]'
      OPIS=      'Кронштейн 3379.03 180х40х140 / БП 0,06м [НВФ]'
      ZESTAW=    '{10. Кронштейн класичні <b>140mm</b> <FONT COLOR="#FF0000"><FONT-SIZE="2"><b><big>(Фіксовані)</b><FONT-SIZE="1">}'

      RODZAJ=1
	  
      PARAMETRY=
	    <
        Z_LISTY=
            < KLUCZ       = 'NVF_PODOVGUVACH' 
			  PYTANIE     = 'Використовувати подовжувача до кронштейна:' 
              ELEMENT     = 'Без подовжувача'   
              ELEMENT     = 'З використаням подовжувача 100х140 (ПАС-3836.04)'   			  
              STANDARDOWO = '0'			  
		  >	  	  
		>		 
	  
	  SYSTEMY= [DEF_SYS_NVF_KERAM_KLIAM, DEF_SYS_NVF_KERAM_GLUE,DEF_SYS_NVF_AKP,DEF_SYS_NVF_HPL_PANEL,DEF_SYS_NVF_FZP]
      RYSUNEK= '3117_03_KR.png'
      WLASNY_RYSUNEK=TAK 
					ROZMIAR_X='100'
					ROZMIAR_Y='100'	
                    RYSUNEK=   'fix_nepodv.vct'					
	  			    POLOZENIE_X='0'
					POLOZENIE_Y='0'
					WYMIARY_GRUPY
                    AKTYWNY=TAK 		

      ELEMENT[N]=< KOD=E_ALP_NVF_3379_03            NR_PRZEKROJU=517 ILOSC='1'                 STRONA=KOLOR_WEWN  >
      ELEMENT[N]=< KOD=E_ALP_NVF_PAS_3836_04        NR_PRZEKROJU=517 ILOSC='1*NVF_PODOVGUVACH' STRONA=KOLOR_WEWN  >
      ELEMENT[N]=< KOD=E_ALP_NVF_Zakl_5_10_DIN7337  NR_PRZEKROJU=517 ILOSC='2'                 STRONA=KOLOR_WEWN  >
      ELEMENT[N]=< KOD=E_ALP_NVF_Zakl_5_10_DIN7337  NR_PRZEKROJU=517 ILOSC='2*NVF_PODOVGUVACH' STRONA=KOLOR_WEWN  >
	  
      ELEMENT[N]=< KOD=E_ALP_NVF_TERMO_140_50_5     NR_PRZEKROJU=517 ILOSC='1'                 STRONA=KOLOR_WEWN  >  
	  >	  
	  
    GRUPA[1172]=
      <
      NAZWA=     'Кронштейн ПАС-3668.03 210х40х140 / БП 0,06м [НВФ]'
      OPIS=      'Кронштейн ПАС-3668.03 210х40х140 / БП 0,06м [НВФ]'
      ZESTAW=    '{10. Кронштейн класичні <b>140mm</b> <FONT COLOR="#FF0000"><FONT-SIZE="2"><b><big>(Фіксовані)</b><FONT-SIZE="1">}'

      RODZAJ=1
	  
      PARAMETRY=
	    <
        Z_LISTY=
            < KLUCZ       = 'NVF_PODOVGUVACH' 
			  PYTANIE     = 'Використовувати подовжувача до кронштейна:' 
              ELEMENT     = 'Без подовжувача'   
              ELEMENT     = 'З використаням подовжувача 100х140 (ПАС-3836.04)'   			  
              STANDARDOWO = '0'			  
		  >	  	  
		>		 
	  
	  SYSTEMY= [DEF_SYS_NVF_KERAM_KLIAM, DEF_SYS_NVF_KERAM_GLUE,DEF_SYS_NVF_AKP,DEF_SYS_NVF_HPL_PANEL,DEF_SYS_NVF_FZP]
      RYSUNEK= '3117_03_KR.png'
      WLASNY_RYSUNEK=TAK 
					ROZMIAR_X='100'
					ROZMIAR_Y='100'	
                    RYSUNEK=   'fix_nepodv.vct'					
	  			    POLOZENIE_X='0'
					POLOZENIE_Y='0'
					WYMIARY_GRUPY
                    AKTYWNY=TAK 		

      ELEMENT[N]=< KOD=E_ALP_NVF_PAS_3668_03            NR_PRZEKROJU=517 ILOSC='1'                 STRONA=KOLOR_WEWN  >
      ELEMENT[N]=< KOD=E_ALP_NVF_PAS_3836_04        NR_PRZEKROJU=517 ILOSC='1*NVF_PODOVGUVACH' STRONA=KOLOR_WEWN  >
      ELEMENT[N]=< KOD=E_ALP_NVF_Zakl_5_10_DIN7337  NR_PRZEKROJU=517 ILOSC='2'                 STRONA=KOLOR_WEWN  >
      ELEMENT[N]=< KOD=E_ALP_NVF_Zakl_5_10_DIN7337  NR_PRZEKROJU=517 ILOSC='2*NVF_PODOVGUVACH' STRONA=KOLOR_WEWN  >
	  
      ELEMENT[N]=< KOD=E_ALP_NVF_TERMO_140_50_5     NR_PRZEKROJU=517 ILOSC='1'                 STRONA=KOLOR_WEWN  >  
	  >	  
	  
    GRUPA[1173]=
      <
      NAZWA=     'Кронштейн ПАС-3705.04 230х40х140 / БП 0,06м [НВФ]'
      OPIS=      'Кронштейн ПАС-3705.04 230х40х140 / БП 0,06м [НВФ]'
      ZESTAW=    '{10. Кронштейн класичні <b>140mm</b> <FONT COLOR="#FF0000"><FONT-SIZE="2"><b><big>(Фіксовані)</b><FONT-SIZE="1">}'

      RODZAJ=1
	  
      PARAMETRY=
	    <
        Z_LISTY=
            < KLUCZ       = 'NVF_PODOVGUVACH' 
			  PYTANIE     = 'Використовувати подовжувача до кронштейна:' 
              ELEMENT     = 'Без подовжувача'   
              ELEMENT     = 'З використаням подовжувача 100х140 (ПАС-3836.04)'   			  
              STANDARDOWO = '0'			  
		  >	  	  
		>		 
	  
	  SYSTEMY= [DEF_SYS_NVF_KERAM_KLIAM, DEF_SYS_NVF_KERAM_GLUE,DEF_SYS_NVF_AKP,DEF_SYS_NVF_HPL_PANEL,DEF_SYS_NVF_FZP]
      RYSUNEK= '3117_03_KR.png'
      WLASNY_RYSUNEK=TAK 
					ROZMIAR_X='100'
					ROZMIAR_Y='100'	
                    RYSUNEK=   'fix_nepodv.vct'					
	  			    POLOZENIE_X='0'
					POLOZENIE_Y='0'
					WYMIARY_GRUPY
                    AKTYWNY=TAK 		

      ELEMENT[N]=< KOD=E_ALP_NVF_PAS_3705_04            NR_PRZEKROJU=517 ILOSC='1'                 STRONA=KOLOR_WEWN  >
      ELEMENT[N]=< KOD=E_ALP_NVF_PAS_3836_04        NR_PRZEKROJU=517 ILOSC='1*NVF_PODOVGUVACH' STRONA=KOLOR_WEWN  >
      ELEMENT[N]=< KOD=E_ALP_NVF_Zakl_5_10_DIN7337  NR_PRZEKROJU=517 ILOSC='2'                 STRONA=KOLOR_WEWN  >
      ELEMENT[N]=< KOD=E_ALP_NVF_Zakl_5_10_DIN7337  NR_PRZEKROJU=517 ILOSC='2*NVF_PODOVGUVACH' STRONA=KOLOR_WEWN  >
	  
      ELEMENT[N]=< KOD=E_ALP_NVF_TERMO_140_50_5     NR_PRZEKROJU=517 ILOSC='1'                 STRONA=KOLOR_WEWN  >  
	  >	  
	  
    GRUPA[1174]=
      <
      NAZWA=     'Кронштейн ПАС-0596.01 60х40х60 / БП 0,06м [НВФ]'
      OPIS=      'Кронштейн ПАС-0596.01 60х40х60 / БП 0,06м [НВФ]'
      ZESTAW=    '{11. Кронштейн оновленний <b>60mm</b> <FONT COLOR="#0000FF"><FONT-SIZE="2"><b><big>(Рухомий)</b><FONT-SIZE="1">}'

      RODZAJ=1	 
	  
	  SYSTEMY= [DEF_SYS_NVF_KERAM_KLIAM, DEF_SYS_NVF_KERAM_GLUE,DEF_SYS_NVF_AKP,DEF_SYS_NVF_HPL_PANEL,DEF_SYS_NVF_FZP]
      //RYSUNEK= 'PAS_3602_01_KR.png'
      WLASNY_RYSUNEK=TAK 
					ROZMIAR_X='100'
					ROZMIAR_Y='100'	
                    RYSUNEK=   'fix_podv1.vct'					
	  			    POLOZENIE_X='0'
					POLOZENIE_Y='0'
					WYMIARY_GRUPY
                    AKTYWNY=TAK 		  

      ELEMENT[N]=< KOD=E_ALP_NVF_PAS_0596_01        NR_PRZEKROJU=517 ILOSC='1'                 STRONA=KOLOR_WEWN  >
      ELEMENT[N]=< KOD=E_ALP_NVF_Zakl_5_10_DIN7337  NR_PRZEKROJU=517 ILOSC='2'                 STRONA=KOLOR_WEWN  >
	  
      ELEMENT[N]=< KOD=E_ALP_NVF_TERMO_70_50_5     NR_PRZEKROJU=517 ILOSC='1'                 STRONA=KOLOR_WEWN  >  
	  >	  	 
	  
    GRUPA[1175]=
      <
      NAZWA=     'Кронштейн ПАС-0596.02 60х40х90 / БП 0,09м [НВФ]'
      OPIS=      'Кронштейн ПАС-0596.02 60х40х90 / БП 0,09м [НВФ]'
      ZESTAW=    '{11. Кронштейн оновленний <b>60mm</b> <FONT COLOR="#0000FF"><FONT-SIZE="2"><b><big>(Рухомий)</b><FONT-SIZE="1">}'

      RODZAJ=1	 
	  
	  SYSTEMY= [DEF_SYS_NVF_KERAM_KLIAM, DEF_SYS_NVF_KERAM_GLUE,DEF_SYS_NVF_AKP,DEF_SYS_NVF_HPL_PANEL,DEF_SYS_NVF_FZP]
      //RYSUNEK= 'PAS_3602_01_KR.png'
      WLASNY_RYSUNEK=TAK 
					ROZMIAR_X='100'
					ROZMIAR_Y='100'	
                    RYSUNEK=   'fix_podv1.vct'					
	  			    POLOZENIE_X='0'
					POLOZENIE_Y='0'
					WYMIARY_GRUPY
                    AKTYWNY=TAK 		  

      ELEMENT[N]=< KOD=E_ALP_NVF_PAS_0596_02        NR_PRZEKROJU=517 ILOSC='1'                 STRONA=KOLOR_WEWN  >
      ELEMENT[N]=< KOD=E_ALP_NVF_Zakl_5_10_DIN7337  NR_PRZEKROJU=517 ILOSC='2'                 STRONA=KOLOR_WEWN  >
	  
      ELEMENT[N]=< KOD=E_ALP_NVF_TERMO_70_50_5     NR_PRZEKROJU=517 ILOSC='1'                 STRONA=KOLOR_WEWN  >  
	  >	  	  
	  
    GRUPA[1176]=
      <
      NAZWA=     'Кронштейн ПАС-0596.03 60х40х120 / БП 0,12м [НВФ]'
      OPIS=      'Кронштейн ПАС-0596.03 60х40х120 / БП 0,12м [НВФ]'
      ZESTAW=    '{11. Кронштейн оновленний <b>60mm</b> <FONT COLOR="#0000FF"><FONT-SIZE="2"><b><big>(Рухомий)</b><FONT-SIZE="1">}'

      RODZAJ=1	 
	  
	  SYSTEMY= [DEF_SYS_NVF_KERAM_KLIAM, DEF_SYS_NVF_KERAM_GLUE,DEF_SYS_NVF_AKP,DEF_SYS_NVF_HPL_PANEL,DEF_SYS_NVF_FZP]
      //RYSUNEK= 'PAS_3602_01_KR.png'
      WLASNY_RYSUNEK=TAK 
					ROZMIAR_X='100'
					ROZMIAR_Y='100'	
                    RYSUNEK=   'fix_podv1.vct'					
	  			    POLOZENIE_X='0'
					POLOZENIE_Y='0'
					WYMIARY_GRUPY
                    AKTYWNY=TAK 		  

      ELEMENT[N]=< KOD=E_ALP_NVF_PAS_0596_03        NR_PRZEKROJU=517 ILOSC='1'                 STRONA=KOLOR_WEWN  >
      ELEMENT[N]=< KOD=E_ALP_NVF_Zakl_5_10_DIN7337  NR_PRZEKROJU=517 ILOSC='2'                 STRONA=KOLOR_WEWN  >
	  
      ELEMENT[N]=< KOD=E_ALP_NVF_TERMO_140_50_5     NR_PRZEKROJU=517 ILOSC='1'                 STRONA=KOLOR_WEWN  >  
	  >	  	 
	  
    GRUPA[1177]=
      <
      NAZWA=     'Кронштейн ПАС-0596.04 60х40х140 / БП 0,14м  [НВФ]'
      OPIS=      'Кронштейн ПАС-0596.04 60х40х140 / БП 0,14м  [НВФ]'
      ZESTAW=    '{11. Кронштейн оновленний <b>60mm</b> <FONT COLOR="#0000FF"><FONT-SIZE="2"><b><big>(Рухомий)</b><FONT-SIZE="1">}'

      RODZAJ=1	 
	  
	  SYSTEMY= [DEF_SYS_NVF_KERAM_KLIAM, DEF_SYS_NVF_KERAM_GLUE,DEF_SYS_NVF_AKP,DEF_SYS_NVF_HPL_PANEL,DEF_SYS_NVF_FZP]	  
      //RYSUNEK= 'PAS_3602_01_KR.png'
      WLASNY_RYSUNEK=TAK 
					ROZMIAR_X='100'
					ROZMIAR_Y='100'	
                    RYSUNEK=   'fix_podv1.vct'					
	  			    POLOZENIE_X='0'
					POLOZENIE_Y='0'
					WYMIARY_GRUPY
                    AKTYWNY=TAK 		  

      ELEMENT[N]=< KOD=E_ALP_NVF_PAS_0596_04        NR_PRZEKROJU=517 ILOSC='1'                 STRONA=KOLOR_WEWN  >
      ELEMENT[N]=< KOD=E_ALP_NVF_Zakl_5_10_DIN7337  NR_PRZEKROJU=517 ILOSC='2'                 STRONA=KOLOR_WEWN  >
	  
      ELEMENT[N]=< KOD=E_ALP_NVF_TERMO_140_50_5     NR_PRZEKROJU=517 ILOSC='1'                 STRONA=KOLOR_WEWN  >  
	  >	  
	  
    GRUPA[1500]=
     <
      NAZWA=     'Доводчик TS 2000 NV BCX *GEZE*'
      OPIS=      'Доводчик TS 2000 NV BCX *GEZE*'
      ZESTAW=    'Доводчик *GEZE*'
      RYSUNEK=   'Samozamykacz.vct'
  
      RODZAJ=0 
  
      SYSTEMY= [DEF_SYS_W77,DEF_SYS_C50,DEF_SYS_C50_CD]
	  
    #DEFINE NOT_WARNING_OKU
      ELEMENT[N]=< KOD=E_TS_2000_NV_BC     ILOSC='1' STRONA=KOLOR_ZEWN>	
      ELEMENT[N]=< KOD=E_TS_4000_TS_2000   ILOSC='1' STRONA=KOLOR_ZEWN>	
    #UNDEFINE NOT_WARNING_OKU 	  
         >   

    GRUPA[1501]=
     <
      NAZWA=     'Доводчик TS 1500 *GEZE*'
      OPIS=      'Доводчик TS 1500 *GEZE*'
      ZESTAW=    'Доводчик *GEZE*'
      RYSUNEK=   'Samozamykacz.vct'
  
      RODZAJ=0 
  
      SYSTEMY= [DEF_SYS_W77,DEF_SYS_C50,DEF_SYS_C50_CD]
	  
    #DEFINE NOT_WARNING_OKU
      ELEMENT[N]=< KOD=E_TS_1500           ILOSC='1' STRONA=KOLOR_ZEWN>	
    #UNDEFINE NOT_WARNING_OKU 	  
         >   			 
	  
>	

