
MATERIALY_DO_FASADY=
  <
  MATERIAL_DO_FASADY= 
    <
    KOD='FASAD_NVF_AKP'

	ZMIENNE_WSPOLNE
	

    NA_PROFILU
	

//	     WARUNEK2='1'
//
//	       ZAKRES  'Q_FIX_PAS_3686' ZALEZY OD 'SWIATLO_DLG'
//	       	[
//	       		<  '0'	  OD 0     DO 500    >			
//	       		<  '1'	  OD 500   DO 1000   >	
//	       		<  '2'	  OD 1000  DO 1500   >	
//	       		<  '3'	  OD 1500  DO 2000   >	
//	       		<  '4'	  OD 2000  DO 2500   >	
//	       		<  '5'	  OD 2500  DO 3000   >	
//	       		<  '6'	  OD 3000  DO 3500   >	
//	       		<  '7'	  OD 3500  DO 4000   >	
//	       		<  '8'	  OD 4000  DO 4500   >	
//	       		<  '9'	  OD 4500  DO 5000   >	
//	       		<  '10'   OD 5000  DO 5500   >	
//				
//	       		< INNE '1' >
//	       	]		 
//			
//	       WARUNEK1='1'    
//           AKCESORIA[E_ALP_NVF_PAS_3686_01;'Q_FIX_PAS_3686';-1]	
// 
//		  WARUNEK1=''					
//		 WARUNEK2=''	
		
    PRZY_SZKLE	
	
//	     WARUNEK2='1'
//
//	       ZAKRES  'Q_FIX_PAS_3686' ZALEZY OD 'GLASS_H'
//	       	[
//	       		<  '0'	  OD 0     DO 500    >			
//	       		<  '1'	  OD 500   DO 1000   >	
//	       		<  '2'	  OD 1000  DO 1500   >	
//	       		<  '3'	  OD 1500  DO 2000   >	
//	       		<  '4'	  OD 2000  DO 2500   >	
//	       		<  '5'	  OD 2500  DO 3000   >	
//	       		<  '6'	  OD 3000  DO 3500   >	
//	       		<  '7'	  OD 3500  DO 4000   >	
//	       		<  '8'	  OD 4000  DO 4500   >	
//	       		<  '9'	  OD 4500  DO 5000   >	
//	       		<  '10'   OD 5000  DO 5500   >	
//				
//	       		< INNE '1' >
//	       	]		 
//			
//	       WARUNEK1='1'    
//           AKCESORIA[E_ALP_NVF_PAS_3686_01;'Q_FIX_PAS_3686';-1]	
// 
//		  WARUNEK1=''					
//		 WARUNEK2=''		
  
    PRZY_SCIANIE	


	PRZY_RAMACH			  
	  
     >
   >