STANDARDOWE_DEFINICJE=
  <
    PROFILE=
      <
        STANDARD[TP_Szyba]=
          <
          PROFILE=[SZYBA_2]
          >

        STANDARD[TP_50_Fasada_RygielGora]=
          <
            PROFILE=[
                    PRF_F50_RYG_F50_201   ,
                    PRF_F50_RYG_F50_220   ,
                    PRF_F50_RYG_F50_202   ,
                    PRF_F50_RYG_F50_203   ,
                    PRF_F50_RYG_F50_204  ,
                    PRF_F50_RYG_F50_205  ,
                    PRF_F50_RYG_F50_206  ,
                    PRF_F50_RYG_F50_207  ,
	                
                    PRF_F50_WRYG_F50_220  ,
                    PRF_F50_WRYG_F50_202  ,
                    PRF_F50_WRYG_F50_203  ,
                    PRF_F50_WRYG_F50_204 ,
                    PRF_F50_WRYG_F50_205 ,
                    PRF_F50_WRYG_F50_206 ,
                    PRF_F50_WRYG_F50_207 						
               	      ]
          >    	 
        STANDARD[TP_50_Fasada_RygielDol                    ]=
          <
            PROFILE=[
                    PRF_F50_RYG_F50_201   ,
                    PRF_F50_RYG_F50_220   ,
                    PRF_F50_RYG_F50_202   ,
                    PRF_F50_RYG_F50_203   ,
                    PRF_F50_RYG_F50_204  ,
                    PRF_F50_RYG_F50_205  ,
                    PRF_F50_RYG_F50_206  ,
                    PRF_F50_RYG_F50_207  ,
	                
                    PRF_F50_WRYG_F50_220  ,
                    PRF_F50_WRYG_F50_202  ,
                    PRF_F50_WRYG_F50_203  ,
                    PRF_F50_WRYG_F50_204 ,
                    PRF_F50_WRYG_F50_205 ,
                    PRF_F50_WRYG_F50_206 ,
                    PRF_F50_WRYG_F50_207 				
                    ]
          >
        STANDARD[TP_50_Fasada_Slup                    ]=
          <
            PROFILE=[
                    PRF_F50_SLP_F50_101  ,
                    PRF_F50_SLP_F50_102  ,
                    PRF_F50_SLP_F50_103  ,
                    PRF_F50_SLP_F50_104  ,
                    PRF_F50_SLP_F50_105  ,
                    PRF_F50_SLP_F50_106  ,
                    PRF_F50_SLP_F50_107  ,	 
                    
                    PRF_F50_WSLP_F50_102 ,
                    PRF_F50_WSLP_F50_103 ,
                    PRF_F50_WSLP_F50_104 ,
                    PRF_F50_WSLP_F50_105 ,
                    PRF_F50_WSLP_F50_106 ,
                    PRF_F50_WSLP_F50_107 				
                                ]
          >

        STANDARD[TP_50_Fasada_Rygiel                  ]=
          <
             PROFILE=[
                    PRF_F50_RYG_F50_201   ,
                    PRF_F50_RYG_F50_220   ,
                    PRF_F50_RYG_F50_202   ,
                    PRF_F50_RYG_F50_203   ,
                    PRF_F50_RYG_F50_204  ,
                    PRF_F50_RYG_F50_205  ,
                    PRF_F50_RYG_F50_206  ,
                    PRF_F50_RYG_F50_207  ,
	                
                    PRF_F50_WRYG_F50_220  ,
                    PRF_F50_WRYG_F50_202  ,
                    PRF_F50_WRYG_F50_203  ,
                    PRF_F50_WRYG_F50_204 ,
                    PRF_F50_WRYG_F50_205 ,
                    PRF_F50_WRYG_F50_206 ,
                    PRF_F50_WRYG_F50_207 				
                     ]
          >

        STANDARD[TP_50_Fasada_SlupSciana              ]=
          <
             PROFILE=[
                    PRF_F50_SLP_F50_101  ,
                    PRF_F50_SLP_F50_102  ,
                    PRF_F50_SLP_F50_103  ,
                    PRF_F50_SLP_F50_104  ,
                    PRF_F50_SLP_F50_105  ,
                    PRF_F50_SLP_F50_106  ,
                    PRF_F50_SLP_F50_107  ,	 
                    
                    PRF_F50_WSLP_F50_102 ,
                    PRF_F50_WSLP_F50_103 ,
                    PRF_F50_WSLP_F50_104 ,
                    PRF_F50_WSLP_F50_105 ,
                    PRF_F50_WSLP_F50_106 ,
                    PRF_F50_WSLP_F50_107 							
                     ]
          >

        STANDARD[TP_50_Fasada_RygielSciana            ]=
          <
             PROFILE=[
                    PRF_F50_RYG_F50_201   ,
                    PRF_F50_RYG_F50_220   ,
                    PRF_F50_RYG_F50_202   ,
                    PRF_F50_RYG_F50_203   ,
                    PRF_F50_RYG_F50_204  ,
                    PRF_F50_RYG_F50_205  ,
                    PRF_F50_RYG_F50_206  ,
                    PRF_F50_RYG_F50_207  ,
	                
                    PRF_F50_WRYG_F50_220  ,
                    PRF_F50_WRYG_F50_202  ,
                    PRF_F50_WRYG_F50_203  ,
                    PRF_F50_WRYG_F50_204 ,
                    PRF_F50_WRYG_F50_205 ,
                    PRF_F50_WRYG_F50_206 ,
                    PRF_F50_WRYG_F50_207 							
                     ]
          >
//*************************************************************************		  
        STANDARD[TP_Fasada_RygielGora]=
          <
            PROFILE=[
		
               	      ]
          >    	 
        STANDARD[TP_Fasada_RygielDol                    ]=
          <
            PROFILE=[	
                    ]
          >
        STANDARD[TP_Fasada_Slup                    ]=
          <
            PROFILE=[		
                  PRF_NVF_KERAM_KLIAM_Vertical_PAS_3608,
				  PRF_NVF_KERAM_GLUE_Vertical_PAS_3608,
                  PRF_NVF_AKP_Vertical_PAS_3609	,
                  PRF_NVF_FZP_Vertical_PAS_3609				  
                                ]
          >

        STANDARD[TP_Fasada_Rygiel                  ]=
          <
             PROFILE=[
			 PRF_NVF_KERAM_KLIAM_Horizontal_Keram_Keram,
			 PRF_NVF_KERAM_GLUE_Horizontal_Keram_Keram,
			 PRF_NVF_AKP_Horizontal_Keram_Keram ,
			 PRF_NVF_FZP_Horizontal_PAS_3687
                     ]
          >

        STANDARD[TP_Fasada_SlupSciana              ]=
          <
             PROFILE=[
					PRF_NVF_KERAM_KLIAM_Vertical_Keram_Wall,
					PRF_NVF_KERAM_GLUE_Vertical_Keram_Wall,
					PRF_NVF_AKP_Vertical_Keram_Wall ,
					PRF_NVF_FZP_Vertical_Keram_Wall
                     ]
          >

        STANDARD[TP_Fasada_RygielSciana            ]=
          <
             PROFILE=[
			PRF_NVF_KERAM_KLIAM_Horizontal_Keram_Wall,
			PRF_NVF_KERAM_GLUE_Horizontal_Keram_Wall,
			PRF_NVF_AKP_Horizontal_Keram_Wall ,
			PRF_NVF_FZP_Horizontal_Keram_Wall
                     ]
          >
//*************************************************************************		
        STANDARD[TP_Peregorodka_RygielGora]=
          <
            PROFILE=[
			   
               	      ]
          >    	 
        STANDARD[TP_Peregorodka_RygielDol]=
          <
            PROFILE=[
			   
                    ]
          >
        STANDARD[TP_Peregorodka_Slup]=
          <
            PROFILE=[
			   
                    ]
          >

        STANDARD[TP_Peregorodka_Rygiel]=
          <
            PROFILE=[
			   
                    ]
          >

        STANDARD[TP_Peregorodka_SlupSciana]=
          <
            PROFILE=[
			   
                    ]
          >

        STANDARD[TP_Peregorodka_RygielSciana]=
          <
            PROFILE=[
			   
                    ]
          >		
        STANDARD[TP_Peregorodka_PodProgiem]=
          <
            PROFILE=[
			   
                    ]
          >		  
//*************************************************************************
        STANDARD[TP_VENTRECHETKA_RygielGora]=
          <
            PROFILE=[
                    			
               	      ]
          >    	 
        STANDARD[TP_VENTRECHETKA_RygielDol                    ]=
          <
            PROFILE=[
                    			
                    ]
          >
        STANDARD[TP_VENTRECHETKA_Slup                    ]=
          <
            PROFILE=[
                    
                                ]
          >

        STANDARD[TP_VENTRECHETKA_Rygiel                  ]=
          <
             PROFILE=[
               
                     ]
          >

        STANDARD[TP_VENTRECHETKA_SlupSciana              ]=
          <
             PROFILE=[
                   			
                     ]
          >

        STANDARD[TP_VENTRECHETKA_RygielSciana            ]=
          <
             PROFILE=[
                   			
                     ]
          >
//*************************************************************************
        STANDARD[TP_Fasada_Strips                    ]=
          <
            PROFILE=[
                    ]
          >
        STANDARD[TP_Fasada_OknoPolaciowe           ]=
          <
             PROFILE=[
                     ]
          >

        STANDARD[TP_Fasada_RamaStruktura           ]=
          <
             PROFILE=[
                     ]
          >
        STANDARD[TP_Fasada_SkrzydloStruktura       ]=
          <
             PROFILE=[
                     ]
          >
        STANDARD[TP_Fasada_SkrzydloPolStruktura    ]=
          <
             PROFILE=[
                     ]
          >

        STANDARD[TP_Struktura_Slup                 ]=
          <
            PROFILE=[
                    ]
          >

        STANDARD[TP_Struktura_Rygiel               ]=
          <
            PROFILE=[
                    ]
          >
        STANDARD[TP_Struktura_SlupSciana           ]=
          <
             PROFILE=[
                     ]
          >
        STANDARD[TP_Struktura_RygielSciana         ]=
          <
             PROFILE=[
                     ]
          >

        STANDARD[TP_Struktura_SkrzydloStruktura    ]=
          <
             PROFILE=[
                     ]
          >
        STANDARD[TP_Struktura_SkrzydloPolStruktura ]=
          <
             PROFILE=[
                     ]
          >

        STANDARD[TP_Fasada_PodProgiem              ]=
          <
            PROFILE=[
			       PRF_F50_BRAK				   
                    ]
          >
        STANDARD[TP_Fasada_PodRamaRigel]=
          <
            PROFILE=[
						   
                    ]
          >		  

        STANDARD[TP_RamaAuto2_Dol1                  ]=
           <
           PROFILE=[
                   ]
           >
        STANDARD[TP_RamaAuto2_Dol2                  ]=
           <
           PROFILE=[
                   ]
           >
        STANDARD[TP_RamaAuto2_Gora                 ]=
          <
          PROFILE=[
                  ]
          >
        STANDARD[TP_RamaAuto2_Bok                  ]=
          <
          PROFILE=[
                  ]
          >
        STANDARD[TP_RamaAuto2_Podzial12            ]=
          <
          PROFILE=[
                  ]
          >
        STANDARD[TP_RamaAuto2_Podzial11            ]=
          <
          PROFILE=[
                  ]
          >
        STANDARD[TP_RamaAuto2_Podzial22            ]=
          <
          PROFILE=[
                  ]
          >
        STANDARD[TP_RamaAuto3_Dol                  ]=
          <
          PROFILE=[
                  ]
          >
        STANDARD[TP_RamaAuto3_Gora                 ]=
          <
          PROFILE=[
                  ]
          >
        STANDARD[TP_RamaAuto3_Bok                  ]=
          <
          PROFILE=[
                  ]
          >
        STANDARD[TP_RamaAuto3_Podzial12            ]=
          <
          PROFILE=[
                  ]
          >
        STANDARD[TP_RamaAuto3_Podzial23            ]=
          <
          PROFILE=[
                  ]
          >
        STANDARD[TP_RamaAuto3_Podzial11            ]=
          <
          PROFILE=[
                  ]
          >
        STANDARD[TP_RamaAuto3_Podzial22            ]=
          <
          PROFILE=[
                  ]
          >
        STANDARD[TP_RamaAuto3_Podzial33            ]=
          <
          PROFILE=[
                  ]
          >
        STANDARD[TP_SkrzAuto21_Gora                ]=
          <
          PROFILE=[
                  ]
          >
        STANDARD[TP_SkrzAuto21_Dol                 ]=
          <
          PROFILE=[
                  ]
          >
        STANDARD[TP_SkrzAuto21_Rama                ]=
          <
          PROFILE=[
                  ]
          >
        STANDARD[TP_SkrzAuto21_PodzialXX           ]=
          <
          PROFILE=[
                  ]
          >
        STANDARD[TP_SkrzAuto21_PodzialXY           ]=
          <
          PROFILE=[
                  ]
          >
        STANDARD[TP_SkrzAuto22_Gora                ]=
          <
          PROFILE=[
                  ]
          >
        STANDARD[TP_SkrzAuto22_Dol                 ]=
          <
          PROFILE=[
                  ]
          >
        STANDARD[TP_SkrzAuto22_Rama                ]=
          <
          PROFILE=[
                  ]
          >
        STANDARD[TP_SkrzAuto22_PodzialXX           ]=
          <
          PROFILE=[
                  ]
          >
        STANDARD[TP_SkrzAuto22_PodzialXY           ]=
          <
          PROFILE=[
                  ]
          >
        STANDARD[TP_SkrzAuto31_Gora                ]=
          <
          PROFILE=[
                  ]
          >
        STANDARD[TP_SkrzAuto31_Dol                 ]=
          <
          PROFILE=[
                  ]
          >
        STANDARD[TP_SkrzAuto31_PodzialXX           ]=
          <
          PROFILE=[
                  ]
          >
        STANDARD[TP_SkrzAuto31_PodzialXY           ]=
          <
          PROFILE=[
                  ]
          >
        STANDARD[TP_SkrzAuto31_Rama                ]=
          <
          PROFILE=[
                  ]
          >
        STANDARD[TP_SkrzAuto32_Gora                ]=
          <
          PROFILE=[
                  ]
          >
        STANDARD[TP_SkrzAuto32_Dol                 ]=
          <
          PROFILE=[
                  ]
          >
        STANDARD[TP_SkrzAuto32_PodzialXX           ]=
          <
          PROFILE=[
                  ]
          >
        STANDARD[TP_SkrzAuto32_PodzialXY           ]=
          <
          PROFILE=[
                  ]
          >
        STANDARD[TP_SkrzAuto32_PodzialXZ           ]=
          <
          PROFILE=[
                  ]
          >
        STANDARD[TP_SkrzAuto32_Rama                ]=
          <
          PROFILE=[
                  ]
          >
        STANDARD[TP_SkrzAuto33_Gora                ]=
          <
          PROFILE=[
                  ]
          >
        STANDARD[TP_SkrzAuto33_Dol                 ]=
          <
          PROFILE=[
                  ]
          >
        STANDARD[TP_SkrzAuto33_PodzialXX           ]=
          <
          PROFILE=[
                  ]
          >
        STANDARD[TP_SkrzAuto33_PodzialXY           ]=
          <
          PROFILE=[
                  ]
          >
        STANDARD[TP_SkrzAuto33_Rama                ]=
          <
          PROFILE=[
                  ]
          >
        STANDARD[TP_SkrzAuto2_PoprzeczkaPion       ]=
          <
          PROFILE=[
                  ]
          >
        STANDARD[TP_SkrzAuto2_PoprzeczkaPoziom            ]=
          <
          PROFILE=[
                  ]
          >
        STANDARD[TP_SkrzAuto3_PoprzeczkaPion              ]=
          <
          PROFILE=[
                  ]
          >
        STANDARD[TP_SkrzAuto3_PoprzeczkaPoziom            ]=
          <
          PROFILE=[
                  ]
          >

        STANDARD[TP_PolaczoneKonstrukcje_RamaPion         ]=
         <
            PROFILE=[
                    
                    ]
          >

        STANDARD[TP_PolaczoneKonstrukcje_RamaDol          ]=
          <
            PROFILE=[
               
                    ]
          >

        STANDARD[TP_PolaczoneKonstrukcje_RamaGora         ]=
          <
            PROFILE=[
                 
                    ]
          >

        STANDARD[TP_PolaczoneKonstrukcje_RamaInna         ]=
          <
            PROFILE=[
                 
                    ]
          >

        STANDARD[TP_PolaczoneKonstrukcje_Brak             ]=
          <
            PROFILE=[
                 
                    ]
          >

        STANDARD[TP_PolaczoneKonstrukcje_LacznikPion      ]=
          <
            PROFILE=[
            
                    ]
          >

        STANDARD[TP_PolaczoneKonstrukcje_LacznikPoziom    ]=
          <
            PROFILE=[
             
                    ]
          >
        STANDARD[ TP_PolaczoneKonstrukcje_LacznikPoprzeczek ]=
          <
            PROFILE=[
                 
                    ]
          >

        STANDARD[TP_RamaStala_RamaDoFasady_FOM                ]=
          <
          PROFILE=[
                  ]
          >
        STANDARD[TP_RamaStala_RamaDoFasady_TON2                ]=
          <
          PROFILE=[
                  ]
          >		
        STANDARD[TP_RamaStala_RamaDoFasady_HOP                ]=
          <
          PROFILE=[
                  ]
          >			  
		  
        STANDARD[TP_RamaStala_TON4_RamaDoFasady_T50                ]=
          <
          PROFILE=[
                  ]
          > 		  
		  
		  
        STANDARD[TP_RamaStala_RamaPion                    ]=
          <
          PROFILE=[
                  ]
          >
        STANDARD[TP_RamaStala_RamaDol                     ]=
          <
          PROFILE=[
                  ]
          >
        STANDARD[TP_RamaStala_RamaGora                    ]=
          <
          PROFILE=[
                  ]
          >
        STANDARD[TP_RamaStala_RamaInna                    ]=
          <
          PROFILE=[
                  ]
          >
        STANDARD[TP_RamyStala_PoprzeczkaPion              ]=
          <
          PROFILE=[
                  ]
          >
        STANDARD[TP_RamyStala_PoprzeczkaPoziom            ]=
          <
          PROFILE=[
                  ]
          >

        STANDARD[TP_RamaOkienna_RamaDoFasady              ]=
          <
             PROFILE=[
                   			   
                     ]
          >
        STANDARD[TP_RamaVentReschetki_RamaDoOkna]=
          <
             PROFILE=[
                   
                     ]
          >
        STANDARD[TP_RamaOkienna_RamaPion                  ]=
          <
             PROFILE=[
	                   
                     ]
          >

        STANDARD[TP_RamaOkienna_RamaDol                   ]=
          <
             PROFILE=[
	              
                     ]
          >

        STANDARD[TP_RamaOkienna_RamaGora                  ]=
          <
              PROFILE=[
	               
                      ]
          >

        STANDARD[TP_RamaOkienna_RamaInna                  ]=
          <
             PROFILE=[
	              				 
                     ]
          >

        STANDARD[TP_RamaOkienna_PoprzeczkaPion            ]=
          <
             PROFILE=[
	                
                     ]
          >

        STANDARD[TP_RamaOkienna_PoprzeczkaPoziom          ]=
          <
             PROFILE=[
	                
                     ]
          >

        STANDARD[TP_RamaOkienna_SzczelinaBalkonu          ]=
          <
             PROFILE=[
                     ]
          >

        STANDARD[TP_RamaOkienna_RuchomySlupek             ]=
          <
             PROFILE=[
	                   PRF_RCHS_ALP_W77_610,
                       PRF_RCHS_ALP_W77_611	
                     ]
          >
        STANDARD[			TP_RamaHarm_RuchomySlupek_Ruchomy,
							TP_RamaHarm_RuchomySlupek_Ruchomy_tz,
							TP_RamaHarm_RuchomySlupek_Szyna	             
							]=
          <
             PROFILE=[
				 
				 
                     ]
          >		  

        STANDARD[TP_RamaOkienna_PodzialOknaPodawczego     ]=
          <
          PROFILE=[
		        
                  ]
          >
        STANDARD[TP_RamaOkienna_SzczelinaOknaPodawczego   ]=
          <
          PROFILE=[
                  ]
          >
        STANDARD[TP_RamaOkiennaZ_RamaDoFasady             ]=
          <
          PROFILE=[
                  ]
          >
        STANDARD[TP_RamaOkiennaZ_Rama                     ]=
          <
          PROFILE=[
                  ]
          >
        STANDARD[TP_RamaOkiennaZ_Rama2                     ]=
          <
          PROFILE=[
                  ]
          >
        STANDARD[TP_RamaOkiennaZ_Poprzeczka               ]=
          <
          PROFILE=[
                  ]
          >
        STANDARD[TP_RamaOkiennaZ_RuchomySlupek            ]=
          <
          PROFILE=[
                  ]
          >

        STANDARD[TP_SkrzydloOkienne_Zawias                ]=
          <
             PROFILE=[
	                 				 
                     ]
          >

        STANDARD[TP_SkrzydloOkienne_Klamka                ]=
          <
             PROFILE=[
	               					 
                     ]
          >

        STANDARD[TP_SkrzydloOkienne_Gora                  ]=
          <
             PROFILE=[
	               							 
                     ]
          >

        STANDARD[TP_SkrzydloOkienne_Dol                   ]=
          <
             PROFILE=[
	                						 
                     ]
          >

        STANDARD[TP_SkrzydloOkienne_Inne                  ]=
          <
             PROFILE=[
	                							 
                     ]
          >

        STANDARD[TP_SkrzydloOkienne_PrzyRuchomymSlupku    ]=
          <
             PROFILE=[
	                					 
                     ]
          >

        STANDARD[TP_SkrzydloOkienne_ZRuchomymSlupkiem     ]=
          <
             PROFILE=[
	               				 
                     ]
          >

        STANDARD[TP_SkrzydloOkienne_PoprzeczkaBalkonowa   ]=
          <
            PROFILE=[
                    ]
          >

        STANDARD[TP_SkrzydloOkienne_PoprzeczkaPionowa     ]=
          <
             PROFILE=[
	            					 
                     ]
          >

        STANDARD[TP_SkrzydloOkienne_PoprzeczkaPozioma     ]=
          <
             PROFILE=[
		     	    
                     ]
          >

        STANDARD[TP_RamaOkienna_RuchomySlupekVirtualny    ]=
          <
             PROFILE=[
			 
                     ]
          >

        STANDARD[TP_SkrzydloOkienne_PrzyRuchomymSlupkuVirtualny ]=
          <
             PROFILE=[
                     ]
          >

        STANDARD[TP_SkrzydloOkienne_ZRuchomymSlupkiemVirtualny  ]=
          <
             PROFILE=[
                     ]
          >

        STANDARD[TP_SkrzydloOkienne_ObrotoweCale          ]=
          <
          PROFILE=[
                  ]
          >
        STANDARD[TP_SkrzydloOkienne_ObrotowePodzielone    ]=
          <
          PROFILE=[
                  ]
          >
         STANDARD[TP_SkrzydloOkienneZ_O1                   ]=
          <
            PROFILE=[
                   ]
          >

        STANDARD[TP_SkrzydloPodawcze_PrzyPodzialeRuchome  ]=
          <
          PROFILE=[
                  ]
          >
        STANDARD[TP_SkrzydloPodawcze_PrzyPodzialeStale    ]=
          <
          PROFILE=[
                  ]
          >
        STANDARD[TP_SkrzydloPodawcze_BokStale             ]=
          <
          PROFILE=[
                  ]
          >
        STANDARD[TP_SkrzydloPodawcze_BokRuchome           ]=
          <
          PROFILE=[
                  ]
          >
        STANDARD[TP_SkrzydloPodawcze_DoRamyStale          ]=
          <
          PROFILE=[
                  ]
          >
        STANDARD[TP_SkrzydloPodawcze_DoRamyRuchome        ]=
          <
          PROFILE=[
                  ]
          >
        STANDARD[TP_SkrzydloPodawcze_DoSzczelinyRuchome   ]=
          <
          PROFILE=[
                  ]
          >
        STANDARD[TP_SkrzydloOkiennePosz_O1                ]=
          <
          PROFILE=[
                  ]
          >

        STANDARD[TP_RamaDrzwiowa_DZDoFasady               ]=
          <
             PROFILE=[
					PRF_RAMA_DRZWIOWA_DZF_ALP_W77_403 
                     ]
          >
        STANDARD[TP_RamaDrzwiowa_DZDoPeregorodka          ]=
          <
             PROFILE=[
			         
                     ]
          >	
        STANDARD[TP_RamaDrzwiowa_DWDoPeregorodka          ]=
          <
             PROFILE=[
			         
                     ]
          >			  

        STANDARD[TP_RamaDrzwiowa_DWDoFasady               ]=
          <
             PROFILE=[
			       	PRF_RAMA_DRZWIOWA_DWF_ALP_W77_404				 
                     ]
          >

        STANDARD[TP_RamaDrzwiowa_DHDoFasady               ]=
          <
          PROFILE=[
                  ]
          >
        STANDARD[TP_RamaDrzwiowa_DWZDoFasady              ]=
          <
          PROFILE=[
                  ]
          >
        STANDARD[TP_RamaDrzwiowa_DWBezpDoFasady           ]=
          <
          PROFILE=[
                  ]
          >
        STANDARD[TP_RamaDrzwiowa_DZBezpDoFasady           ]=
          <
          PROFILE=[
                  ]
          >

        STANDARD[TP_RamaDrzwiowa_DZ                       ]=
          <
             PROFILE=[
                PRF_RAMA_DRZWIOWA_DZ_ALP_W77_401
                     ]
          >

        STANDARD[TP_RamaDrzwiowa_DW                       ]=
          <
             PROFILE=[
                PRF_RAMA_DRZWIOWA_DW_ALP_W77_402
                     ]
          >

        STANDARD[TP_RamaDrzwiowa_DHZ                       ]=
          <
          PROFILE=[
                
                  ]
          >
        STANDARD[TP_RamaDrzwiowa_DHG                       ]=
          <
          PROFILE=[
                
                  ]
          >
        STANDARD[TP_RamaDrzwiowa_DHK                       ]=
          <
          PROFILE=[
                
                  ]
          >
        STANDARD[TP_RamaDrzwiowa_DWZ                      ]=
          <
          PROFILE=[
                  ]
          >
        STANDARD[TP_RamaDrzwiowa_DWBezp                   ]=
          <
          PROFILE=[
                  ]
          >
        STANDARD[TP_RamaDrzwiowa_DZBezp                   ]=
          <
          PROFILE=[
                  ]
          >

        STANDARD[TP_RamaDrzwiowa_PodzialDZ                ]=
          <
             PROFILE=[
                   PRF_PODZ_DX_ALP_W77
                     ]
          >

        STANDARD[TP_RamaDrzwiowa_PodzialDW                ]=
          <
             PROFILE=[
                   PRF_PODZ_DX_ALP_W77
                     ]
          >

        STANDARD[TP_RamaDrzwiowa_PodzialDH                ]=
          <
          PROFILE=[
                
                  ]
          >
        STANDARD[TP_RamaDrzwiowa_PodzialDWZ               ]=
          <
          PROFILE=[
                  ]
          >
        STANDARD[TP_RamaDrzwiowa_PodzialDZBezp            ]=
          <
          PROFILE=[
                  ]
          >
        STANDARD[TP_RamaDrzwiowa_PodzialDWBezp            ]=
          <
          PROFILE=[
                  ]
          >
        STANDARD[TP_RamaDrzwiowa_RuchomySlupekDZ          ]=
          <
          PROFILE=[
                 PRF_PODZ_DZ_ALP_W77_612   				 
                  ]
          >
        STANDARD[TP_RamaDrzwiowa_RuchomySlupekDW          ]=
          <
          PROFILE=[
                    				 
                  ]
          >

        STANDARD[TP_RamaDrzwiowa_ProgDZ                   ]=
          <
             PROFILE=[
                    PRF_PROG_ALP_W77_614 
                     ]
          >

        STANDARD[TP_RamaDrzwiowa_ProgDW                   ]=
          <
             PROFILE=[
                    PRF_PROG_ALP_W77_614
                     ]
          >

        STANDARD[TP_RamaDrzwiowa_ProgDH                   ]=
          <
          PROFILE=[
 
                  ]
          >
        STANDARD[TP_RamaDrzwiowa_ProgDWZ                  ]=
          <
          PROFILE=[
                  ]
          >
        STANDARD[TP_RamaDrzwiowa_ProgDZBezp               ]=
          <
          PROFILE=[
                  ]
          >
        STANDARD[TP_RamaDrzwiowa_ProgDWBezp               ]=
          <
          PROFILE=[
                  ]
          >

        STANDARD[TP_RamaDrzwiowa_SzczotkaDZ               ]=
          <
             PROFILE=[
                
                     ]
          >

        STANDARD[TP_RamaDrzwiowa_SzczotkaDW               ]=
          <
             PROFILE=[  
                   
                     ]
          >

        STANDARD[TP_RamaDrzwiowa_SzczotkaDH               ]=
          <
          PROFILE=[
               
                  ]
          >
        STANDARD[TP_RamaDrzwiowa_SzczotkaDWZ              ]=
          <
          PROFILE=[
                  ]
          >
        STANDARD[TP_RamaDrzwiowa_SzczotkaDZBezp           ]=
          <
          PROFILE=[
                  ]
          >
        STANDARD[TP_RamaDrzwiowa_SzczotkaDWBezp           ]=
          <
          PROFILE=[
                  ]
          >

        STANDARD[TP_RamaDrzwiowa_Prog2DZ                  ]=
          <
             PROFILE=[
     
                     ]
          >

        STANDARD[TP_RamaDrzwiowa_Prog2DW                  ]=
          <
             PROFILE=[

                     ]
          >

        STANDARD[TP_RamaDrzwiowa_Prog2DH                  ]=
          <
          PROFILE=[
             
                  ]
          >
        STANDARD[TP_RamaDrzwiowa_Prog2DWZ                 ]=
          <
          PROFILE=[
                  ]
          >
        STANDARD[TP_RamaDrzwiowa_Prog2DWBezp              ]=
          <
          PROFILE=[
                  ]
          >
        STANDARD[TP_RamaDrzwiowa_Prog2DZBezp              ]=
          <
          PROFILE=[
                  ]
          >

        STANDARD[TP_SkrzydloDrzwiowe_DW1Poprzeczka        ]=
          <
             PROFILE=[
                 PRF_SLP_OKIENNA_ALP_W77_301  ,
                 PRF_SLP_OKIENNA_ALP_W77_302  ,
                 PRF_SLP_OKIENNA_ALP_W77_303  ,
                 PRF_SLP_OKIENNA_ALP_W77_304  ,
                 PRF_SLP_OKIENNA_ALP_W77_305  ,
                 PRF_SLP_OKIENNA_ALP_W77_307				 
                     ]
          >

        STANDARD[TP_SkrzydloDrzwiowe_DZ1Poprzeczka        ]=
          <
             PROFILE=[
                 PRF_SLP_OKIENNA_ALP_W77_301  ,
                 PRF_SLP_OKIENNA_ALP_W77_302  ,
                 PRF_SLP_OKIENNA_ALP_W77_303  ,
                 PRF_SLP_OKIENNA_ALP_W77_304  ,
                 PRF_SLP_OKIENNA_ALP_W77_305  ,
                 PRF_SLP_OKIENNA_ALP_W77_307						 
                     ]
          >
        STANDARD[TP_SkrzydloDrzwiowe_DZ1  ]=
          <
             PROFILE=[
				     				 
                     ]
          >
        STANDARD[TP_SkrzydloDrzwiowe_DZ2  ]=
          <
             PROFILE=[
                      					 
                     ]
          >		  
        STANDARD[TP_SkrzydloDrzwiowe_DW1  ]=
          <
             PROFILE=[
	            					  
                     ]
          >		 

        STANDARD[TP_SkrzydloDrzwiowe_DH1        ]=
          <
          PROFILE=[
                
                  ]
          >
		  
        STANDARD[TP_SkrzydloDrzwiowe_DH2        ]=
          <
          PROFILE=[
                
                  ]
          >		  

        STANDARD[TP_SkrzydloDrzwiowe_DH1Poprzeczka        ]=
          <
          PROFILE=[
          
                  ]
          >
        STANDARD[TP_SkrzydloDrzwiowe_DW1BezpPoprzeczka    ]=
          <
          PROFILE=[
                  ]
          >
        STANDARD[TP_SkrzydloDrzwiowe_DZ1BezpPoprzeczka    ]=
          <
          PROFILE=[
                  ]
          >
        STANDARD[TP_RamaUniw_RamaDoFasady                 ]=
          <
             PROFILE=[
                     ]
          >

        STANDARD[TP_RamaUniw_RamaPion                     ]=
          <
              PROFILE=[
                   PRF_RAMA_OKIENNA_ALP_W77_101 ,
                   PRF_RAMA_OKIENNA_ALP_W77_102 ,
                   PRF_RAMA_OKIENNA_ALP_W77_103 ,
                   PRF_RAMA_OKIENNA_ALP_W77_104 ,
                   PRF_RAMA_OKIENNA_ALP_W77_105 
                    ]
          >

        STANDARD[TP_RamaUniw_RamaDol                      ]=
          <
              PROFILE=[
                   PRF_RAMA_OKIENNA_ALP_W77_101 ,
                   PRF_RAMA_OKIENNA_ALP_W77_102 ,
                   PRF_RAMA_OKIENNA_ALP_W77_103 ,
                   PRF_RAMA_OKIENNA_ALP_W77_104 ,
                   PRF_RAMA_OKIENNA_ALP_W77_105 			  
                      ]
          >

        STANDARD[TP_RamaUniw_RamaGora                     ]=
          <
              PROFILE=[
                   PRF_RAMA_OKIENNA_ALP_W77_101 ,
                   PRF_RAMA_OKIENNA_ALP_W77_102 ,
                   PRF_RAMA_OKIENNA_ALP_W77_103 ,
                   PRF_RAMA_OKIENNA_ALP_W77_104 ,
                   PRF_RAMA_OKIENNA_ALP_W77_105 
                      ]
          >

        STANDARD[TP_RamaUniw_RamaInna                     ]=
          <
              PROFILE=[
                   PRF_RAMA_OKIENNA_ALP_W77_101 ,
                   PRF_RAMA_OKIENNA_ALP_W77_102 ,
                   PRF_RAMA_OKIENNA_ALP_W77_103 ,
                   PRF_RAMA_OKIENNA_ALP_W77_104 ,
                   PRF_RAMA_OKIENNA_ALP_W77_105 
                     ]
          >

        STANDARD[TP_RamaUniw_PoprzeczkaPion               ]=
          <
             PROFILE=[
                	 PRF_SLP_OKIENNA_ALP_W77_301  ,
                     PRF_SLP_OKIENNA_ALP_W77_302  ,
                     PRF_SLP_OKIENNA_ALP_W77_303  ,
                     PRF_SLP_OKIENNA_ALP_W77_304  ,
                     PRF_SLP_OKIENNA_ALP_W77_305  ,
                     PRF_SLP_OKIENNA_ALP_W77_307	 
                     ]
          >

        STANDARD[TP_RamaUniw_PoprzeczkaPoziom             ]=
          <
             PROFILE=[
                	 PRF_SLP_OKIENNA_ALP_W77_301  ,
                     PRF_SLP_OKIENNA_ALP_W77_302  ,
                     PRF_SLP_OKIENNA_ALP_W77_303  ,
                     PRF_SLP_OKIENNA_ALP_W77_304  ,
                     PRF_SLP_OKIENNA_ALP_W77_305  ,
                     PRF_SLP_OKIENNA_ALP_W77_307	 
                     ]
          >

        STANDARD[TP_PAN_RAMA_2S                    ]=
          <
             PROFILE=[
			 
                     ]
          >		 

        STANDARD[TP_PAN_RAMA_2S_FIX                    ]=
          <
             PROFILE=[
			 
                     ]
          >		
 		  
        STANDARD[TP_PAN_RAMA_3S_FIX                    ]=
          <
             PROFILE=[
			 
                     ]
          >		
		  
        STANDARD[TP_PAN_RAMA_2S_PION                    ]=
          <
             PROFILE=[
			 
                     ]
          >		

        STANDARD[TP_PAN_RAMA_2S_PION_FIX_MOVE                    ]=
          <
             PROFILE=[
			 
                     ]
          >				 

        STANDARD[TP_PAN_RAMA_3S_PION_FIX_MOVE                    ]=
          <
             PROFILE=[
			 
                     ]
          >		

        STANDARD[TP_PAN_RAMA_3S_PION_FIX                    ]=
          <
             PROFILE=[
			 
                     ]
          >				  

        STANDARD[TP_PAN_RAMA_2S_PION_FIX                   ]=
          <
             PROFILE=[
			 
                     ]
          >				  

        STANDARD[TP_Prog                    ]=
          <
             PROFILE=[
			 
                     ]
          >		

        STANDARD[TP_Prog_FIX                    ]=
          <
             PROFILE=[
			 
                     ]
          >				  

        STANDARD[TP_Prog_3S_FIX                    ]=
          <
             PROFILE=[
			 
                     ]
          >				  
		  
        STANDARD[TP_PAN_PODZ12                    ]=
          <
             PROFILE=[
			 
                     ]
          >		  	

        STANDARD[TP_PAN_PODZ22                    ]=
          <
             PROFILE=[
			 
                     ]
          >		  

        STANDARD[TP_PAN_PODZ22_P90                    ]=
          <
             PROFILE=[
			 
                     ]
          >		  			  

        STANDARD[TP_PAN_PODZ23                    ]=
          <
             PROFILE=[
			 
                     ]
          >		  				  
		  
        STANDARD[TP_RamaDrzwiowa_ProgS                    ]=
          <
             PROFILE=[
                     ]
          >

        STANDARD[TP_SkrzydloSzklane_S1                    ]=
          <
             PROFILE=[
                     ]
          >

        STANDARD[TP_SkrzydloSzklane_S2                    ]=
          <
             PROFILE=[
                     ]
          >

        STANDARD[TP_SkrzydloSzklane_S3                    ]=
          <
             PROFILE=[
                     ]
          >

        STANDARD[TP_SkrzydloSzklane_SDol                  ]=
          <
             PROFILE=[
                     ]
          >

        STANDARD[TP_SkrzydloSzklane_Podzial               ]=
          <
             PROFILE=[
                     ]
          >

        STANDARD[TP_Otwor                    ]=
          <
            PROFILE=[
                    ]
          >


        STANDARD[ TP_RamaAutoOK_DoFasady                   ]=
          <
            PROFILE=[
                    ]
          >


        STANDARD[ TP_PodzialAutoOK                   ]=
          <
            PROFILE=[
                    ]
          >


        STANDARD[ TP_ProgAutoOK                   ]=
          <
            PROFILE=[

                    ]
          >


        STANDARD[ TP_RamaAutoOK_Zawias                   ]=
          <
            PROFILE=[
                    ]
          >


        STANDARD[ TP_RamaAutoOK_Klamka                   ]=
          <
            PROFILE=[
                    ]
          >


        STANDARD[ TP_PoprzeczkaAutoOK                   ]=
          <
            PROFILE=[
                    ]
          >


        STANDARD[ TP_SkrzydloAutoOK_RamaZawias                   ]=
          <
            PROFILE=[
                    ]
          >

        STANDARD[ TP_RamaAutoOK_ZawiasJakoPoprzeczka     ]=
          <
            PROFILE=[
                    ]
          >

        STANDARD[ TP_RamaAutoOK_KlamkaJakoPoprzeczka     ]=
          <
            PROFILE=[
                    ]
          >


        STANDARD[ TP_RamaUniw_Poprzeczka_O_DW            ]=
          <
            PROFILE=[
                    ]
          >

        STANDARD[ TP_RamaUniw_Poprzeczka_O_DZ            ]=
          <
            PROFILE=[
                    ]
          >
        STANDARD[ TP_11_Rama2DOL            ]=
          <
            PROFILE=[
			  
                    ]
          >		  
        STANDARD[ TP_11_Rama2            ]=
          <
            PROFILE=[
			    
                    ]
          >				  
        STANDARD[ TP_11_PodzialX            ]=
          <
            PROFILE=[
			  
                    ]
          >					
        STANDARD[ TP_11_Podzial4            ]=
          <
            PROFILE=[
			    
                    ]
          >				  
        STANDARD[ TP_11_Podzial2           ]=
          <
            PROFILE=[
			    
                    ]
          >	
		  
        STANDARD[ TP_RamaDoFasadyWentylowanej,TP_RamaDoFasadyWentylowanej_PION            ]=
          <
            PROFILE=[
                    PRF_NVF_KERAM_KLIAM_Horizontal_Keram_Wing,
					PRF_NVF_KERAM_GLUE_Horizontal_Keram_Wing,
					PRF_NVF_AKP_Horizontal_Keram_Wing
			 
	                 ]
          >
        STANDARD[TP_Skrzydlo_DH, TP_Otwor,TP_KopniakDrzwi]=
          <
             PROFILE=[
	                  				 
                     ]
          >	
        STANDARD[TP_Prog]=
          <
             PROFILE=[
	                  				 
                     ]
          >	  
        STANDARD[TP_SLUP_SKRAJ]=
          <
             PROFILE=[
	                  				 
                     ]
          >	 
        STANDARD[TP_SLUP_SKRAJ,TP_RYGIEL_GORA,TP_SLUP_SRODEK,TP_RYGIEL_SRODEK]=
          <
             PROFILE=[
	                  				 
                     ]
          >	 
        STANDARD[TP_Podzial_DH]=
          <
             PROFILE=[
	                  				 
                     ]
          >	
        STANDARD[TP_11_Skrzydlo1,TP_111_Skrzydlo1,TP_111_Skrzydlo1_dol]=
          <
             PROFILE=[
	                 					  
                     ]
          >	 			  
        STANDARD[TP_11_Skrzydlo2]=
          <
             PROFILE=[
	           					  
                     ]
          >	 	
        STANDARD[TP_111_Skrzydlo2]=
          <
             PROFILE=[
	                  					  
                     ]
          >	 			  
        STANDARD[TP_11_Skrzydlo2a,TP_111_Skrzydlo2a]=
          <
             PROFILE=[
	                  					  
                     ]
          >	 	
        STANDARD[TP_11_Skrzydlo2b]=
          <
             PROFILE=[
	                  					  
                     ]
          >	 	
        STANDARD[TP_111_Skrzydlo2b]=
          <
             PROFILE=[
	                  					  
                     ]
          >	 
        STANDARD[TP_111_Skrzydlo2c]=
          <
             PROFILE=[
	                  					  
                     ]
          >	 		  
        STANDARD[TP_11_Skrzydlo3]=
          <
             PROFILE=[
	                 				  
                     ]
          >	 		 		  
        STANDARD[TP_11_Skrzydlo3a,TP_111_Skrzydlo3a]=
          <
             PROFILE=[
	                  					  
                     ]
          >	 		
        STANDARD[TP_111_Skrzydlo4]=
          <
             PROFILE=[
	                					  
                     ]
          >	 		
        STANDARD[TP_111_Skrzydlo4a]=
          <
             PROFILE=[
	                  					  
                     ]
          >	 		
        STANDARD[TP_111_Skrzydlo4b]=
          <
             PROFILE=[
	                  					  
                     ]
          >	 			  
        STANDARD[TP_11_Podzial3]=
          <
             PROFILE=[
	                  					  
                     ]
          >	 	
        STANDARD[TP_TPB36_RamaUniw_PoprzeczkaPoziom]=
          <
             PROFILE=[
	                  					  
                     ]
          >	 	
        STANDARD[TP_TPB36_111_RamaUniw_PoprzeczkaPoziom]=
          <
             PROFILE=[
	                  					  
                     ]
          >	


        STANDARD[TP_SLIDER_WINDOW_Rama_PION]=
          <
             PROFILE=[
	                  					  
                     ]
          >	
        STANDARD[TP_SLIDER_WINDOW_Rama_GORA]=
          <
             PROFILE=[
	                  					  
                     ]
          >	
        STANDARD[TP_SLIDER_WINDOW_Rama_DOL]=
          <
             PROFILE=[
	                  					  
                     ]
          >	
        STANDARD[TP_SLIDER_WINDOW_Podzial12_poziom]=
          <
             PROFILE=[
	                  					  
                     ]
          >			  
		  
	  
        STANDARD[TP_TPB36_RamaUniw_PoprzeczkaPion]=
          <
             PROFILE=[
			 
	               					  
                     ]
          >	 	
        STANDARD[TP_TPB36_111_RamaUniw_PoprzeczkaPion]=
          <
             PROFILE=[
	               	 				   
                     ]
          >	 			  
   >
   
//**********************************************************************
// Skrzydla
//**********************************************************************

 SKRZYDLA=
      <
        STANDARD[TS_LEER_TB50                   ]=
          <
             SKRZYDLA=[
                    
                    ]
          >	 		  	  
        STANDARD[TS_LEER_TB50_T5                   ]=
          <
             SKRZYDLA=[
                    
                    ]
          >	 		  
        STANDARD[TS_111_Skrzydlo3B                   ]=
          <
             SKRZYDLA=[
                    
                    ]
          >	 	
        STANDARD[TS_111_Skrzydlo3A                   ]=
          <
             SKRZYDLA=[
                    
                    ]
          >	 				  
        STANDARD[TS_111_Skrzydlo2                   ]=
          <
             SKRZYDLA=[
                    
                    ]
          >	 	  
        STANDARD[TS_111_Skrzydlo1                    ]=
          <
             SKRZYDLA=[
                    
                    ]
          >	  	 	  
	  
        STANDARD[TS_11_Skrzydlo3                   ]=
          <
             SKRZYDLA=[
                    
                    ]
          >	 		  
        STANDARD[TS_11_Skrzydlo2                   ]=
          <
             SKRZYDLA=[
                  
                    ]
          >	 	  
        STANDARD[TS_11_Skrzydlo1                    ]=
          <
             SKRZYDLA=[
                 
                    ]
          >	  	  

		  STANDARD[TS_TKP_SK_WAH1	                    ]=
          <
             SKRZYDLA=[
                    
                    ]
          >	  	  
		  STANDARD[TS_TKP_SK_WAH2	                    ]=
          <
             SKRZYDLA=[
                    
                    ]
          >	  	
		  STANDARD[TS_TKP_SK_WAH3	                    ]=
          <
             SKRZYDLA=[
                    
                    ]
          >	  			  

        STANDARD[TS_Fasada_Strips                    ]=
          <
             SKRZYDLA=[
                    ]
          >
        STANDARD[ TS_Fasada_OknoPolaciowe                  ]=
          <
             SKRZYDLA=[
                      ]
          >

        STANDARD[ TS_Fasada_RamaStruktury                  ]=
          <
             SKRZYDLA=[
                      ]
          >

        STANDARD[ TS_Fasada_RamaPolStruktury                  ]=
          <
             SKRZYDLA=[
                      ]
          >

        STANDARD[ TS_Fasada_PolStruktura                   ]=
          <
             SKRZYDLA=[
                      ]
          >

        STANDARD[ TS_Fasada_Struktura                      ]=
          <
             SKRZYDLA=[
                      ]
          >

        STANDARD[ TS_Struktura_StrukturaSkrzydloStale      ]=
          < SKRZYDLA=[
                     ]
          >

        STANDARD[ TS_Struktura_StrukturaSkrzydloUchylne    ]=
          < SKRZYDLA=[
                     ]
          >

        STANDARD[ TS_Struktura_PolStrukturaSkrzydloStale   ]=
          < SKRZYDLA=[
                     ]
          >

        STANDARD[ TS_Struktura_PolStrukturaSkrzydloUchylne ]=
          < SKRZYDLA=[
                     ]
          >

        STANDARD[ TS_Fasada_RamaStala                      ]=
          < SKRZYDLA=[
		    
                     ]
          >
        STANDARD[ TS_Fasada_RamaStala_TOB4                      ]=
          < SKRZYDLA=[
		     
                     ]
          >		  
		STANDARD[TS_Fasada_RamaTon2]=
          < SKRZYDLA=[
		
                     ]
          >
		STANDARD[TS_Fasada_RamaTMC]=
          < SKRZYDLA=[
			 
                     ]
          >		  
		STANDARD[TS_Fasada_RamaTon4]=
          < SKRZYDLA=[
		
                     ]
          >		  
		STANDARD[TS_Fasada_RamaTOT]=
          < SKRZYDLA=[
			
                     ]
          >			  
//*************************************************************************
		STANDARD[TS_Fasada_RamaOps1]=
          < SKRZYDLA=[
	
                     ]
          >
		STANDARD[TS_Fasada_RamaHOP]=
          < SKRZYDLA=[
			
                     ]
          >		  
//*************************************************************************

        STANDARD[ TS_Fasada_RamaStala_DACH                      ]=
          < SKRZYDLA=[
                     ]
          >

        STANDARD[ TS_Fasada_RamaOkienna                    ]=
          <
             SKRZYDLA=[
 
                     ]
          >
		  
        STANDARD[ TS_Fasada_RamaOkienna_PVC                    ]=
          <
             SKRZYDLA=[
                     ]
          >
		  
  
        STANDARD[ TS_Fasada_RamaRigelOkienna             ]=
          <
             SKRZYDLA=[
					  
                     ]
          >		  

        STANDARD[ TS_Fasada_Vent_Reshetki_TBR1]=
          <
             SKRZYDLA=[
                      			  
                     ]
          >		  		  
        STANDARD[ TS_Fasada_Vent_Reshetki_TBR2]=
          <
             SKRZYDLA=[
                      			  
                     ]
          >		  
        STANDARD[ TS_Dveri_Vent_Reshetki_TBR2]=
          <
             SKRZYDLA=[
                      			  
                     ]
          >		
        STANDARD[ TS_Dveri_Vent_Reshetki_TBR1]=
          <
             SKRZYDLA=[
                      			  
                     ]
          >				  
        STANDARD[ TS_Fasada_RamaOkienna_Holod ]=
          <
             SKRZYDLA=[
                      			  
                     ]
          >	

        STANDARD[ TS_Peregorodka2_RamaOW ]=
          <
             SKRZYDLA=[
                    
                     ]
          >	
        STANDARD[ TS_Peregorodka_RamaOW ]=
          <
             SKRZYDLA=[
                      
                     ]
          >	

        STANDARD[ TS_Fasada_RamaOkienna_TBM                    ]=
          <
             SKRZYDLA=[
                    				  
                     ]
          >		  
        STANDARD[ TS_Fasada_RamaOkienna_T38                    ]=
          <
             SKRZYDLA=[
                      					  
                     ]
          >		 
        STANDARD[ TS_Peregorodka_RamaOkienna_T38]=
          <
             SKRZYDLA=[
                      					  
                     ]
          >				  
        STANDARD[ TS_Fasada_RamaBalkonna                    ]=
          <
             SKRZYDLA=[
                  
                     ]
          >	
        STANDARD[ TS_Fasada_RamaBalkonna_TBM                ]=
          <
             SKRZYDLA=[
               				  
                     ]
          >			  
        STANDARD[ TS_Fasada_RamaUniwers
                    ]=
          < SKRZYDLA=[
                     ]
          >

        STANDARD[ TS_Fasada_RamaOkiennaZ                   ]=
          < SKRZYDLA=[
                     ]
          >

        STANDARD[ TS_Fasada_RamaDW                         ]=
          <
             SKRZYDLA=[
		             WNG_RAMA_DWF_W77_404
                      ]
          >

        STANDARD[ TS_Fasada_RamaDW_TBM                         ]=
          <
             SKRZYDLA=[
                 				  
                      ]
          >		  
		  
        STANDARD[ TS_Fasada_RamaDZ                         ]=
          <
             SKRZYDLA=[
                   WNG_RAMA_DZF_W77_403
                      ]
          >
		  
        STANDARD[ TS_Fasada_RamaDZ_TBM                         ]=
          <
             SKRZYDLA=[
                				  
                      ]
          >
		  
        STANDARD[ TS_Fasada_RamaDZ_D40                        ]=
          <
             SKRZYDLA=[
                    				  
                      ]
          >	
        STANDARD[ TS_Fasada_RamaDW_D40                        ]=
          <
             SKRZYDLA=[
                 					  
                      ]
          >			  
        STANDARD[ TS_Peregorodka_RamaDZ                 ]=
          <
             SKRZYDLA=[
                      ]
          >	
        STANDARD[ TS_Peregorodka_RamaDW                 ]=
          <
             SKRZYDLA=[
               					  
                      ]
          >		  
  
        STANDARD[ TS_Fasada_RamaDH                         ]=
          <
             SKRZYDLA=[
                      ]
          >

        STANDARD[ TS_Fasada_RamaDWZ                        ]=
          <
             SKRZYDLA=[
                      ]
          >

        STANDARD[ TS_Fasada_RamaDWBezp                     ]=
          <
             SKRZYDLA=[
                      ]
          >

        STANDARD[ TS_Fasada_RamaDZBezp                     ]=
          <
             SKRZYDLA=[
                      ]
          >

        STANDARD[ TS_Fasada_RamaDAuto2                     ]=
          <
             SKRZYDLA=[
                      ]
          >

        STANDARD[ TS_Fasada_RamaDAuto3                     ]=
          <
             SKRZYDLA=[
                      ]
          >


        STANDARD[ TS_RamaOkienna_OW1                       ]=
          <
             SKRZYDLA=[
	                	WNG_SKRZ_OK1_W77_201_UR	  
                      ]
          >
        STANDARD[ TS_RamaOkienna_PVC_OW1                  ]=
          <
             SKRZYDLA=[
               			WNG_SKRZ_OK1_W77_205_UR  
                      ]
          >	
        STANDARD[ TS_RamaOkienna_PVC_OW2                  ]=
          <
             SKRZYDLA=[
        			    WNG_SKRZ_OK2_W77_205_UR  
                      ]
          >				  
        STANDARD[ TS_RamaOkienna_PVC_OW3                  ]=
          <
             SKRZYDLA=[
              			  
                      ]
          >		  
        STANDARD[ TS_RamaOkienna_T38                      ]=
          <
             SKRZYDLA=[
	            
                      ]
          >
        STANDARD[ TS_RamaOkienna_OW2                      ]=
          <
             SKRZYDLA=[
				  WNG_SKRZ_OK2_W77_201_UR
                      ]
          >

        STANDARD[ TS_RamaOkienna_OW3                      ]=
          <
             SKRZYDLA=[
				  
                      ]
          >
        STANDARD[ TS_RamaOkienna_OW2v                     ]=
          <
          SKRZYDLA=[
                   ]
          >

        STANDARD[ TS_RamaOkienna_OW3v                      ]=
          <
          SKRZYDLA=[
                   ]
          >

        STANDARD[ TS_RamaOkienna_OUP1                      ]=
          <
             SKRZYDLA=[
					   ]
          >

        STANDARD[ TS_RamaOkienna_OUP2                      ]=
          <
             SKRZYDLA=[]
          >

        STANDARD[ TS_RamaOkienna_OUP3                      ]=
          <
             SKRZYDLA=[]
          >

        STANDARD[ TS_RamaOkienna_OZ1                       ]=
          <
          SKRZYDLA=[
                    ]
           >

         STANDARD[ TS_RamaOkienna_OZ2                       ]=
         <
            SKRZYDLA=[
                       ]
           >

         STANDARD[ TS_RamaOkienna_OZ3                       ]=
           <
              SKRZYDLA=[
                       ]
           >


        STANDARD[ TS_RamaOkienna_Obrotowe                  ]=
          <
          SKRZYDLA=[
                   ]
          >

        STANDARD[ TS_RamaOkienna_OBW1                      ]=
          <
             SKRZYDLA=[
			   				
                      ]
          >

        STANDARD[ TS_RamaOkienna_OBW2                      ]=
          <
             SKRZYDLA=[
			   						
                      ]
          >

        STANDARD[ TS_RamaOkienna_OBW3                      ]=
          <
             SKRZYDLA=[
			      					
                      ]
          >

        STANDARD[ TS_RamaOkienna_OBZ1                      ]=
          <
             SKRZYDLA=[
                      ]
          >

        STANDARD[ TS_RamaOkienna_OBZ2                      ]=
          <
             SKRZYDLA=[
                      ]
          >

        STANDARD[ TS_RamaOkienna_OBZ3                      ]=
          <
             SKRZYDLA=[
                      ]
          >


        STANDARD[ TS_RamaOkienna_SkrzydloHarmonijkowe      ]=
          <
             SKRZYDLA=[
                      ]
          >

        STANDARD[ TS_RamaOkienna_SkrzydloO1Posz            ]=
          <
             SKRZYDLA=[
                      ]
          >

        STANDARD[ TS_RamaOkienna_SkrzydloO2Posz            ]=
          <
             SKRZYDLA=[
                      ]
          >

        STANDARD[ TS_RamaOkienna_SkrzydloO3Posz            ]=
          <
             SKRZYDLA=[
                      ]
          >

        STANDARD[ TS_RamaOkienna_PodawczePionStale         ]=
          <
             SKRZYDLA=[
                      ]
          >

        STANDARD[ TS_RamaOkienna_PodawczePionRuch          ]=
          <
             SKRZYDLA=[
                      ]
          >

        STANDARD[ TS_RamaOkienna_PodawczePoziomStale       ]=
          <
             SKRZYDLA=[
                      ]
          >

        STANDARD[ TS_RamaOkienna_PodawczePoziomRuch        ]=
          <
             SKRZYDLA=[
                      ]
          >


        STANDARD[ TS_Drzwi_DW1                             ]=
          <
            SKRZYDLA=[
                 	WNG_SKRZ_DW1_W77_502				 
                     ]
          >
		STANDARD[ TS_Drzwi_T38_Fasad                        ]=
          <
            SKRZYDLA=[

                     ]
          >
		STANDARD[ TS_Drzwi_DZ_D40                             ]=
          <
            SKRZYDLA=[
                   
                     ]
					           >
		STANDARD[ TS_Drzwi_DW_D40                             ]=
          <
            SKRZYDLA=[
                   				 
                     ]
					           >							   
        STANDARD[ TS_Drzwi_DW2                             ]=
          <
            SKRZYDLA=[
               		WNG_SKRZ_DW2_W77_502			 
                     ]
          >

        STANDARD[ TS_Drzwi_DW2_D40                             ]=
          <
            SKRZYDLA=[
                   
                     ]
          >
		  
        STANDARD[ TS_Drzwi_DW3                             ]=
          <
            SKRZYDLA=[
               		WNG_SKRZ_DW3_W77_502			 
                     ]
          >
		  
        STANDARD[ TS_Drzwi_DW3_D40                             ]=
          <
            SKRZYDLA=[
               			 
                     ]
          >
		  
        STANDARD[ TS_Drzwi_DW3v                             ]=
          <
            SKRZYDLA=[
                 	WNG_SKRZ_DW3_W77_502rs					 
                     ]
          >

        STANDARD[ TS_Drzwi_DZ1                             ]=
          <
            SKRZYDLA=[
                    WNG_SKRZ_DZ1_W77_501 			 
                     ]
          >

        STANDARD[ TS_Drzwi_DZ2                             ]=
          <
            SKRZYDLA=[
               		WNG_SKRZ_DZ2_W77_501						 
                     ]
          >
		  
        STANDARD[ TS_Drzwi_DZ2_D40                             ]=
          <
            SKRZYDLA=[		  
              					 
                     ]
          >		  

        STANDARD[ TS_Drzwi_DZ3                             ]=
          <
            SKRZYDLA=[
                   WNG_SKRZ_DZ3_W77_501 								 
                     ]
          >

        STANDARD[ TS_Drzwi_DZ3_D40                             ]=
          <
            SKRZYDLA=[
                  					 
                     ]
          >
		  
        STANDARD[ TS_Drzwi_DZ3v                             ]=
          <
            SKRZYDLA=[
                	WNG_SKRZ_DZ3_W77_501rs			 
                     ]
          >

        STANDARD[ TS_Drzwi_DH1                             ]=
          <
             SKRZYDLA=[
                
                      ]
          >

        STANDARD[ TS_Drzwi_DH2                             ]=
          <
             SKRZYDLA=[
                
                      ]
          >

        STANDARD[ TS_Drzwi_DH3                             ]=
          <
             SKRZYDLA=[
                
                      ]
          >

        STANDARD[ TS_Drzwi_DWZ_W                           ]=
          <
             SKRZYDLA=[
                      ]
          >

        STANDARD[ TS_Drzwi_DWZ_Z                           ]=
          <
             SKRZYDLA=[
                      ]
          >

        STANDARD[ TS_Drzwi_DW1b                            ]=
          <
             SKRZYDLA=[
			        WNG_SKRZ_DW1_W77_502
                      ]
          >

        STANDARD[ TS_Drzwi_DW2b                            ]=
          <
             SKRZYDLA=[
                      ]
          >

        STANDARD[ TS_Drzwi_DW3b                            ]=
          <
             SKRZYDLA=[
                      ]
          >

        STANDARD[ TS_Drzwi_DZ1b                            ]=
          <
             SKRZYDLA=[
                      ]
          >

        STANDARD[ TS_Drzwi_DZ2b                            ]=
          <
             SKRZYDLA=[
                      ]
          >

        STANDARD[ TS_Drzwi_DZ3b                            ]=
          <
             SKRZYDLA=[
                      ]
          >

        STANDARD[ TS_Tafla1                                ]=
          <
             SKRZYDLA=[
                      ]
          >

        STANDARD[ TS_Tafla2                                ]=
          <
             SKRZYDLA=[
                      ]
          >

        STANDARD[ TS_Tafla3                                ]=
          <
             SKRZYDLA=[
                      ]
          >

        STANDARD[ TS_RamaAutomatu_Skrzydlo12R              ]=
          <
             SKRZYDLA=[
                      ]
          >

        STANDARD[ TS_RamaAutomatu_Skrzydlo22R              ]=
          <
             SKRZYDLA=[
                      ]
          >

        STANDARD[ TS_RamaAutomatu_Skrzydlo22R2             ]=
          <
             SKRZYDLA=[
                      ]
          >

        STANDARD[ TS_RamaAutomatu_Skrzydlo13R              ]=
          <
             SKRZYDLA=[
                      ]
          >

        STANDARD[ TS_RamaAutomatu_Skrzydlo23R              ]=
          <
             SKRZYDLA=[
                      ]
          >

        STANDARD[ TS_RamaAutomatu_Skrzydlo33R              ]=
          <
             SKRZYDLA=[
                      ]
          >

        STANDARD[ TS_RamaAutomatu_Skrzydlo33R2             ]=
          <
             SKRZYDLA=[
                      ]
          >

        STANDARD[ TS_RamaAutomatu_Skrzydlo12S              ]=
          <
             SKRZYDLA=[
                      ]
          >

        STANDARD[ TS_RamaAutomatu_Skrzydlo13S              ]=
          <
             SKRZYDLA=[
                      ]
          >

        STANDARD[ TS_Otwor ]=
          < SKRZYDLA=[
                     ]
          >

        STANDARD[ TS_AutomatOK_RamaDoFasady ]=
          < SKRZYDLA=[
                     ]
          >

        STANDARD[ TS_AutomatOK_Skrzydlo1 ]=
          < SKRZYDLA=[
                     ]
          >

        STANDARD[ TS_AutomatOK_Skrzydlo2 ]=
          < SKRZYDLA=[
                     ]
          >

        STANDARD[ TS_AutomatOK_Skrzydlo3 ]=
          < SKRZYDLA=[
                     ]
          >
    
        STANDARD[ TS_RamaOkienna_SkrzydloHarmonijkowe]=
          <
          SKRZYDLA=[
                   ]
          >
        STANDARD[ TS_Drzwi_DB1 ]=
          <
          SKRZYDLA=[
                   ]
          >

        STANDARD[TS_Drzwi_DB2 ]=
          <
          SKRZYDLA=[
                   ]
          >
        STANDARD[TS_Drzwi_DB3 ]=
          <
          SKRZYDLA=[
                   ]
          >
        STANDARD[TS_Drzwi_DB4  ]=
          <
          SKRZYDLA=[
                   ]
          >
        STANDARD[TS_Drzwi_DB5  ]=
          <
          SKRZYDLA=[
                   ]
          >
        STANDARD[TS_Drzwi_DB6  ]=
          <
          SKRZYDLA=[
                   ]
          >
       STANDARD[TS_Drzwi_DB7  ]=
          <
          SKRZYDLA=[
                   ]
          >
       STANDARD[TS_Drzwi_DB8  ]=
          <
          SKRZYDLA=[
                   ]
          >
       STANDARD[TS_Drzwi_DB1a  ]=
          <
          SKRZYDLA=[
                   ]
          >
       STANDARD[TS_Drzwi_DB3a   ]=
          <
          SKRZYDLA=[
                   ]
          >

	  STANDARD[ TS_Drzwi_DB9 ]=
          <
          SKRZYDLA=[
                   ]
          >

        STANDARD[TS_Drzwi_DB10 ]=
          <
          SKRZYDLA=[
                   ]
          >
		  
        STANDARD[TS_Drzwi_DB11 ]=
          <
          SKRZYDLA=[
                   ]
          >
		  
        STANDARD[TS_Drzwi_DB12  ]=
          <
          SKRZYDLA=[
                   ]
          >
		  
        STANDARD[TS_Drzwi_DB13  ]=
          <
          SKRZYDLA=[
                   ]
          >
		  
        STANDARD[TS_Drzwi_DB14  ]=
          <
          SKRZYDLA=[
                   ]
          >
		  
       STANDARD[TS_Drzwi_DB15  ]=
          <
          SKRZYDLA=[
                   ]
          >
		  
       STANDARD[TS_Drzwi_DB16  ]=
          <
          SKRZYDLA=[
                   ]
          >
		  
       STANDARD[TS_Drzwi_DB9a  ]=
          <
          SKRZYDLA=[
                   ]
          >
		  
       STANDARD[TS_Drzwi_DB11a   ]=
          <
          SKRZYDLA=[
                   ]
          >
		  
       STANDARD[ TS_AutomatOk_skrzydlo1  ]=
          <
          SKRZYDLA=[
                   ]
          >
		  
       STANDARD[ TS_AutomatOk_skrzydlo2  ]=
          <
          SKRZYDLA=[
                   ]
          >
		  
       STANDARD[ TS_AutomatOk_skrzydlo3  ]=
          <
          SKRZYDLA=[
                   ]
          >
       STANDARD[ TS_SLIDE_S33A  ]=
          <
          SKRZYDLA=[
		  
                   ]
          >		
       STANDARD[ TS_SLIDE_S32 ]=
          <
          SKRZYDLA=[
		  
                   ]
          >		
       STANDARD[ TS_SLIDE_S31_FIX ]=
          <
          SKRZYDLA=[
		  
                   ]
          >				  
>


    SZPROSY=[

	]
    SZPROSY=[

	]
	

 
 WARUNEK_DLA_DRUGIEGO_SZKLA='NUMER_SZYBY'
    SZYBA_ZLOZONA=[
	              SZYBA_2,     //0
				  SZYBA_3      //1
				  ]
    SZYBA1=[
	       EGLASS24,    //0
		   EGLASS50     //1
		   ]
	NAZWA_SZKLA_STANDARDOWEGO='24mm – стандартный стеклопакет'
    NAZWA_SZKLA_STANDARDOWEGO='50mm - стандартное стекло'
  >
