PODSYSTEMY=
  <
PODSYSTEM[DEF_SYS_F50]=
      <
        NAZWA       = 'F50 - Ôàñàä'
        OPIS        = 'Ôàñàä F50. Øèðèíà ïðîôèëþ 50ìì'
        KATEGORIA   = 'Ôàñàäè'
        RYSUNEK     = 'F50.BMP'
        KOD         = 'F50'
      >
PODSYSTEM[DEF_SYS_W77]=
      <
        NAZWA       = 'W77 - Â³êíà òà äâåð³'
        OPIS        = 'Â³êíà òà äâåð³ W77. Øèðèíà ïðîôèëþ 77ìì'
        KATEGORIA   = 'Â³êíà òà äâåð³'
        RYSUNEK     = 'W77.BMP'
        KOD         = 'W77'
      >	
PODSYSTEM[DEF_SYS_C50]=
      <
        NAZWA       = 'C50 - Â³êíà òà äâåð³'
        OPIS        = 'Â³êíà òà äâåð³ C50. Øèðèíà ïðîôèëþ 50ìì'
        KATEGORIA   = 'Â³êíà òà äâåð³'
        RYSUNEK     = 'C50.BMP'
        KOD         = 'C50'
      >	 	  
PODSYSTEM[DEF_SYS_NVF_KERAM_KLIAM]=
      <
        NAZWA       = 'Ïëèòè êåðàìîãðàí³òó íà êëÿéìåðàõ'
        OPIS        = 'Ïëèòè êåðàìîãðàí³òó íà êëÿéìåðàõ'
        KATEGORIA   = 'ÑÈÑÒÅÌÀ ÍÀÂ²ÑÍÈÕ ÂÅÍÒÈËÜÎÂÀÍÈÕ ÔÀÑÀÄ²Â'
        RYSUNEK     = 'NVF_KERAM_KLIAM.BMP'
        KOD         = 'NVF'
      >	 	
PODSYSTEM[DEF_SYS_NVF_AKP]=
      <
        NAZWA       = 'Êàñåòè ç ÀÊÏ'
        OPIS        = 'Êàñåòè ç ÀÊÏ'
        KATEGORIA   = 'ÑÈÑÒÅÌÀ ÍÀÂ²ÑÍÈÕ ÂÅÍÒÈËÜÎÂÀÍÈÕ ÔÀÑÀÄ²Â'
        RYSUNEK     = 'NVF_AKP.BMP'
        KOD         = 'NVF'
      >	 		  
>


